### ISSUE TITLE
Nimbus - OMG Thank You!!

### ISSUE THREAD

**Issue by meesterexx** [ivarbrandt/skin.nimbus#1]
Not a problem or issue, just a Big Fat Thank You!! 
Saw this in the repo, had no idea what it was and had to try it on a test build (with Fen Light) and was blown away! It's exactly what I've wanted with the home screen and the Flix view!

Thank you so much, can't wait for this (and Fen Light) to go to official release!

Feel free to close this, just wanted to tell you how much it is sincerely appreciated. 
(BTW, Do you have a tip/donate link? Asking seriously.)

**Comment by ivarbrandt** [comment]
Yeeee it's sick huh :) I appreciate your enthusiasm! I feel like I should let you know though that Nimbus is going to be a personal project just for me. It might not ever be officially released. It was supposed to be a lighter version of FENtastic with less features but then I had a few ideas and here we are lol.

That being said it will be in the test repo and I will continue to work on it but I won't be taking any feature requests.

Also please keep in mind that as I work on it, it will "break" multiple times. Not to where its unusable but certain sections/menus won't look right until I get to them.

I have a Kofi and you can find the link [here](https://ko-fi.com/ivarbrandt). Thank you!

**Comment by meesterexx** [comment]
I'm cool with all that as long as I have access to it!
Seriously, it's beatiful.

btw, done:
![nimbus](https://github.com/ivarbrandt/skin.nimbus/assets/13154733/f9159b7f-cc2f-4491-9881-edac363eb257)

**Comment by ivarbrandt** [comment]
Thanks so much!

And yes, you'll definitely continue to have access to it.

**Comment by Zero0Q** [comment]
I just want to say tank you for the best so far skin, I been waiting for this long time now. I will buy you couple beers for such wonderful Christmas gift. Thanks bro :)

**Comment by ivarbrandt** [comment]
> I just want to say tank you for the best so far skin, I been waiting for this long time now.

Awesome and thank you for your support! I'm glad you're enjoying it.

**Comment by Zero0Q** [comment]
> > I just want to say tank you for the best so far skin, I been waiting for this long time now.
> 
> 
> 
> Awesome and thank you for your support! I'm glad you're enjoying it.

No worries mate, happy to help. The skin is awesome it works well within fen addon, I have switched to local libraries playlists and everything works except ratings in Home Screen. ![image](https://github.com/ivarbrandt/skin.nimbus/assets/20936968/c582e3b5-dcbf-4ba1-a366-da70d8d6a051)

**Comment by ivarbrandt** [comment]
I can't test because I don't use local libraries.

Also, same as FENtastic, the skin is designed for use with Fen.

**Comment by ivarbrandt** [comment]
Library widgets will always load faster than addon widgets.

That being said mine take about a second to load per widget. The skin is pretty light.

Make sure that the widgets don't have too many items. I cap mine out at 20 items per widget. Set the limit in the Fen addon.

**Comment by Zero0Q** [comment]
Thanks mate, I did put limit in fen to 50 for widgets only but it still loads all of them, even if I specify directly in widget_movies.xml to load 50 widgets it's not working.

**Comment by Zero0Q** [comment]
It's all good now, everything is working🙂

**Comment by ivarbrandt** [comment]
> It's all good now, everything is working

Awesome! Is it faster now?

**Comment by Zero0Q** [comment]
Much faster, I edited my trakt lists to 100 items. Fen was working with items limitations only thing I was getting is next page in widgets even though I disabled it in fen. Anyways this is a back door fix😅

**Comment by Zero0Q** [comment]
I have few ideas if it's possible to integrate in to skin, I'm not sure if you know how Titan binge mod skin looks like, so if you could add in your skin episodes view like in the picture and video info dialog like in Titan binge mod has with play next episodes if it's a show or play if it's a movie that way we don't need to enter the show to look what we played last.![image](https://github.com/ivarbrandt/skin.nimbus/assets/20936968/e5f4d43c-43bd-4fc7-b31e-eaa7770f03f0)

![image](https://github.com/ivarbrandt/skin.nimbus/assets/20936968/f69ca05a-8b92-4478-a09a-d1f45e13cbc3)

**Comment by ivarbrandt** [comment]
I'm not sure if you saw the first few comments above. 

In case you didn't, I specifically stated that I will not be taking any requests for this skin. 

It will continue to be available in the test repo but it comes as is.

**Comment by ivarbrandt** [comment]
All good man.

The layout is like Netflix with the fanart, info, clearlogo, and widget positioning. But the similarities end there.
