### ISSUE TITLE
 Kodi Omega has been released, an update is needed plz. 

### ISSUE THREAD

**Issue by kim1406** [ivarbrandt/skin.nimbus#10]
Thanks for this great skin. We are waiting for the update to support Kodi Omega plz.

**Comment by ivarbrandt** [comment]
`0.0.95` is now compatible with Omega. Keep in mind that I haven't tested everything yet and this skin is still in development.

**Comment by kim1406** [comment]
Great. Thanks for your fast response. I will test and inform.

**Comment by kim1406** [comment]
Just to let you know that, I love this skin very much. I'm using it now on my Omega build and it is working great. It is the best skin so far. THANK YOU.
