### ISSUE TITLE
No Auto Info at all in CoreElec

### ISSUE THREAD

**Issue by dm2912** [ivarbrandt/skin.nimbus#100]
Nimbus 1.0.24
CoreElec 21.1.1

Getting no auto-info at all using widgets from both

+ Library
+ TMDB Helper

in both instances it fades out the unselected items, but no info appears

In library I do at least get a studio icon appears, but nothing else

**Comment by ivarbrandt** [comment]
Nimbus has been reverted back to the Netflix layout.
