### ISSUE TITLE
Nimbus Reversion

### ISSUE THREAD

**Issue by ivarbrandt** [ivarbrandt/skin.nimbus#101]
Nimbus has been reverted back to the Netflix layout. I've attached the multi-widget skin and helper version below.

Skin: https://github.com/ivarbrandt/repository.ivarbrandt/raw/master/repo/zips/skin.nimbus/skin.nimbus-0.1.24.zip
Helper: https://github.com/ivarbrandt/repository.ivarbrandt/raw/master/repo/zips/script.nimbus.helper/script.nimbus.helper-0.0.43.zip

If you updated and made stacked widgets, these will no longer work. Changing the widget display type to one that is available will fix any issues you may encounter with this. 

The Netflix layout is the version that will be maintained and developed going forward.

**Comment by Sacramil1** [comment]
Why the revert if you don't mind me asking? That update with stacked widgets was amazing

**Comment by ivarbrandt** [comment]
Because this update was an impulsive one. Also, I didn't fully grasp how such a sudden drastic change would impact people. 

I was going through a lot when I first started really changing it. But after the situation I was going through passed, I realized that the multi-widget layout (where stacked widgets are a possibility) doesn't fit the original design of Nimbus (which is the Netflix layout).

I like to tinker/tweak when I'm going through things. But with so many people relying on my repo, I realized that I need to make those changes in a separate project of my own so I don't pull what I just did.

**Comment by Merc337** [comment]
I usually don't insert myself into these conversations, but I feel a message is needed from all of us real Kodi users who don't write messages on reddit. We just check for important updates, and don't get involved in the conversations. I have been customizing and learning the new skin today, and man, oh man, this is by far the best skin I've ever used. Please don't let these novice knuckleheads make us real users lose this masterpiece. Thank you for all your hard work. 0.1.24 is the GOAT

**Comment by Sacramil1** [comment]
> Because this update was an impulsive one. Also, I didn't fully grasp how such a sudden drastic change would impact people.
> 
> I was going through a lot when I first started really changing it. But after the situation I was going through passed, I realized that the multi-widget layout (where stacked widgets are a possibility) doesn't fit the original design of Nimbus (which is the Netflix layout).
> 
> I like to tinker/tweak when I'm going through things. But with so many people relying on my repo, I realized that I need to make those changes in a separate project of my own so I don't pull what I just did.

Makes sense.   I look forward to a possible future project with those features. Your skins are so light compared to others I use and that stacked widget function set it over the top.

**Comment by 36-chambers** [comment]
For what it's worth I prefer the Netflix layout. The stacked layout was nice too, but I'd definitely suggest putting that in another skin somewhere. I like the original minimalistic design.

**Comment by Guguloi** [comment]
Man I love your work. Both Fentastic and Nimbus are awesome skins, each to his own.
I like Nimbus more because simplicity. And great looking. And speed.
So I was a little puzzled when a saw Fentastic v2.0 instead of Nimbus but hey, it's your work so I respect that. Reverted to 1.23 and that's it.
Now in the morning you made me a great surprise with this reversion. Thank you from the bottom of my heart.

**Comment by derrgoo** [comment]
I think it's pretty great the new one. It is so fast and designed well. Innovative design not seen before. 

I hope you decide to leave but always your decision and thanks for all your efforts. All keep a backup hopefully it doesn't break anytime soon. 😉

**Comment by hcgiub001** [comment]
I've made a post here to inform them of your decision
https://www.reddit.com/r/Addons4Kodi/comments/1fhy2tn/nimbus_1025_update_nimbus_has_been_reverted_back/

I've deleted the previous thread. 
I'm sure you put in allot of work into the widget style and learnt allot. whatever skin you choose is the one I'll support. Happy Monday!

**Comment by dm2912** [comment]
shame, installed and tried it out purely for stacked widgets

netflix style skins are ten-a-penny

**Comment by ivarbrandt** [comment]
I appreciate everyone's opinion. Both versions are easily installable and will work for quite some time. At this point, it's a matter of preference.

**Comment by Nuklear92** [comment]
> I appreciate everyone's opinion. Both versions are easily installable and will work for quite some time. At this point, it's a matter of preference.

To be honest, I'm personally more fan of the Netflix style theme. But, that doesn't mean In the future you could create an optional choice for homescreen layout, similar to for example skins like AuraMod, where the user can choose between a multi-widget style homescreen, Netflix, basic styles, etc. So everyone has a choice. Personally, I think the current Netflix style has many potential to be even broader without going over the top like Arctic Fuse which has a similar thematic. I believe in the near future you can take some cues from it to improve over your own Netflix style theme, perhaps by adding the submenus widget style as that skin do. 

You could install that skin one day and just navigate around at all the things it can be done with that layout and perhaps grab some key ideas that will enhance the user experience and implement it in your own way and style that would keep the minimalistic aspect, speed and reliability of the skin.

That's just my sincere opinion on the matter. Either way, I think your skin is fantastic and as I had mentioned previously it has a lot potential, just don't abandon it yet to start another skin project. Which many skinners tend to do when they get new ideas, hehe! I'm still hoping to see this skin grow more and it's going in a good path as it currently sits. 👍

**Comment by hcgiub001** [comment]
I just thought you might want to hear this

![image](https://github.com/user-attachments/assets/6da3e2a7-cc46-4253-b6af-eae7ad9fa19a)
