### ISSUE TITLE
[BUG] once it dims, it won't undim without skin reload

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#103]
have been experiencing this for a while, someone mentioned it on reddit too

https://streamable.com/gvyl2t

I'm using Kodi on windows and alt-tab into other windows and come back to kodi and if it's dimmed, most time it won't undim unless I reload skin. 
thanks

EDIT: in the video I reloaded the skin, it did not undim on its own

**Comment by hcgiub001** [comment]
Didn't think of that. Loaded Estuary and had the same result
https://streamable.com/291808
thanks

**Comment by ivarbrandt** [comment]
Might be a Kodi bug. Check the screensaver settings as well.

**Comment by hcgiub001** [comment]
thanks, I'll check both, It's happened last week I noticed. but I have a script to reload skin with one click so it's not so bad. I have been using custom xml files outside the range of what kodi said to use (10850)
could be to do with that, I want to show you later what I cam up with, it's kind of cool but still working on it (no coding, manually) want your thoughts on the concept

**Comment by ivarbrandt** [comment]
> want your thoughts on the concept

Sure thing. 

Btw, I added the configurable delay back in for the auto info in PosterView. I had to quickly revert it back to the Netflix type layout and with that all the other changes in the update got reverted too.

**Comment by hcgiub001** [comment]
nice! love that viewtype thanks
