### ISSUE TITLE
Using both versions of Nimbus

### ISSUE THREAD

**Issue by derrgoo** [ivarbrandt/skin.nimbus#104]
I understand you will not be updating on non Netflix version. However, I have a question about using both Netflix and non Netflix on my kodi build.( be able to switch skins) However, I am unclear what I need to rename to get both working. Is this something you can point out or is it a huge undertaking? Or just use a fork and have two kodis reside on my box?

**Comment by ivarbrandt** [comment]
You'd need to rename the skin id in `addon.xml` and all mentions of 'nimbus' in the codebase. There's 536 references in the the skin and 82 in the helper. If you're familiar with code it's relatively straightforward. If not, I'd just go the separate fork route.

Why do you want to have both versions?

**Comment by derrgoo** [comment]
My wife loves Netflix and I love the new one because of stacked widgets. Hers is just simple. 😂

**Comment by derrgoo** [comment]
All just do fork because I am not familiar where the code base is. Thanks. 🙏

**Comment by ivarbrandt** [comment]
Lol I understand. The Netflix layout is cleaner. The stacked layout is more functional.

> All just do fork because I am not familiar where the code base is. Thanks. 🙏

Sounds good. Enjoy :)
