### ISSUE TITLE
Bug in posterflow view of movie collections 

### ISSUE THREAD

**Issue by basicals** [ivarbrandt/skin.nimbus#105]
Latest .26 version. 
Items are shown multiple times:
![PXL_20240918_074141826](https://github.com/user-attachments/assets/8db687ec-0c09-433b-809a-7b3716f6ac1e)
How to reproduce: set nimbus to go into a movie collection when selecting a movie that belongs to one.

Btw the posterflow view is super interesting, gonna give it a whirl!

**Comment by ivarbrandt** [comment]
This isn't a bug. It's how the wraplist within Kodi works.
