### ISSUE TITLE
No clear logo using umbrella

### ISSUE THREAD

**Issue by derrgoo** [ivarbrandt/skin.nimbus#106]
Hi, just wondering is this is a skin issue or addon. If addon I can post there and see if dev responds. Thanks

![image](https://github.com/user-attachments/assets/aa39cd20-2ee7-4808-b1b8-621b26c99d12)

**Comment by ivarbrandt** [comment]
> Hi, just wondering is this is a skin issue or addon.

Could be neither. Make sure you have clearlogo enabled in Skin settings > On screen display. If you do and you still don't see it, then it probably isn't available. The skin falls back to the text title when clearlogo isn't available.

Also, try setting up fanart.tv artwork if you haven't. They tend to have more clearlogos available compared to TMDb.

**Comment by derrgoo** [comment]
All on in settings all try fanart tv as suggested. All let you know.

**Comment by derrgoo** [comment]
I put in fanart details. I also tested same series with POV. POV shows but umbrella still not.

**Comment by ivarbrandt** [comment]
Then it's likely an addon issue.

**Comment by derrgoo** [comment]
Okay. All contact dev and see. Thank you. (Closed)

**Comment by Kryosiris** [comment]
I can see clearlogo on episode lists using umbrella on ah2 and auramod but not on nimbus

**Comment by ivarbrandt** [comment]
> I can see clearlogo on episode lists using umbrella on ah2 and auramod but not on nimbus

Thanks for this info. That means that the problem lies with Nimbus and not Umbrella. I'll work on a fix.

**Comment by derrgoo** [comment]
Looks much better now. Only one missing from trakt - progress - episodes. Both main menu and osd.

**Comment by ivarbrandt** [comment]
> Looks much better now.

How? I haven't pushed an update.

**Comment by derrgoo** [comment]
Sorry! typo lol I meant to say that it is great you found it and will push an update.

**Comment by derrgoo** [comment]
Thank you!!! All showing now. 👏
