### ISSUE TITLE
Trailer messes up widgets IF one widget item is empty

### ISSUE THREAD

**Issue by 2Bnier** [ivarbrandt/skin.nimbus#108]
First of all, many thanks for this awesome skin.

**_Issue One_**: Title says the issue

I tested the trailers beforehand and everything works fine... until I set up all of my widgets.
Tried to reproduce for couple of minutes and found out that an empty widget item was causing the messed up widget UI.

https://drive.google.com/file/d/1x_sP2a70tZdt5ydEJZdB_wmd6_10vroH/view?usp=drive_link

Happens on both trailer modes (One click and auto)
Note that when the screen dims, the trailer is already playing... the screen recorder didnt grab it.
Also, I think I could also call this as **_Issue Two_** - because in the showcase video, the screen doesn't dim while the trailer is playing.

All widgets are messed up if they are below the empty widget (widget 2, Continue Watching [In Progress in Fen Lite]). The widgets above it (widget 1 in the video) works with no issues.

**Comment by ivarbrandt** [comment]
Correct, haven't found a fix for this.

I just put all empty widgets at the the bottom so they don't mess up the widget positioning during trailers.
