### ISSUE TITLE
This is cool

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#109]
https://forum.kodi.tv/showthread.php?tid=371037

![image](https://github.com/user-attachments/assets/43f8dbe7-87ee-4388-ae18-8ef96ac6b96d)

I didn't create a single widget. It uses TMDBhelper to find the trakt account I believe, and then it loads the widgets for basically all menus in trakt, MOVIES, TV SHOWS

I believe it's doing API calls itself, each time I go to a new section it will load those widgets so it's barely any delay to load lots of widgets.

It then relies on TMDBhelper that relies on addons to get you the source.
Since it's API's it's crazy. It's basically an addon+slin combined, each section that is inside an addon is inside the homescreen widgets

https://streamable.com/trxexh

the tech is cool, thoughts?

**Comment by ivarbrandt** [comment]
Ask what you really want to ask.

**Comment by derrgoo** [comment]
What nimbus offers is way nicer in my opinion and being able to make your own widgets is what a custom build is. If you want this just go download a made build which dozens out there.

**Comment by hcgiub001** [comment]
I kind of got carried away lol
This skin I believe needs TMDBhelper, it gets your trakt information from TMDBhelper then it loads your data from trakt, like your movies, tv shows, your calendars. and all stuff like popular movies, trending etc. You don't have to create your own widget for this.
each section you access loads the widget for that section, it directly gets the information from API's I think which is why it's faster than normal widgets that have to communicate with addons. I liked the idea. but yeah In Nimbus we can load our own widgets like this. I'm closing the issue , not sure what I wanted out of this.
