### ISSUE TITLE
OSD doesn’t go away if playback speed is changed. 

### ISSUE THREAD

**Issue by mcmcc1** [ivarbrandt/skin.nimbus#11]
I raise the playback speed to 1.2 and the OSD will not go away.

**Comment by ivarbrandt** [comment]
I don't have anywhere in the OSD where you can change the playback speed. Can you provide some screenshots so I have a better understanding of what you're talking about?

**Comment by mcmcc1** [comment]
If you turn on sync playback to display under video settings, the option appears to change playback speed in the OSD.

**Comment by ivarbrandt** [comment]
Fixed. Changes are in `0.1.10`.
