### ISSUE TITLE
Information- Cast

### ISSUE THREAD

**Issue by derrgoo** [ivarbrandt/skin.nimbus#110]
![image](https://github.com/user-attachments/assets/a1cf2312-e04b-43f3-a1b2-bfa6253a0ce6)

![image](https://github.com/user-attachments/assets/ff5c8b01-36fc-4787-a683-1a817e62bb3c)

I have been wondering if there is a way to connect this with TMD helper or another database. Maybe I have not found the settings to turn this part on. It searches on the actor but always comes up empty. Is there a way to see more results? Thank you.

**Comment by ivarbrandt** [comment]
Click right instead of select.

**Comment by derrgoo** [comment]
Lol finally! Thanks
