### ISSUE TITLE
can we get the path url of custom widgets?

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#111]
Hey Ivar
Hope you could help me here,
is their a way I can get the path to a specific custom widget (out of the 4 we can have)
so I can map this
like we have for shutdownmenu  ActivateWindow(ShutdownMenu)
normally I add things to favourites.xml to see what the path is, but I can't with the widgets (That I know of). Just need to add this to finish that thing I'm working and would be awesome if I can get those paths.
thanks for any help you can offer and to hear me out.

EDIT: if possible having both the main widget that we have on the side bar, like fenlight and then we have the widgets for that main one like blockbuster , trendinding etc

if I can get a path to both them, then that would be awesome! :D

**Comment by ivarbrandt** [comment]
You can find the paths for each main menu item in separate xmls:

`script-nimbus-main_menu_movies.xml`
`script-nimbus-main_menu_tvshows.xml`

You can find the paths in the `onclick` tag.

The widgets can be found in separate xmls as well:

`script-nimbus-widget_movies.xml` contains the movie widgets
`script-nimbus-widget_tvshows.xml` contains the tvshow widgets

In there you'll find the path in the `content_path` param of each widget.

**Comment by hcgiub001** [comment]
Oh I see, the onclick just takes you to the addon
      <onclick>ActivateWindow(Videos,plugin://plugin.video.fen,return)</onclick>

I could get this by adding to favourites, was thinking I could have a path that goes to the homepage on widget section and say my widget was in Fenlight custom 

![image](https://github.com/user-attachments/assets/b5e2faab-31d1-4ad4-97e7-235ef9debbc6)

and I had 10 widgets inside it, that I could get a path to say 5th in the list
so if I mapped my key to it, it will stay in homepage in the widget section. but that doesn't seem like it's possible?

**Comment by ivarbrandt** [comment]
You want to map a key to take you to the 5th widget in a specific section?

**Comment by hcgiub001** [comment]
yes, I want to be able to get to any section I want, and even better I want a map to get me to the specific section itself

so if I have all 4 sections filled, I'd like to be able to map them
and in each if I have 20 widgets, I want to map them to
is this possible without you having to alter anything? if not it's okay, just wanted to know if their is a quick way to find out

**Comment by ivarbrandt** [comment]
I don't know if it's possible.

**Comment by hcgiub001** [comment]
was a long shot, thanks
