### ISSUE TITLE
[BUG] information duplicated on Dramacool

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#112]
Hey Ivar
![image](https://github.com/user-attachments/assets/71fc0f53-dcba-4815-b7cf-9359a4404e94)

you pretty much fixed everything on dramcool, thanks! just when we do a search the information is messed up. I wasn't going to bring it up, I can live with it but someone else had an issue on reddit that I asked them to report here

> Hi guys so I installed nimbus with the hopes of being able to use the formerly known  
> flixify (now known as raptus.site) service with the add on and it’s working amazingly but > for some reason in movies it shows the information twice. I attached a picture for 
> reference and tv shows it shows just fine. Does anyone have any idea how I can fix this? I > don’t know if maybe it’s using another provider to fetch info and that’s why it’s doing 
> that? I don’t have an IMBD api key in either so I’m just confused why it’s populating 
> twice . Thank you so much and also if anyone has an idea how to change the theme
>  colors that would be awesome also.

![image](https://github.com/user-attachments/assets/115e7b59-646c-41e1-978d-85438eedd5fa)

https://www.reddit.com/r/Addons4Kodi/comments/1foi205/nimbus_wflixify_information_duplicated/

thanks for taking a look if you have time

**Comment by ivarbrandt** [comment]
Fixed Dramacool for next update. In order to fix the flixify addon I would need the exact name of the addon as it shows up in the addons directory.

**Comment by hcgiub001** [comment]
I'll find out from that person and thankyou!

**Comment by jokerkiller36** [comment]
Hi Ivan thank you so much for being willing to fix it. I've provided the instruction I used to install the add on I hope it helps. 

The Add-on registers its repository during installation and after installation the plug-in will be automatically updated from this repository
Install the Add-on:
Download the latest version of the plugin flixify.com-2.1.17.zip (or use short permalink to latest versions: https://raptus.site/kodi/last.zip )
At XBMC/KODI open Add-ons -> Add-on Browser -> Install from zip file
 See the step-by-step instructions 
If you see the "DISABLED" alert, change the settings to allow plugin installation
 See the step-by-step instructions 
Select the downloaded the Add-on zip file
 See the step-by-step instructions 
At the Main menu XBMC/Kodi select Add-ons -> The Site
 See the step-by-step instructions 
You will see a PIN code on the screen for activation the device and you need to enter it on the PIN login page at your browser from a PC or mobile
 See the step-by-step instructions 
Wait a few seconds after PIN login for the device to be authorized.
Enjoy!

**Comment by hcgiub001** [comment]
> Hi Ivan thank you so much for being willing to fix it. I've provided the instruction I used to install the add on I hope it helps.
> 
> The Add-on registers its repository during installation and after installation the plug-in will be automatically updated from this repository Install the Add-on: Download the latest version of the plugin flixify.com-2.1.17.zip (or use short permalink to latest versions: https://raptus.site/kodi/last.zip ) At XBMC/KODI open Add-ons -> Add-on Browser -> Install from zip file See the step-by-step instructions If you see the "DISABLED" alert, change the settings to allow plugin installation See the step-by-step instructions Select the downloaded the Add-on zip file See the step-by-step instructions At the Main menu XBMC/Kodi select Add-ons -> The Site See the step-by-step instructions You will see a PIN code on the screen for activation the device and you need to enter it on the PIN login page at your browser from a PC or mobile See the step-by-step instructions Wait a few seconds after PIN login for the device to be authorized. Enjoy!

It was a simple request to ask for the name of the addon, when you install an addon it has a name, if you can't provide that when asked , you really expect to install something then do some authorisation just to find out what it's called? if you asked for my name and I said , go to this address and knock on the door 3 times once someone give you a password, you can enter the house and you'll find his name, how would you respond?
why are you using an addon that is so obscure ? I don't speak for [ivarbrandt](https://github.com/ivarbrandt) but he's being kind to share his work, but doesn't have unlimited time to do the work for you. What is the addon called so we can at least do some research.

**Comment by jokerkiller36** [comment]
It's called flixify. I wasn't sure what was being asked explicitly if the add on install link was required or not to do further analysis on what the potential issue may be. You're correct you don't speak for the dev so let him reply with what he prefers. 

Dev I attached a picture of the add on name as well. Thank you. ![image](https://github.com/user-attachments/assets/8d07171e-1653-45c8-b33f-30913f8375ae)

**Comment by jokerkiller36** [comment]
> > Hi Ivan thank you so much for being willing to fix it. I've provided the instruction I used to install the add on I hope it helps.
> 
> > 
> 
> > The Add-on registers its repository during installation and after installation the plug-in will be automatically updated from this repository Install the Add-on: Download the latest version of the plugin flixify.com-2.1.17.zip (or use short permalink to latest versions: https://raptus.site/kodi/last.zip ) At XBMC/KODI open Add-ons -> Add-on Browser -> Install from zip file See the step-by-step instructions If you see the "DISABLED" alert, change the settings to allow plugin installation See the step-by-step instructions Select the downloaded the Add-on zip file See the step-by-step instructions At the Main menu XBMC/Kodi select Add-ons -> The Site See the step-by-step instructions You will see a PIN code on the screen for activation the device and you need to enter it on the PIN login page at your browser from a PC or mobile See the step-by-step instructions Wait a few seconds after PIN login for the device to be authorized. Enjoy!
> 
> 
> 
> It was a simple request to ask for the name of the addon, when you install an addon it has a name, if you can't provide that when asked , you really expect to install something then do some authorisation just to find out what it's called? if you asked for my name and I said , go to this address and knock on the door 3 times once someone give you a password, you can enter the house and you'll find his name, how would you respond?
> 
> why are you using an addon that is so obscure ? I don't speak for [ivarbrandt](https://github.com/ivarbrandt) but he's being kind to share his work, but doesn't have unlimited time to do the work for you. What is the addon called so we can at least do some research.

As I've stated on Reddit it's because it’s not just publicly available it’s through flixify an invite only site but they have a add on for kodi so you can stream through a tv or something instead of just mobile devices or anything that requires browser access it’s just way nicer to use UI wise instead of a browser when on a tv. The domain is raptus.site but you can’t sign up without being invited I commented back on the issue to see if the dev is able to do it . I don’t want to use a community plugin because everything is on this in relation to media and I don’t have to worry about finding good links etc everything is just one click high quality and shows come out before they do on streaming services so I just like using it. If it can’t be fixed then it can’t but obviously I’m going to ask if it can be . I found being in list view it shows all info properly but I like to see the thumbnails without being on the actual title itself. I don't think it should matter to you if I'm using a superior service to what's publicly available to anyone.

**Comment by ivarbrandt** [comment]
I've installed the addon. I see Flixify in my addons and when I click it, it gives me a PIN code to enter in a browser.

Because the addon is invite only, I won't be able to test the fix directly. The only thing I need to know, is the addon that I installed from the zip, Flixify, the addon that you stream directly from?

**Comment by jokerkiller36** [comment]
> I've installed the addon. I see Flixify in my addons and when I click it, it gives me a PIN code to enter in a browser.
> 
> 
> 
> Because the addon is invite only, I won't be able to test the fix directly. The only thing I need to know, is the addon that I installed from the zip, Flixify, the addon that you stream directly from? Or is there another addon that is installed but can only be accessed through the invite?

Correct, the streaming occurs straight from the add-on. I have setup the paths in nimbus to reference the movies/shows etc. if you would like if we can establish comms offsite I am willing to activate your pin on my account and as soon as invites are allowed again I can invite you if you like it! I also know this must be something im the only one dealing with this so I'm willing to donate a tip to you for your time regarding this issue :)

**Comment by ivarbrandt** [comment]
Sure thing. I'll send you a message in the Reddit chat.

**Comment by ivarbrandt** [comment]
Update is up.

**Comment by jokerkiller36** [comment]
Wow!! ![image](https://github.com/user-attachments/assets/807e459a-9de3-45ba-9db2-7c1dff8f9400) you're the best man thank you so much . This is exactly what I've been looking for

**Comment by hcgiub001** [comment]
> Update is up.
just checked and works awesome now! you don't some great work on widgets too! great update thankyou!
