### ISSUE TITLE
addons show release version

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#113]
Hey Ivar, hope you're well. 
New update is cool! but I've noticed this
![image](https://github.com/user-attachments/assets/0bd3b10a-c7c0-4cb4-b6f7-c7638f07c9ce)
the release version label makes it more cluttered?

**Comment by donutmiddles** [comment]
Far from being "more cluttered," that makes use of what would otherwise be more empty space between the widgets. Now it contains useful information that saves one having to navigate into the Add-ons section for more details. This is very helpful, keep it.

**Comment by hcgiub001** [comment]
> Far from being "more cluttered," that makes use of what would otherwise be more empty space between the widgets. Now it contains useful information that saves one having to navigate into the Add-ons section for more details. This is very helpful, keep it.

when will you find this useful information? do you have a photographic memory so you can recall what was the last release version so you can know if it's been updated? I'm having a hard to understanding why would need to know at all times what the release version is. Nimbus philosophy is always been aesthetics. It might be useful for you to know at all times what the release version is, even though you have no idea when the new version was updated, but it's definitely goes against Nimbus philosophy. Heck no other skin shows this. Please explain how knowing the release version is useful to you and how often you need to know what the release version is to justify having it plastered on main menu?

**Comment by hcgiub001** [comment]
In fact which OS (android / IOS) has release version as part of the name for it's apps? I'm pretty sure this is an oversight, a bug as you will, which is why I reported it.
and do you know all you have to do is long press the addon and click information for the release number and everything else? not exactly "having to navigate"

**Comment by ivarbrandt** [comment]
It's not a bug. I added it on purpose and it's staying.
