### ISSUE TITLE
IDEAS on widget settings 

### ISSUE THREAD

**Issue by Launcher2020** [ivarbrandt/skin.nimbus#116]
Going to settings where the 
Widget option 
choose landscape sub label
There's options that are 
Tagline, director, full genre ,and studio
is there any way for the developer can add a non option Also for the people who don't want all those options under the landscape sub label
If it's possible thank you....

P.S. I just found out about this skin and you did amazing thank but can you add just this one thing that's all please and thank you once again ,😊🤞

**Comment by ivarbrandt** [comment]
Are you sure you want this option? It looks a bit strange having a bigger space between widgets

![Screenshot_20241010-125115](https://github.com/user-attachments/assets/25b2739c-0e58-4b10-a759-d993ed1c47ff)

**Comment by Launcher2020** [comment]
Thank you for replying back yes if you can and that's why there other options for other people to pick from if you can please add it that will be amazing and thank you

**Comment by Launcher2020** [comment]
Hey it's me again 😊 this is what I'm talking about right here if you can add this option and have it look like this 
![Picsart_24-10-10_16-47-45-972](https://github.com/user-attachments/assets/446b33e1-0f17-44eb-9167-f738f6731910)

**Comment by ivarbrandt** [comment]
That giant space just bothers me lol. I'll make it optional though.

**Comment by Launcher2020** [comment]
Thank you so much 🙏😊🙏😊 Bless you man..

**Comment by Launcher2020** [comment]
How do does that work do I have to reinstall the skin again or wait for the update and it will automatic do it ..

**Comment by ivarbrandt** [comment]
Done for next update.

> How does that work getting the update on the widget option

It will auto update if you have auto update enabled, otherwise you'll get a notification pop up.

**Comment by Launcher2020** [comment]
Awesome 👍 thank you ..i really appreciate it hey do you have a PayPal account so I can buy you a drink 🍻 lol for adding this to your project and taking you time to do so ...

**Comment by ivarbrandt** [comment]
I appreciate the gesture but don't worry about it.

**Comment by Launcher2020** [comment]
Okay thank you again 😊🙏 keep up the amazing jod on the skin Nimbus we all appreciate it thank you....
