### ISSUE TITLE
poster widgets not showing titles of show/movies

### ISSUE THREAD

**Issue by dabutch3r** [ivarbrandt/skin.nimbus#118]
I have found if I use Fen for widgets I have no issues with poster view. I see the title, meta data and other info. But when I use some other addons ( for 1 click ) as widgets the poster view does not have the show/movie title when highlighted. I know those addons dont have meta data added in details so thats not a issue. Can you add the show/movie title above ot below the poster art? When I use Square view title is added but square cuts off too much of the image imo. 

![screenshot00002](https://github.com/user-attachments/assets/646a3640-2f18-4fe5-b255-4c135a4bd460)
Here is an example of poster of a 1 click addon.

![screenshot00005](https://github.com/user-attachments/assets/667da24c-7109-4d7e-8548-03d39ebc11c8)
Here is an example of same addon with square view

Thank you

**Comment by ivarbrandt** [comment]
I don't want to add that in. In Skin settings > Widgets options, make sure Show item title in InfoLine is toggled on that way you can see the title of the item when it is focused.

**Comment by dabutch3r** [comment]
I toggled it and still no Title in INFOLINE. must be the format that some addons use for their xml's in the addons.

**Comment by ivarbrandt** [comment]
Strange. Which addon are you using?

**Comment by dabutch3r** [comment]
Black Lightning,,, One of the better 1 click tv and movie addons

**Comment by ivarbrandt** [comment]
I'll check it out and get back to you.

**Comment by derrgoo** [comment]
BL do not have the proper code to pick up most any of the skins. Especially 1 click section don't think he can do anything about it.

**Comment by ivarbrandt** [comment]
Fixed for next update.

**Comment by dabutch3r** [comment]
Thank you
