### ISSUE TITLE
Where can I edit to pull background art from a URL

### ISSUE THREAD

**Issue by dabutch3r** [ivarbrandt/skin.nimbus#119]
I'm looking to edit the skin to make it by default to look at a folder I have online. My background folder has several folders with backgrounds inside them.  I would like to browse that folder through the skin settings. 
I tried to edit the userdata skin settings xml but all url formats failed to work. 
Thanks for your help

**Comment by ivarbrandt** [comment]
No idea. There was someone that figured out how to do this with FENtastic awhile back so it is possible. You could post in Reddit and see if anyone knows.

**Comment by dabutch3r** [comment]
LOL, That was me that solved it on Fentastic skin. The xmls on Nimbus didnt look the same as Fentastic and the places I made the edits on the other skin. I will look back at my Fentastic build and walk back through the steps to see if I can make same edits to Nimbus.

**Comment by ivarbrandt** [comment]
LOL that's funny. I now recognize your username.

If you're still having trouble, let me know what you changed in FENtastic and I'll point you to the similar code in Nimbus.

**Comment by dabutch3r** [comment]
Found it.. I was looking in the skin folder but I had made the edits to Userdata in Fen skin. So I made same changes to Nimbus userdata/settings and got it to work. I see there is 2 entries Nimbuscustombackground and Lastimagepath. I will mess with these lines.

Line 153<setting id="nimbuscustombackground" type="string">URL_To_My_BG_folder_image.jpeg</setting>

Thank you for the sweet skins to mess with.

**Comment by dabutch3r** [comment]
Here is my settings file
[settings.zip](https://github.com/user-attachments/files/17357027/settings.zip)

**Comment by ivarbrandt** [comment]
Nice. Glad you were able to sort it out. Does that let you access a bunch of backgrounds?

**Comment by dabutch3r** [comment]
I can access any image on my server. I have well over 150 backgrounds there. It will open the image I set as default but if I click image path in skin settings it shows all images in that folder. If I want to access other folder I hit .. to go back a folder. From there I can see all my other BG folders.  So this will work for me and my small build.

**Comment by dabutch3r** [comment]
Well over 150 with no space used in addon,  plus I can add more within seconds.

**Comment by ivarbrandt** [comment]
That's awesome. I might have to do something like that for Nimbus.

**Comment by dabutch3r** [comment]
The userdata/settings xml shows the path I used. I looked to make the edit of background path in home, includes and settings xml in skin folder but couldn't find the right syntactic to use.

**Comment by ivarbrandt** [comment]
In `Variables_Artwork.xml`, there's a variable called `NimbusCustomBackgroundImage`. Edit the second value that contains the` special://` path to have it point to your online folder by default.

I'm not sure if this will allow you to choose which image to use though.

**Comment by dabutch3r** [comment]
Awesome
 I will give it a try sunday

**Comment by dabutch3r** [comment]
Tested the new update. making edits to Variables_artwork did the trick. It does allow me to view and set and backgrounds in my online folders of backgrounds. Thank you again for this info and The poster name fix.

**Comment by ivarbrandt** [comment]
> It does allow me to view and set and backgrounds in my online folders of backgrounds.

That is pretty cool. You're welcome :)
