### ISSUE TITLE
OSD background 

### ISSUE THREAD

**Issue by Guguloi** [ivarbrandt/skin.nimbus#12]
First of all a BIG THANK YOU for this skin, it's all I dreamt: simple, blazing fast and great looking.

Second, is not a request is just an observation. Black background on OSD controls. When I want to adjust offset for subtitles I can't see subtitles. Maybe a transparent layer instead that black background?

Anyway no biggie if not because I need offset correction very rare.

Have a nice life.

**Comment by derrgoo** [comment]
Maybe we can help. I have looked for which xml it is and couldn't spot it. Any help and all try to play with it.

**Comment by TwilightMercy** [comment]
> Maybe we can help. I have looked for which xml it is and couldn't spot it. Any help and all try to play with it. 

VideoOSD.xml
