### ISSUE TITLE
FEN Lite Anime search

### ISSUE THREAD

**Issue by Better-Red** [ivarbrandt/skin.nimbus#120]
Hi, thank you for both FENtastic and Nimbus, they're my go to skins on my box, mostly playing with Nimbus now. Is there anyway that FEN Lite Anime could be added to the search in Nimbus? I would ask about FENtastic as well, but I don't think you're taking feature requests. Many thanks.

**Comment by ivarbrandt** [comment]
This is a path that needs to be added and provided by the FEN Lite dev, Tikipeter. Only then can I add it in to Nimbus.

**Comment by Better-Red** [comment]
If I'm being thick, please feel free to say so! :)

![screenshot00000](https://github.com/user-attachments/assets/aa34adf2-222f-4698-a27c-6dd389ed101d)

**Comment by hcgiub001** [comment]
> If I'm being thick, please feel free to say so! :)
> 
> ![screenshot00000](https://private-user-images.githubusercontent.com/46077626/377028933-aa34adf2-222f-4698-a27c-6dd389ed101d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMjkwOTcsIm5iZiI6MTcyOTEyODc5NywicGF0aCI6Ii80NjA3NzYyNi8zNzcwMjg5MzMtYWEzNGFkZjItMjIyZi00Njk4LWEyN2MtNmRkMzg5ZWQxMDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAxMzMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYzVlNDI0ZjQ3OWU0NjdlZmE1NzhjYjJhNTA3YjA2MjY4MTI3ZjczNTRiZDQyYjI2ZGQ0YTdmMTdlMmViMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-928SK83mdS7l6eRRzJot0ctD3y4qNsSrcq5T5LkIe8)

When you search in anime (in Fen Light) it looks at the code to have a look at what it needs to do. Other addons can't use it because it's not designed that other people need to use the search outside the addon. Fen Light has to write it in code for a "path" so other developers can use this path to search outside Fen Light. You'll have to make an issue here
https://github.com/Tikipeter/tikipeter.github.io/issues
kindly asking the developer to have a path so skins can make use of Anime Search like he's provided for paths for other searches.

**Comment by Better-Red** [comment]
Understood, thank you. I've opened an issue on Tikipeter's GitHub.

**Comment by Better-Red** [comment]
From Tikipeter:

This should work fine. No need to create any path.

plugin://plugin.video.fenlight/?mode=build_tvshow_list&amp;action=tmdb_anime_search&amp;query=$INFO[Skin.String(SearchInputEncoded)]

I did try implementing this myself, but I'm missing something, probably missing several somethings!

**Comment by ivarbrandt** [comment]
> I did try implementing this myself, but I'm missing something, probably missing several somethings!

All good. I like that you tried. 

I've finished adding this in to Nimbus. It will be available in the next update.

**Comment by Better-Red** [comment]
> > I did try implementing this myself, but I'm missing something, probably missing several somethings!
> 
> All good. I like that you tried.
> 
> I've finished adding this in to Nimbus. It will be available in the next update.

That's great, thank you. I will try again and see if I can add it to FENtastic, unless you can give me some pointers?

**Comment by ivarbrandt** [comment]
Add this widget to group 27001 in `Custom_1121_SearchResults.xml`:

```
<include content="WidgetListPoster" condition="!Skin.HasSetting(HideAnimeResults) + String.IsEqual(Skin.String(current_search_provider),1)">
        <param name="content_path" value="plugin://plugin.video.fenlight/?mode=build_tvshow_list&amp;action=tmdb_anime_search&amp;query=$INFO[Skin.String(SearchInputEncoded)]"/>
        <param name="widget_header" value="Anime"/>
        <param name="widget_target" value="videos"/>
        <param name="list_id" value="27013"/>
</include>
```

Then add this button to grouplist 647 in `SkinSettings.xml`:

```
<control type="radiobutton" id="64705">
	<label>   - Anime</label>
	<include>DefaultSettingButton</include>
	<onclick>Skin.ToggleSetting(HideAnimeResults)</onclick>
	<selected>!Skin.HasSetting(HideAnimeResults)</selected>
	<visible>!Skin.HasSetting(NoSearchResultsWindow) + String.IsEqual(Skin.String(current_search_provider),1)</visible>
</control>
```

Since we added the new widget and new button, make sure that the list_ids of the widgets get updated. So since we added in 27013, the previous 27013 widget becomes 27014 and so on. Same with the ids for the button grouplist.

**Comment by Better-Red** [comment]
Thank you again, that works. So I don't break anything else, should I bump the values here?

```
<control type="radiobutton" id="64705">
	<label>   - Anime</label>
	<include>DefaultSettingButton</include>
	<onclick>Skin.ToggleSetting(HideAnimeResults)</onclick>
	<selected>!Skin.HasSetting(HideAnimeResults)</selected>
	<visible>!Skin.HasSetting(NoSearchResultsWindow) + String.IsEqual(Skin.String(current_search_provider),1)</visible>
</control>
/
```

**Comment by Better-Red** [comment]
Thank you again, that works. So I don't break anything else, should I bump the values to match here?

```
<include content="WidgetListCategoryStacked" condition="!Skin.HasSetting(HideTraktResults) + [String.IsEqual(Skin.String(current_search_provider),0) | String.IsEqual(Skin.String(current_search_provider),1) | String.IsEqual(Skin.String(current_search_provider),3)]">
							<param name="content_path" value="$VAR[SearchProviderTRAKTListsVar]"/>
							<param name="widget_header" value="TRAKT Lists"/>
							<param name="widget_target" value="videos"/>
							<param name="list_id" value="27017"/>
						</include>
						<include content="WidgetListBigPosterStacked" condition="!Skin.HasSetting(HideTraktResults) + [String.IsEqual(Skin.String(current_search_provider),0) | String.IsEqual(Skin.String(current_search_provider),1) | String.IsEqual(Skin.String(current_search_provider),3)]">
							<param name="content_path" value="$INFO[Window(1121).Property(fentastic.27017.path)]"/>
							<param name="widget_header" value="$INFO[Window(1121).Property(fentastic.27017.label)]"/>
							<param name="widget_target" value="videos"/>
							<param name="list_id" value="270171"/>
						</include>
						<include content="WidgetListCategoryStacked" condition="!Skin.HasSetting(HideTraktResults) + String.IsEqual(Skin.String(current_search_provider),2)">
							<param name="content_path" value="plugin://plugin.video.umbrella/?action=trakt_search_lists&amp;media_type=movies&amp;name=$INFO[Skin.String(SearchInputTraktEncoded)]"/>
							<param name="widget_header" value="TRAKT Lists (Movies)"/>
							<param name="widget_target" value="videos"/>
							<param name="list_id" value="27018"/>
						</include>
						<include content="WidgetListBigPosterStacked" condition="!Skin.HasSetting(HideTraktResults) + String.IsEqual(Skin.String(current_search_provider),2)">
							<param name="content_path" value="$INFO[Window(1121).Property(fentastic.27018.path)]"/>
							<param name="widget_header" value="$INFO[Window(1121).Property(fentastic.27018.label)]"/>
							<param name="widget_target" value="videos"/>
							<param name="list_id" value="270181"/>
						</include>
						<include content="WidgetListCategoryStacked" condition="!Skin.HasSetting(HideTraktResults) + String.IsEqual(Skin.String(current_search_provider),2)">
							<param name="content_path" value="plugin://plugin.video.umbrella/?action=trakt_search_lists&amp;media_type=tvshows&amp;name=$INFO[Skin.String(SearchInputTraktEncoded)]"/>
							<param name="widget_header" value="TRAKT Lists (TV Shows)"/>
							<param name="widget_target" value="videos"/>
							<param name="list_id" value="27019"/>
						</include>
						<include content="WidgetListBigPosterStacked" condition="!Skin.HasSetting(HideTraktResults) + String.IsEqual(Skin.String(current_search_provider),2)">
							<param name="content_path" value="$INFO[Window(1121).Property(fentastic.27019.path)]"/>
							<param name="widget_header" value="$INFO[Window(1121).Property(fentastic.27019.label)]"/>
							<param name="widget_target" value="videos"/>
							<param name="list_id" value="270191"/>
						</include>
```

**Comment by ivarbrandt** [comment]
Correct. Make sure you update the content path and widget header too for the stacked display widget eg. WidgetListBigPosterStacked
