### ISSUE TITLE
Make viewtypes independent/unique per widget/source

### ISSUE THREAD

**Issue by Dakotah-Engel** [ivarbrandt/skin.nimbus#121]
I like using poster flow view when using my genres widget but I like grid view when viewing my collection. Would be nice to have views saved differently based on widget/source of the view

**Comment by ivarbrandt** [comment]
Widgets refer to the home screen. Views refer to viewing content within an addon in the video windows.

Knowing that, rephrase your question.

**Comment by Dakotah-Engel** [comment]
Gonna close this. I meant I want each section within fen lite to have whatever view I set it to. For example, movies -> trending to be in flix view and movies -> popular to be in posterflow. Right now when you set a view type, it's the same for everything within the addon. Realizing now having every single one be unique is probably wildly impractical for memory reasons

**Comment by ivarbrandt** [comment]
Nimbus can save different viewtypes for different content types (movies, tvshows, seasons, episodes, and episode lists).

What you're asking for though is near impossible. Solid coding project though if you wanna take on it yourself.
