### ISSUE TITLE
Progress Indicator Refresh

### ISSUE THREAD

**Issue by hufflepuffhavoc** [ivarbrandt/skin.nimbus#122]
Not sure if this is a skin related thing but when using fen light next episodes through favorites the **progress indicator** doesnt refresh unless the episode ends or i back out and back to the next episodes (works the same with movies and with widgets this is not an issue but i just prefer using it without it).

**Comment by ivarbrandt** [comment]
This isn't skin related. Nimbus shows the progress indicators according to the data it needs available. Updating progress is performed by the addon you're using.

**Comment by npmstart-pray** [comment]
I've been having issues for a while with trakt not marking tv episodes I watch as "watched."  I can still manually mark them from the context menu. I haven't tried a sync, but I'll report back if it solves the issue.
