### ISSUE TITLE
Default OSD Dynamic Title

### ISSUE THREAD

**Issue by hufflepuffhavoc** [ivarbrandt/skin.nimbus#123]
Feature request: I prefer the default layout of the OSD i think it looks great but would like having the customization option similar to the modular layout as I personally prefer to have the title always on display instead of it dynamically changing to video and audio codecs. Plus it would be nice if it showed the episode title too. 

Really appreciate the work you have done on nimbus. It has been a joy to use it.

**Comment by ivarbrandt** [comment]
Not too sure on this one. The default OSD layout is the one I use, the modular was for everyone else that didn't like it.

Let me think about it.

**Comment by ivarbrandt** [comment]
I don't entirely know if I can make the label not be dynamic the way it's currently coded. That being said, I will see if I can figure something out. I'll also add in the episode title as well.

**Comment by ivarbrandt** [comment]
Finished for next update.
