### ISSUE TITLE
[Minor Request] option for locking Media Views based on individual add-ons instead of universal

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.nimbus#124]
Is it possible to implement an option so you can choose your preferred media view individually depending on the addon. For example, I use FenLight and Otaku and sadly if I change a media views in Otaku since the posters aren't really good in that Addon. Changing the media view to let's say Landscape for artworks will also affect and change it in FenLight add-on where I might want to keep the artwork as posters for shows and movies. So, it would be nice to be able to change media views and lock them addon to addon instead of universal as it currently is. Other skins I've used in the past has had this method of media view selection which is addon by addon. That way we can have different styles for different addons.

**Comment by ivarbrandt** [comment]
I tried to implement exactly this quite a few times and I haven't been able to figure it out.
