### ISSUE TITLE
Jellycon search support

### ISSUE THREAD

**Issue by vimcc** [ivarbrandt/skin.nimbus#125]
Currently, it looks like the given search providers give external results. Is it possible to only configure this to search through the jellycon add-on instead? 

At the moment the only way of searching through jellycon is directly through a path (e.g; all movies), using the filter options or the search button once you're already in the jellycon path.

**Comment by ivarbrandt** [comment]
It is possible but I'm not going to implement it.

If you are interested in tackling this yourself see the `Custom_1121_SearchResults.xml` file. Inside of that you'll find widgets that are used to display search results. In the content_path param of each of those you can remove the variable and enter in the paths for jellycon results instead.
