### ISSUE TITLE
Ratings not Displaying in FENtastic Home Page and MDbList API Invalid Error in Nimbus

### ISSUE THREAD

**Issue by KweenMother** [ivarbrandt/skin.nimbus#126]
I've been searching non-stop the past 24 hours and cannot find the reason as to why FENtastic stopped displaying ratings.

- Setup: Xbox Series S, and Windows 10 Laptop
- Kodi 21.1
- FENtastic 1.0.25
- Fen Light 1.0.84 & 1.0.89
- Nimbus Helper Installed: 0.0.46
- FENtastic Helper Installed: 0.6.20a 
- Current Kodi Log: https://paste.kodi.tv/esoqosapek
- 
- Cleared Ratings Cache & Restarted Kodi (Multiple times)
- Cleared and Re-entered MDbList API Keys (Copy & Paste)
- Created a new MDbList API Key and entered it (Copy & Paste)
- Cleared All Cache Including Favorites (Multiple times)
- Multiple times...
- Checked for Corrupt Databases
- Clean Databases
- Remake Settings Cache
- Clear All Cache (Excluding Favorites)
- Current Kodi Log: https://paste.kodi.tv/imehejigoz
- RATINGS WILL DISPLAY IN EXTRAS SCREEN but not on the Home Screen (Metacritic, RT Critic & Audience, IMDB, TMDB) 

I've had this setup going on 6 months and haven't made any changes to it other than FENtastic and Fen Light updates. I have my OMDB & MDBlist API Keys entered correctly in the skin and Fen Light. I've uninstalled, and reinstalled multiple times, I've cleared the Ratings Cache and Restarted Kodi multiple times before trying to scroll through. I've checked all Dependencies for both FENtastic and Nimbus and they are all met or exceeded.  

I loaded Nimbus skin and directly copied and pasted from the MDbList site into the skin.  I received an error "Invalid API Key".  I created a new MDbList API Key and directly copied and pasted into the Nimbus skin and received the same error.  

I'm not sure what else I can do, any help would be appreciated. 

![No Ratings FENtastic](https://github.com/user-attachments/assets/ed9c8d91-77a4-455b-833a-2e047e9f1f58)
![MDblist API Key Blackedout](https://github.com/user-attachments/assets/67720ea0-1895-43da-8b13-1d05f5bcbba2)
![TMDB   OMDB API Keys Blackedout](https://github.com/user-attachments/assets/f2c0cee5-9bdb-455d-8d65-7386ebc51e53)
![Invalid API Key Nimbus](https://github.com/user-attachments/assets/0da79534-bcd8-40e9-811e-acaeb2e703bf)

**Comment by ivarbrandt** [comment]
A few things you can check:

1. Are the widgets from TMDbHelper? If they are try using Fen Light widgets directly.
2. Do you have auto updates enabled for addons? If you do, check what was most recently updated in that last 24 hours. Maybe there was another addon that was updated that is causing a conflict.
3. If none of the above fixes it then you can try deleting the settings.xml file in userdata/addon_data/skin.nimbus. It's possible that one of the skin strings got corrupted. This will reset all the skin settings back to default including all of the strings associated with displaying the ratings.

Let me know how it goes. The fact that ratings are not working in either skin possibly points to an issue outside of the skins. We won't know for sure though till we dig further into it.

**Comment by KweenMother** [comment]
Hello Ivarbrandt!

Thank you for taking the time for this!  Thank you.  

- The widgets are from Fen Light directly.
- 1 Available Update: ResolveURL gujal 5.1.150.  I haven't updated it because I'm not sure if it would rollback the YouTube plugin from Anxdpanic.  Nothing about Recently Updated. 
- skin.nimbus was not found in the userdata/addon_data/
![No Nimbus or FENtastic Skin Found](https://github.com/user-attachments/assets/c232ccf1-6a84-451a-97cf-3232b843c6d4)
![Available Update ResolveURL Kodi](https://github.com/user-attachments/assets/68d95e53-86e2-4a0a-8899-bec484818216)

**Comment by KweenMother** [comment]
After another fresh install with only Cocoscrapers, Fen Light, and FENtastic, the ratings still do not populate.  I deleted the settings.xml from the userdata/addon_data/ but it did not work. 

![Userdata Addon_data skin nimbus](https://github.com/user-attachments/assets/99d71924-a62d-4121-b404-b3ce79dfa45e)
![Recently Updated Kodi](https://github.com/user-attachments/assets/0bfce8c9-05e2-4dd5-8b41-91974a43112b)
![Kodi Fresh Install - Fen Light and CocoScrapers](https://github.com/user-attachments/assets/47d25124-e291-488b-b2f3-00fd0fe9c1d2)

**Comment by KweenMother** [comment]
I just saw your last reply.  I will work on this.  Thank you.

**Comment by ivarbrandt** [comment]
When you copy paste, check to make sure there aren't any extra spaces before or after the API key. So copy the key manually instead of clicking the copy button.
