### ISSUE TITLE
MDbList ratings request

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.nimbus#127]
Is it possible to add Trakt ratings as part of the overall ratings MDbList is able to show in nimbus. I've personally grown accustomed to rely on Trakt ratings as part of checking if a movie or tv show is good enough to give it a chance, since it's a service much of the community use and I use with all of the addons I've used in the past and currently use today. Plus, I tend to contribute giving ratings as well to many of the stuff I watch too. And since most of the ratings and reviews are based on real people who use the service everyday not "paid critics etc". The many times I've let myself be guided by Trakt ratings, they haven't been wrong regarding a movie or tv show being bad or good.

So, I think Trakt ratings should be a great and honest add to be shown by nimbus when using MDbList ratings I find them to be even more thrust worthy than TMDB ratings themselves most of the time or even metacritic.

**Comment by ivarbrandt** [comment]
I feel the same way about Trakt ratings. I've been wanting to add other ratings as well but there isn't any room for them.

**Comment by Nuklear92** [comment]
> I feel the same way about Trakt ratings. I've been wanting to add other ratings as well but there isn't any room for them.

You could always sacrifice the least important ratings for it, example. If you asked me; I did remove either one of these two I marked with the red arrow, which I find not very important compared to having Trakt ratings instead. 

![image](https://github.com/user-attachments/assets/f52f5b05-4a84-477e-a127-26ffd9bec09e)

**Comment by ivarbrandt** [comment]
Removing any of the current ratings isn't an option. Other people might use/prefer those ratings.

I'll see if I can think of a way to add in Trakt ratings.

**Comment by ivarbrandt** [comment]
I thought of a way to do it but it requires redoing all of the ratings code across the skin. That's something that I currently don't want to do but I will keep it on the list.

**Comment by Nuklear92** [comment]
> I thought of a way to do it but it requires redoing all of the ratings code across the skin. That's something that I currently don't want to do but I will keep it on the list.

Oh, that's okay! No rush, as long as you found a way to make it happen eventually that's what matters. 👍

**Comment by ivarbrandt** [comment]
I got it done. Next update all 6 ratings will be configurable. I also added MDbList and Letterboxd along with Trakt.

**Comment by Nuklear92** [comment]
> I got it done. Next update all 6 ratings will be configurable. I also added MDbList and Letterboxd along with Trakt.

Awesome! Thanks, can't wait to test it out. 👍
