### ISSUE TITLE
[Bug] Fentastic skin or script helper bug using Widelist view with landscape toggled and mdblist key

### ISSUE THREAD

**Issue by Fubuz** [ivarbrandt/skin.nimbus#129]
Hi Ivar,
I have found 2 interesting bugs in Fentastic skin or the script helper. I understand this is not for Nimbus so hopefully, you can take the time and look at it. Would be very much appreciated.

1. **Missing landscape image** on the left side when in Widelist view and browsing through different menus (**NOT** browsing shows or movies). Toggled landscape button in widelist view and using mdblist api key.
2. **Missing progress bar** in Widelist view under landscape image if landscape button is **NOT** toggled (selected clearlogo).

Example:
Fenlight (missing image)
![image](https://github.com/user-attachments/assets/94f910e4-ba0d-4538-8686-50e4aba5b007)

Youtube (missing image)
![image](https://github.com/user-attachments/assets/9b6db617-0307-4113-9abd-4007c3687175)

The landscape image **is present** when browsing shows and episodes and movies. Example:
![image](https://github.com/user-attachments/assets/149b429a-a02b-4daa-9ddd-94121b4bb3c4)
![image](https://github.com/user-attachments/assets/f5ebf600-cbb7-40f2-a10b-59ff05657d6e)

Missing progress bar when using clearlogo in widelist view:
![image](https://github.com/user-attachments/assets/a6a34456-8e91-4551-aa4e-13c41fa52eaf)
![image](https://github.com/user-attachments/assets/6e1e0653-1f52-484b-a85f-6770ae6dabb9)

The bug can be reproduced:
- in combination with using **Widelist view + landscape toggle on + having a mdblist api key** (no matter the combination of toggled buttons in ratings/trailer setting)
- or just having **toggled landscape in Widelist view + having a mdblist api key** and using a different view system-wide

The landscape image bug can be circumvented by not using mdblist key (and losing ratings/trailers) or not having toggled landscape in Widelist view (and losing progress bar in widelist view under landscape image - the one that is present in pic 3 and missing in pic 6). 

I have tested this under 3 different systems: Win11, CoreElec, Android using Kodi 21.1, FENtastic 1.0.25, FENtastic Helper 0.6.20a. They all have the same 2 bugs. It is possible that this is all just one bug :)

I have also appended kodi log: [kodi.log](https://github.com/user-attachments/files/17601841/kodi.log)

Thank you very much for your time!

**Comment by ivarbrandt** [comment]
FENtastic is no longer being actively developed.

That being said I will try to fix the missing landscape image. As for the progress bar not appearing when clearlogo is enabled, that is intentional so that's not a bug.

**Comment by ivarbrandt** [comment]
FENtastic is no longer being actively developed.

In the future, please refrain posting from non-Nimbus related questions here. I closed the issues for FENtastic for a reason.
