### ISSUE TITLE
Screen doesn't un-dim when woken after sleep

### ISSUE THREAD

**Issue by npmstart-pray** [ivarbrandt/skin.nimbus#13]
I'm using the "Dim" screensaver, and I walked away while leaving what I was watching (an RD stream) paused. When I came back, I couldn't get the display to un-dim back to normal brightness, but the content would play normally otherwise. Had to reboot. Seems perhaps linked to CEC stuff. Haven't looked to see if there has been an update that happened or something...
RasPi4 running xbian (64bit) kodi v21

**Comment by ivarbrandt** [comment]
I'm doubt this is skin related. Strange things happen when you leave something paused for a long time then come back. I did that one time and when I came back, sound was completely gone for my Shield. 

This gives me an idea for a feature that would avoid these issues altogether.

**Comment by npmstart-pray** [comment]
It was a 5 minute pause, but I take your point. I also think the skin updated while I was paused, which is probably a bigger trigger for what I experienced. 

You're doing excellent work, sir, and I'd just like you to know how much I appreciate it!  Thank you!

**Comment by TwilightMercy** [comment]
> I doubt this is skin related. Strange things happen when you leave something paused for a long time then come back. I did that one time and when I came back, sound was completely gone for my Shield.
> 
> This gives me an idea for a feature that would avoid these issues altogether.

The sound gone issue is very annoying in Kodi, for all setups/skins.
Can you share insights/details on how the feature works to avoid this issue? and can this be duplicated to fix this issue on Estuary/FENtastic skins?

**Comment by ivarbrandt** [comment]
> The sound gone issue is very annoying in Kodi, for all setups/skins.

Has this happened to you too?

**Comment by TwilightMercy** [comment]
> > The sound gone issue is very annoying in Kodi, for all setups/skins.
> 
> Has this happened to you too?

Yes, it's common issue for a lot of Kodi users

https://www.reddit.com/r/kodi/comments/1btib7i/kodi_no_sound_until_restarted/

Or sometimes black screen after pausing a video for a long time, then only stop and replay the video will work.

**Comment by ivarbrandt** [comment]
I didn't know it happened to lots of people. 

My solution to implement something that will automatically end playback after x number of minutes if the video is paused. The number of minutes will be able to set to a custom value by the user.

**Comment by npmstart-pray** [comment]
That would be fantastic, if it can also remember where I was in what I was watching...and then maybe ask if I'd like to resume watching from where I left off...

**Comment by ivarbrandt** [comment]
>  if it can also remember where I was in what I was watching...and then maybe ask if I'd like to resume watching from where I left off...

This is handled by the addon you're using.

**Comment by umbrellaplug** [comment]
This is happening to me outside of playback. I can just leave Kodi idle and sitting overnight, come back in the morning and I have this exact issue.

I wanted to comment so you didn't waste time trying to end playback to solve it. The issue appears outside of playback.

**Comment by ivarbrandt** [comment]
> This is happening to me outside of playback. I can just leave Kodi idle and sitting overnight, come back in the morning and I have this exact issue.

Thanks for letting me know. Is it happening to you on any skin? Also, what device are you using? I ask because I used to have my Shield set to automitically sleep after x minutes and that messed up Kodi every time I came back in the morning.

**Comment by umbrellaplug** [comment]
> > This is happening to me outside of playback. I can just leave Kodi idle and sitting overnight, come back in the morning and I have this exact issue.
> 
> Thanks for letting me know. Is it happening to you on any skin? Also, what device are you using? I ask because I used to have my Shield set to automitically sleep after x minutes and that messed up Kodi every time I came back in the morning.

I'm running Nimbus (nice skin) currently. I am using a shield, but I also have the dim display or blacked out display on a firecube running 20.5.

I will check my shield settings as well. I have added some code in the nimbus skin helper service to call the kodi screensaver then immediately kill it on device wake. I'm going to see if that helps also. It appears to be related to the screensaver.

**Comment by ivarbrandt** [comment]
> I am using a shield, but I also have the dim display or blacked out display on a firecube running 20.5.

Same here. I had all sorts of issues with it until I changed the Shield settings to never sleep and instead use Kodi's screensaver dimming function after x minutes and this resolved all issues I was having outside of playback. Try this and let me know if it works.

> I have added some code in the nimbus skin helper service to call the kodi screensaver then immediately kill it on device wake. I'm going to see if that helps also.

Awesome. Keep me posted on how that goes. I have the logic for the auto ending of playback figured out but I won't add it if it's not really gonna help anything lol.

**Comment by ivarbrandt** [comment]
Added optional auto ending of playback. Hopefully it helps.
