### ISSUE TITLE
Displaying source name in Fullscreen video

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#130]
Hey ivar, long time , hope all is well :)
Thanks for hearing me out and considering this request

Anime using addons can be finicky, Tikipeter is adding a great feature where we can change "episode groups".
TMDB is using a default structure for the seasons and episodes. but people have created their own and anyone can create them. Some shows TMDB doesn't use a group that corresponds to torrents, but now you have the ability to fix that so it's a great tool we will shortly have.

It's not just for anime, you have Netflix shows where I've seen this feature correct and find results.
But when I'm watching anime and a next episode is loaded. I'm always thinking what if it's the wrong file, but their is no easy way to check what the actual file is being played (if you are in a pack)

Here is what it currently shows
![image](https://github.com/user-attachments/assets/f6df6aeb-9c0a-4066-81f7-ea9da979840a)

this is what is showing when I try to find a source 
![Screenshot (692)](https://github.com/user-attachments/assets/16d56e12-82a7-4366-9d0a-6ea2fef91d66)

and this information I would love to see on the fullscreen video control somewhere
![Screenshot (694)](https://github.com/user-attachments/assets/24c38f0b-3690-4c6e-a5b7-95f8830e2b8e)

I grabbed my history from RD and came up with something
<img width="1280" alt="Screenshot (695)" src="https://github.com/user-attachments/assets/4450350d-8364-472a-bcdd-64e0d08d75ae">

Now I can see what I was supposed to search for 
Dan Da Dan | S1 E1
and what file I'm actually playing
DAN.DA.DAN.S01E01.Thats.How.Love.Starts.Ya.Know!.2160p.B-Global.WEB-DL.JPN.AAC2.0.H.264.MSubs-ToonsHub.mkv

and have confidence it's the right file

Or even if you can add this in this screen
![image](https://github.com/user-attachments/assets/ef19eea6-1525-4ee7-9419-a5887f7c2f59)

Just somewhere so I can make sure the file name is the right season and episode number to what I want it to be

Is this possible and do you think it's worth it for you? I'm sure you would need addons to provide this information somehow?
thanks again , I like using Nimbus, it's perfect blend of aesthetics and speed

**Comment by ivarbrandt** [comment]
I've added this in and made it optional. It will be available in the next update.

**Comment by hcgiub001** [comment]
No way, this was one thing I didn't think you would add! honestly I love this! THANKYOU!

**Comment by hcgiub001** [comment]
I love it , thankyou :)
![image](https://github.com/user-attachments/assets/004e496a-12f6-4a3c-945c-286594848cff)

**Comment by hcgiub001** [comment]
This isn't a big deal but what do you think of only having the source text scroll (if it's too big) and keeping the rest the same

In my example above 
Bleach | 2 x 3 | March of the Starcross |
will stay fixed and the source text will scroll (if it needs to)
It will look cleaner and we can always have a fixed place holder. If too much bother then it's cool. Thanks again

**Comment by hcgiub001** [comment]
their is an issue, wasn't sure to open a new issue for this
I'll post a pic
![Screenshot (730)](https://github.com/user-attachments/assets/fb2d452c-6424-4f89-b585-62d2a39bd4ee)

it's a pack
this is what my RD history is saying the file is
/Blue Lock - Episode 02 - Monster 1080p BDRip x265 PCM 2.0 Kira [SEV].mkv

![image](https://github.com/user-attachments/assets/916ec135-1ddc-479a-9a7a-1b16dbc0f787)

this is the magnet link
magnet:?xt=urn:btih:a0b3739e0b2cea46afdc7085ab62de1f16f6e08c

I've noticed this on a few episodes.
if you need any more information, happy to provide.
hope you can have a fix. thank you

**Comment by ivarbrandt** [comment]
> It will look cleaner and we can always have a fixed place holder.

Maybe later.

> I've noticed this on a few episodes.
if you need any more information, happy to provide.
hope you can have a fix. thank you

I don't see the issue.

**Comment by Nuklear92** [comment]
@hcgiub001 Hey, sorry for being out of topic. I saw the screenshot of the torrent files search and im wondering if this is an add-on inside of kodi or a website if you could share the name of it, I'll appreciate it I'm always looking for torrents to cache on my RD cloud and that website or android apk looks clean.

**Comment by hcgiub001** [comment]
> I don't see the issue.

![image](https://github.com/user-attachments/assets/99d7675b-f87e-4b88-abf7-fff47bba1a15)

The show title is missing and it should write "Blue Lock - Episode 02 - Monster 1080p BDRip x265 PCM 2.0 Kira [SEV].mkv"

it has %20 for the spaces etc.

@Nuklear92 it's https://debridmediamanager.com/ I've been meaning to have a guide. it's a better way to manage your debrid stuff. The new scraper that was added (commet) is using the stuff on this site.
You can search for content that you can't find and good chance it has it. Comet isn't a full 1:1 with this
Just sync with your debrid account

**Comment by ivarbrandt** [comment]
> The show title is missing and it should write "Blue Lock - Episode 02 - Monster 1080p BDRip x265 PCM 2.0 Kira [SEV].mkv"
it has %20 for the spaces etc.

If the TV show title is missing that means it's not being set by whichever addon you're using.

As for the spaces, that's exactly how Kodi is reading the label for the filename. Fixing this would require parsing the label during playback and then spitting out a new one. That's not worth my time or effort for something I'll never use.

**Comment by hcgiub001** [comment]
100%, it's on a few shows and has the information I require to see the episode data. Thanks for doing this :)

**Comment by hcgiub001** [comment]
would you be able to point me where this logic occurs? I've had great success with chatgpt and I can start learning how to tweak things myself

**Comment by ivarbrandt** [comment]
> would you be able to point me where this logic occurs?

Yeah for sure. look for `NowPlayingLabelVar` in 'Variables_Seekbar.xml'.

OpenAI is a great resource. Especially if you use it to teach you how and why it's doing what it's doing. It can really speed up the learning process.

**Comment by hcgiub001** [comment]
I looked into this. chatgpt wasn't able to modify it. I learnt if I create an addon and use python script to activate when a video is played that we can change the information and store in another variable then to use that instead. but then would have to do for every update. I only wanted the information about episode so it's fine as it is.

one thing I changed was 
					<scroll>false</scroll>
in includes_seekbar.xml

when it was scrolling , it's disorientating, you don't get a glance of the content being displayed and you can't check episode that is supposed to be displayed against what is being pkayed.

For next update can you change so it doesn't scroll? I feel you get the best value that way. thanks
imo great underrated feature

**Comment by hcgiub001** [comment]
I figured out how it works slightly
![image](https://github.com/user-attachments/assets/59ca4d83-be83-4871-b1f9-81ce977aa4ca)

now I have full filename and I can easily view it, pretty chuffed, thanks for your help

**Comment by hcgiub001** [comment]
not sure how but chatgpt got it working
![image](https://github.com/user-attachments/assets/f521ab16-3352-49f4-ac54-c6de52b63050)

I created an addon and the python script created a new info label that I'm using. it wasn't working and we added some debug stuff, then for some reason that made it work!

I think it actually looks good and very useful, now will try to see how to add the file size stuff. really pleased with this!

**Comment by hcgiub001** [comment]
hey, do you know if we can get the file size of the file being played?
can't find anything from https://kodi.wiki/view/InfoLabels
checked kodi logs and nothing shows up.
Any help would be appreciated, thanks

**Comment by hcgiub001** [comment]
thanks for giving me the push and believing I can do it. I managed to add filesize!

![image](https://github.com/user-attachments/assets/6b846559-0b4d-442c-9bfe-b9e189270dbc)

**Comment by ivarbrandt** [comment]
Nice job man. Keep learning. I'm rooting for you.
