### ISSUE TITLE
Incorrect labelling of movies in Otaku

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#131]
Hey Ivar, hope all is good.

In Otaku when we are in Movies section, (e.g. Movies - Trending - Trending Last Year)  the label shows as "TV Shows"

![image](https://github.com/user-attachments/assets/7f1fd002-6735-4537-a7ef-7fcc5f713567)

This is the same label as Series

Each item has the property ListItem.Art(fanart)
inside it we can use the information to determine if it's a movie or a tv show
this is over the movie in my picture

> ListItem.Art(fanart): https://assets.fanart.tv/fanart/movies/887870/moviebackground/blue-giant-63d4c3f6e2b30.jpg

this is for a TV show

> ListItem.Art(fanart): https://assets.fanart.tv/fanart/tv/407520/showbackground/the-eminence-in-shadow-634d3705a1ec0.jpg

So after the https://assets.fanart.tv/fanart/ we either have tv or movie. 

Would be awesome if we had the right label for aesthetics reason. Would you be willing to change it?
Thanks for your consideration. :)

**Comment by ivarbrandt** [comment]
> Would you be willing to change it?

Nope. At least not like that. What's missing there in Otaku is a plugin category. This is what Nimbus uses to display that kind of information. It pulls it using this infolabel `$INFO[Container.PluginCategory]`.

If the information you want is stored in a different infolabel, I can add that in but you'll have to ask the Otaku dev where it's stored.

**Comment by hcgiub001** [comment]
thanks I'll ask Otaku dev, if no reply is received in 3 days I'll close

**Comment by hcgiub001** [comment]
I asked the developer and after some queries , this is their latest response

> I think if mediatype is included in the stuff sent to the spot that content type is set you could add a little swap there using mediatype as the decider, altho i think the visual aspect is all thats wrong with this situation so its more like a flaw instead of a issue lol.
> As for content type being used i think addons is used for menus like normal then tvshows or episodes for everything else due to them situations where the movie items are designed like a show with the movie item being episode 1 or whatnot.
> All this leads me to think the lazy fix idea might be best but i dont know the whole code structure so i could be wrong. 

seems the addon issue but I've asked twice and their seems to be no urgency, soif/when a fix happens I'll reopen the issue with the information you need.
thanks
