### ISSUE TITLE
IDEA 💡

### ISSUE THREAD

**Issue by Launcher2020** [ivarbrandt/skin.nimbus#132]
I'm using Embuary add-ons and I noticed that the main menu path. If I put suggestion movies it will say ( because you watched then the name of the movie ) and that looks amazing but when I set it to set widgets it doesn't say anything Is there a reason why it's not showing like it is  when putting on the main path and if so is there a way you can make it work on the main (set widgets) menu ..??? 
![Picsart_24-11-07_10-39-51-598](https://github.com/user-attachments/assets/e2758e24-7e80-4b4e-a2b3-a8c61590b2cc)
![Picsart_24-11-07_10-43-13-064](https://github.com/user-attachments/assets/1006b240-c9ff-4c8d-9729-c9c58ebd4bfd) 
I hope this works

**Comment by ivarbrandt** [comment]
That label is set by the addon in use. I'm pretty sure there isn't anything I can do about it.

**Comment by Launcher2020** [comment]
Okay thank you for replying back have a great day

**Comment by ivarbrandt** [comment]
You as well.

**Comment by Launcher2020** [comment]
> You as well.

Sorry for the bother but I was looking around Kodi community and came across this.. in not an expert but it this telling you how to do it it from the same add onn Embuary..

Get suggestions based on watched movies
Example

plugin://script.embuary.helper/?info=getsimilar&type=movie&pos=0&tag=HDR

Explanation

type = required
pos = optional, will return the result of the most recent watched item (starts with "0")
tag = optional, additional filter option to filter by library tag
Available item properties

ListItem.Property(searchstring) = Item that was used for the query
Picks up to 2 random genres of random watched item and returns similar items of your library.
