### ISSUE TITLE
Nimbus and fentastic not working on Coreelec

### ISSUE THREAD

**Issue by shanestonk** [ivarbrandt/skin.nimbus#135]
Trying to install nimbus and fenstatic skin on Coreelec (kodi) but keep getting error installation failed.

Hope nimbus and fentastic can work with coreelec nexus 20.5 and Ce Omega 21.1.1.

Reason using Coreelec because it support Dolby Vision profile 7 Fel and lossless audio codec. Android Tv cant play Dolby Vision Profile 7 fel.

umbrestuary skin work with coreelec nexus 20.5 but i cant use fenlight search with it.

**Comment by ivarbrandt** [comment]
Nimbus and FENtastic are both only for Kodi Omega.
