### ISSUE TITLE
Anime search not showing if search window for Fen Light is toggled off

### ISSUE THREAD

**Issue by 2Bnier** [ivarbrandt/skin.nimbus#136]
First of all, thanks again for this awesome skin, very clean and looks great!

[[[-- Not sure if this is an issue with Fen Lite or with Nimbus but if this issue is with the former, then please confirm so I can make a post there and just close this post.  --]]]

Version 0.1.28 changelog states 'Anime search widget has been added to search for Fen Light', but is not showing if the Search Window Toggle is Off.

![CnP_12112024_201831](https://github.com/user-attachments/assets/1da8324d-a98d-4fd9-ba3f-13b39a58068a)
![CnP_12112024_201841](https://github.com/user-attachments/assets/83c868c0-0473-4dad-b551-d94a8a915080)

Since Fen Lite already has the search function for Anime, shouldn't the home screen search dialog also include Anime? 

I'm not using the search window since it reloads all the widgets back in the home screen if search was canceled, taking much time.

Thank you.

**Comment by ivarbrandt** [comment]
> Since Fen Lite already has the search function for Anime, shouldn't the home screen search dialog also include Anime?

Yes, it should. Looks like I forgot to add that in when I added in Anime search for Fen Light. I'll get this fixed when I have some time.

**Comment by ivarbrandt** [comment]
Update is up.
