### ISSUE TITLE
yay or ney

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#137]
I find the dynamic of the GUI cool. Just thought of this

![ezgif com-animated-gif-maker](https://github.com/user-attachments/assets/8e4f1cd8-556e-4da6-8cc8-eb6f76742f31)

with different colours that would look cool, I used 3 different elements and cycled through

![image](https://github.com/user-attachments/assets/3605a32b-9279-4b84-9f35-bdf32748a30f)

it's going to be a ney, but what are your thoughts?

**Comment by ivarbrandt** [comment]
Looks cool

**Comment by hcgiub001** [comment]
just thought to share , maybe you can make use of it sometime for something else

**Comment by hcgiub001** [comment]
I shouldn't ask but it will look so cool

![image](https://github.com/user-attachments/assets/a00e5a04-a599-412d-b582-958f3d6c86c2)

image going through the list and you see different coloured collection set animation. It also just brings the movie alive and human visual system is designed to see changes, so it'll be easily identifiable without even looking at it directly, kind of drawing you to click

1/is this something that can be coded, easily?
2/does this have performance issues?
3/can this be added? :D

**Comment by ivarbrandt** [comment]
1. No extra code is required. You just need a gif and then you can replace the current static icon.
2. This shouldn't cause any performance issues.
3. Of course, it's an easy add. Fork Nimbus and add it to your own version of the skin.

**Comment by hcgiub001** [comment]
Boo!

**Comment by hcgiub001** [comment]
it's in variable flixpanel, and in extras icon. used paint to erase the centres and create the gif. Looks tacky af, yeah not adding that . thanks
I did learn you can have giffs instead of PNG, COOL!

**Comment by ivarbrandt** [comment]
> Looks tacky af

Yeahhh I had a feeling..

> I did learn you can have giffs instead of PNG, COOL!

Yup. The loading dots for the widgets in Nimbus use a gif.
