### ISSUE TITLE
Otaku - no ratings showing

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#141]
Hey
In Otaku https://github.com/Goldenfreddy0703/Otaku (anime addon) it's not showing rating

![image](https://github.com/user-attachments/assets/ad95ed6d-a459-45b5-9b74-4ee90cbbc965)

Theirs a property
ListItem.Rating: 
which has it, please could this be added?
thanks

**Comment by ivarbrandt** [comment]
Ratings aren't available for Otaku because the items don't provide an IMDb ID.

**Comment by ivarbrandt** [comment]
Update is up.

**Comment by hcgiub001** [comment]
Just saw this message, thanks Ivar, it's working great :)

**Comment by hcgiub001** [comment]
I've found out where Otaku is getting it's ratings from
anilist

for this anime
![image](https://github.com/user-attachments/assets/5c435b6b-c29f-483e-83d9-0797d04b1407)

and anilist
![image](https://github.com/user-attachments/assets/53767a10-acf8-4710-a1d2-e337eab67d52)

and all their metadata is sourced from anilist
ListItem.Art(poster): https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx170695-Nb1DIg7gIHCF.jpg

so I got the icon for anilist and made the background transparent
![removal ai _26b2b21c-f2bd-40c0-a1b8-f56c23448208-anilist_logo-svg](https://github.com/user-attachments/assets/e7f19759-dfd3-4fba-b6bd-934efcb42382)

to maintain consistency across the ratings and show where the ratings come from, would you consider adding this ratings in your ratings_image and have it displayed as a rating in Otaku as opposed to star_rating as you have now?

**Comment by ivarbrandt** [comment]
One rating for Otaku items would look kinda strange. I think it looks better now with the star rating.

**Comment by hcgiub001** [comment]
yeah it still looks good :), thanks again

**Comment by johnnyw94** [comment]
Hi dev! Is it possible to add star rating for Otaku testing addon too? 
https://github.com/Goldenfreddy0703/Otaku-Testing

It's by the same Otaku dev, but It's better compared to default Otaku with lots of bug fixes & features.

**Comment by ivarbrandt** [comment]
I'll add support for the star rating in Otaku Testing for next update.

**Comment by johnnyw94** [comment]
> I'll add support for the star rating in Otaku Testing for next update.

Thank you so much!
