### ISSUE TITLE
Set square artwork per widget

### ISSUE THREAD

**Issue by Better-Red** [ivarbrandt/skin.nimbus#142]
Hi,

As ever, thanks for all your work.

A question, not an issue.  I use an add-on which has a section pulled from multiple extractors, therefore no artwork, so the associated widget is blank. Obviously, I can go in through the main menu path, but for uniformity, I would like to add an image as artwork to said widget. I'm guessing this would be of limited use to most people, but wondered if you could think of a way of adding an image (either locally or in the cloud) to a specific widget?  I'm guessing the answer will be "not easily", but no harm in asking.

Many thanks.

**Comment by ivarbrandt** [comment]
I'm almost sure that this isn't possible.

The images for items in each widget are set by the addon in use.

That being said, it is possible that Nimbus isn't picking up on the artwork that is available for the addon in question. When you navigate inside the addon, is there any view that displays some kind of artwork? If there is, I can get it to show up in the widgets as well.

**Comment by Better-Red** [comment]
Thank you for getting back to me. Nimbus is working fine. There is no artwork in that section of the add-on, the add-on is treating a stream as a directory. I get that usually the artwork is made available by the add-on. The question is whether it is possible, at a code level or otherwise, to set the artwork per widget. Obviously, I had a look at the cpath_cache.db before asking. If the answer is no, please just close the issue.

**Comment by ivarbrandt** [comment]
Nah not possible.
