### ISSUE TITLE
Auto widgets label

### ISSUE THREAD

**Issue by Zero0Q** [ivarbrandt/skin.nimbus#144]
Hi,
Im trying to add random trakt liked list folder in nimbus movies hub, but the name of those incoming folder is not showing when i add this in widget name ($INFO[Container(19011).ListItem.Property(autoLabel)])
If i do it from autowidgets addon it shows names but its heavy loading widgets, can you please see where is the isue for this.

Thanks

**Comment by ivarbrandt** [comment]
As far as I know `$INFO[Container(19011).ListItem.Property(autoLabel)]` only works for AutoWidget.

Fen Light has a feature for random widgets with dynamic handling of the labels. Go to Tools > Tips for Use to learn how to set these up.

**Comment by Zero0Q** [comment]
Thank You for the tip, i will check it out.
