### ISSUE TITLE
[Request] Make POV addon Source Select UI auto scroll links when they're longer than the available readable space

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.nimbus#146]
As the title says, in FenLight when the links surpass the available readable space, they'll auto-scroll. 

With the POV addon the links are static and you cannot read the rest of it when links file names are longer.

![image](https://github.com/user-attachments/assets/6a320aa8-d497-4ca3-93ac-7d97141d9574)

I'm not sure if you are able to do this yourself, or in any case let me know and perhaps I can tag the developer which I think is Kodifitzwell. And hopefully this can be fix for when the addon is used with Nimbus skin.

**EDIT:**

Just to add to this post as I didn't wanted to make another one since it's related to the same add-on. I just discovered that the POV addon doesn't display "Season Premiere/Season Finale" tags like FenLight and Umbrella add-ons. Hopefully this can also be fixed. 

Here's FenLight as you can see it displays Season Premiere.
![image](https://github.com/user-attachments/assets/f559945a-b16d-4441-9d59-fa9fbbc72a13)

Here's POV add-on as you can see no Season Premiere tag.
![image](https://github.com/user-attachments/assets/7ac4c2c1-f14b-4b9f-a922-b5bb98c8a313)

**Comment by ivarbrandt** [comment]
The autoscrolling of the links is a POV thing.

As for the episode type, something might have changed with POV. I recently remember seeing it work correctly with POV and Fen/Fen Light. Only thing I can think of is the property was changed/removed.

I'll double check my code to make sure the issue isn't on my end.

**Comment by Nuklear92** [comment]
> The autoscrolling of the links is a POV thing.
> 
> 
> 
> As for the episode type, something might have changed with POV. I recently remember seeing it work correctly with POV and Fen/Fen Light. Only thing I can think of is the property was changed/removed.
> 
> 
> 
> I'll double check my code to make sure the issue isn't on my end.

I see, either way I'll tag @kodifitzwell then. Hopefully he reads the issue post and the auto-scrolling for links can be something he could do if possible.

**Comment by kodifitzwell** [comment]
I don't like the scrolling text, so I *may* never (never say never) do that.  I might suggest the listinfo view if you require a longer view of the title.

![Clipboard-1](https://github.com/user-attachments/assets/32f5a009-ccb2-4e24-a37c-11ee070d824a)

someday I will do a wide(r) list removing the poster, like I recently did for Dradis/Infinity.

"Season Premiere/Season Finale" was never part of POV.  I don't really see a need for this, but people seem to like it so in the future.  I rewrote the way it was done in Infinity so it did not require an additional function call for season info.  if I can do the same in POV I will.

**Comment by Nuklear92** [comment]
@ivarbrandt I'll be closing the issue as the addon dev said he might be addressing both issues within future updates of the addon. My apologies for taking some off other things you might had been doing.

**Comment by Nuklear92** [comment]
@kodifitzwell @ivarbrandt Okay, POV does indeed have Season Premiere and Finale tags. However, here's what I discovered and I'll post a small clip I recorded below showing the issue. The problem seems to lay in the "current" season being watched. For some odd reason it does not show the Season Premiere and Finale tags. Only after that season is finished being watched. Then, it will start showing the Season Premiere and Finale tags. Also, as you'll see below "Unwatched" seasons will also show Season Premiere and Finale tags, only when your next season is the one "unwatched" then the Season Premiere and Finale tags disappear. Until I finish that season. 

Which leads me to believe this could be a small bug of some sort, maybe?

**Here's the video clip**
https://streamable.com/60l1xb

**Comment by kodifitzwell** [comment]
the listitem property is set independent of the watched status.  so the only suggestion I have is clear the meta cache (or all).

**Comment by ivarbrandt** [comment]
Clearing all cache and restarting Kodi fixed it for me.

**Comment by Nuklear92** [comment]
@ivarbrandt @kodifitzwell wow, it did the trick! Clearing meta cache fixed the issue, thanks a lot for the tip. 💙
