### ISSUE TITLE
"Trakt options" from context menu

### ISSUE THREAD

**Issue by chary47** [ivarbrandt/skin.nimbus#15]
When clicking Trakt options from the context menu of a widget item the screen goes black. The usual sound of scrolling a menu plays when scrolling with the remote, but the actual menu seems to be out of bounds or something.

This is on kodi for androidtv using an nvidia shield.

**Comment by ivarbrandt** [comment]
Which addon?

**Comment by chary47** [comment]
I use FEN, TMDB Helper and AutoWidget.

I noticed when I don't try this on the widget but by navigating through TMDB Helper to the list that the widget links to I can sometimes get the Trakt option window to open, but only once. Then I have to exit the list and reopen it. Then the Trakt option window shows up again

**Comment by ivarbrandt** [comment]
I just took a quick look and there's definitely something wrong with the context menu. I'll take a look at it this weekend.

**Comment by ivarbrandt** [comment]
Fixed. Changes are in `0.1.10`.
