### ISSUE TITLE
Nimbus Update

### ISSUE THREAD

**Issue by ivarbrandt** [ivarbrandt/skin.nimbus#16]
EDIT: This guide has been updated as of `0.1.15`. In order to have access to all of the new features make sure that you are on the latest version of the skin `0.1.15` and the helper `0.0.37`.

As of` 0.1.15`, I've added a video showing how to use the new features below. You can view it here: https://rb.gy/l9zpkl

There is a big Nimbus update now available with lots of changes to the skin. I’m writing this guide to hopefully help the transition go more smoothly as some of the changes may be confusing.

I really wanted to add some optional artwork types and extend the blur functionality to the rest of the skin. This would mean axing color themes completely. But I know that there’s some of you that prefer color themes so I was able to come up with a solution that fits both preferences. That did require quite a few changes. I would say about 97 percent of the original look can be achieved.

The biggest change that I want to go over is the handling of artwork and how it affect the skin’s overall appearance. Artwork settings can be configured individually for the home screen and views, but only the home artwork settings influence the whole skin. Let me show you what I mean.

Go to the home screen and highlight the main menu, click left and the home screen artwork settings will pop up.
![Screenshot_20240717-190955](https://github.com/user-attachments/assets/1745d082-d0c9-45cf-9c54-fa11a7af6b8f)

Here you can toggle blur, change artwork style from fanart to landscape, and when landscape is enabled you can display it normally or use fanart. There is also options for which art to display for the new landscape widgets as well as options for episode art. For episodes, when fanart is chosen as the style, you can choose between thumbs or fanart. When landscape is enabled, you can choose between thumbs, fanart, or landscape.

Besides the new Landscape widget and views which I will get to below, some of the biggest changes are how the selected artwork impacts the overall look and feel of the skin. Here’s an overview of the combinations and how they change the skins overall appearance.

Blur disabled + fanart = original Nimbus look with fanart and black backgrounds.
![Screenshot_20240707-161139](https://github.com/ivarbrandt/skin.nimbus/assets/54084201/00fa5e5b-9d97-4b2f-92e9-441a83990654)
![Screenshot_20240707-161152](https://github.com/ivarbrandt/skin.nimbus/assets/54084201/f4e87509-bb87-4aec-8672-bf458506ac71)

Blur disabled + landscape + default/fanart = New look where landscape or landscapefanart is used instead of fanart. The color theme is also used across the skin and menus.
![Screenshot_20240707-161232](https://github.com/ivarbrandt/skin.nimbus/assets/54084201/52d5831d-a454-4c80-a9f5-ede9f2943e2c)
![Screenshot_20240707-161238](https://github.com/ivarbrandt/skin.nimbus/assets/54084201/78b1cf2e-2623-47aa-ad7f-b203160cf54c)

Blur enabled + fanart/landscape + default/fanart = Blur everywhere. Blur changes depending on which type of art is chosen. If fanart isn’t available, it will fall back to the custom background image you’ve set. You can set this in Skin settings as well.
![Screenshot_20240707-161346](https://github.com/ivarbrandt/skin.nimbus/assets/54084201/a6e9be88-fd75-48e9-930c-568422256307)
![Screenshot_20240707-161404](https://github.com/ivarbrandt/skin.nimbus/assets/54084201/3f2898f2-ee8e-408f-9b4e-8f8e9d71bff1)
![Screenshot_20240707-161410](https://github.com/ivarbrandt/skin.nimbus/assets/54084201/b8338d0d-328d-4e70-b71d-7a9ade132a01)

Now, these exact same options are available in the video windows inside addons. Let’s say you go to a movies window then access the media menu panel on the left. You’ll see Artwork and when Landscape is enabled you can choose between default and fanart. You can also access other settings in the media panel like clearlogo and blur. When blur is disabled and landscape is enabled, the skin will switch to the selected color theme as well.
![Screenshot_20240707-161615](https://github.com/ivarbrandt/skin.nimbus/assets/54084201/b332af35-3f4b-4711-bd40-72a37a6f7d83)

Artwork can be configured independently of the home screen and video windows. Artwork can also be configured independently for movies, tvshows, seasons, and episodes in the video windows. For example, you can have landscapefanart for movies, fanart for tvshows, and landscape for seasons etc.

There are also 3 new views that have been added:

List (movies, tvshows, seasons, episodes, episode lists, menus, addons, favorites, etc)
![Screenshot_20240720-080833](https://github.com/user-attachments/assets/27b2f397-0e75-4e17-aeb9-19032c3ab6ce)
![Screenshot_20240720-121523](https://github.com/user-attachments/assets/4ba1ea9a-35fa-4717-ac1c-cb66bd30f897)

FlixScape and the accompanying homescreen Landscape widget (movies, tvshows, seasons, episodes, episode lists)
![Screenshot_20240714-175407](https://github.com/user-attachments/assets/bf782faa-2a8e-4db4-8537-8beca9979080)
![Screenshot_20240717-184947](https://github.com/user-attachments/assets/cdaf7eed-2585-4d14-9a69-998fb0bf0f32)

WallScape (movies, tvshows, seasons, episodes, episode lists)
![Screenshot_20240717-181251](https://github.com/user-attachments/assets/86611807-6516-4df4-bcce-1914dceb6dad)

The artwork options for List are completely separate from the other views and content types. So you can have different artwork for movies, tvshows etc. Nimbus will remember what you set and display that artwork just like the other views. Also, please note that one-click trailers and auto trailers play in fullscreen from this view.

In FlixScape you'll see an additional option called `Artwork (Items)`. This toggles the art used for the items themselves. When toggling this, you'll need to refocus the main view before fully seeing the changes. The equivalent setting for this in the home screen is called `Landscape widgets` and you'll see this in the artwork settings menu. In FlixScape, you also have one click access to WallScape view when pressing down. Just make sure you have `Enable one-click switch to Wall/WallScape view` enabled in Skin settings. This option will work even if you've locked the view. NOTE: This also works the same way in Flix view.

That’s about it for the main changes. The last few updates saw quite the transformation of Nimbus so feel free to explore around and try different options and combinations to best suit your preferences. If you have any questions feel free to reach out. Even though this will be a big update with lots of changes, my stance on feature requests has not changed. Please respect it. Bug reports are welcome. Enjoy!

**Comment by Tikipeter** [comment]
Oh geez, which one to choose?!

These are all great ivarbrandt. I may give the Landscape Art with Blur a go first when the update happens.

This looks like a lot of work. :)

**Comment by ivarbrandt** [comment]
Lots of options my guy.

>I may give the Landscape Art with Blur a go first when the update happens.

Solid choice. That's exactly what I've been rocking.

>This looks like a lot of work. :)

Bro yes it was. Some of the visibility conditions need to make this happen are craaazy lol.

**Comment by nightknight111** [comment]
Appreciate it more than I could express. It looks amazing and runs smooth even on my chromecast 4k. I would completely avoid using widgets until this skin. Lovin my setup rn

**Comment by ivarbrandt** [comment]
Awesome! Glad to hear you're enjoying it.

**Comment by Jatobas66** [comment]
Hi Guys,

I'm absolutely loving this skin, but I'm unsure how to install it on my Kodi on Nvidia Shield Pro. Could you please help me with a guide on how to install it or let me know if it's compatible? I'm using a Nvidia Shield Pro (Android device) with Kodi OMega.

Thanks!

**Comment by djdirty60** [comment]
Hey Ivan,

Really got a great skin to the update. Hope the skin gets better and better in the future 😁😁😁.

But want to thank you for all your hard work in this skin/update. Keep it up 👍🏼

**Comment by ivarbrandt** [comment]
@Jatobas66 

You can install it from my Kodi repo here: https://ivarbrandt.github.io/repository.ivarbrandt/

**Comment by tony2501** [comment]
How do I make the trailers work if I have no content in my kodi library and i pull everything in from my plex server using composite addon?

**Comment by ivarbrandt** [comment]
The composite addon would need to provide an IMDB ID through an info label:

`$INFO[ListItem.IMDBNumber]`

Otherwise, there is currently no other way.
