### ISSUE TITLE
Trailers conflicting

### ISSUE THREAD

**Issue by basicals** [ivarbrandt/skin.nimbus#17]
Hey ivarbrandt, first things first, this skin is posed to explode in popularity and become mainstream by you keeping it simple, light, and not cluttered with customization options, congrats on your approach and hopefully it'll remain the same! 

To the issue:
Latest version on a shield TV 2017.
Enable the Netflix-like trailer feature for the main menu, click on a movie on a widget, launch it's trailer, quickly press back. You'll land at the main menu with the trailer playing in the background, but the Netflix-like timer will remain and trigger, relaunching the trailer on top of the trailer that's currently playing.

**Comment by basicals** [comment]
Sorry, eng is not my native language. let's see: 
Click on a movie, select trailer, the trailer begins in full screen. Press back, you'll land in the main menu. Wait a bit and the issue will happen.

**Comment by ivarbrandt** [comment]
> Click on a movie, select trailer

So you mean starting a trailer from an add on, not through autotrailers or one-click trailers in Nimbus?

**Comment by ivarbrandt** [comment]
Fixed for next update.

**Comment by basicals** [comment]
Got it then, cheers.
