### ISSUE TITLE
Icon bug on main screen "next episodes widget"

### ISSUE THREAD

**Issue by basicals** [ivarbrandt/skin.nimbus#18]
Setup a tmdbhelper>your next episodes widget, and there's this blank placeholder next to the episode duration on every episode in the widget, except when the episode is season premiere.

![PXL_20240708_092741246](https://github.com/ivarbrandt/skin.nimbus/assets/6373803/8010522e-cdee-4ebb-96df-86e73c1a9509)

![PXL_20240708_093419206](https://github.com/ivarbrandt/skin.nimbus/assets/6373803/99025b3b-a431-4b2f-a5ec-751f288be1ea)

Side question: is it intended for square view to show landscape episode previews with black bars on top and bottom? Instead of just the episode preview (maybe you haven't/won't implement landscape size? Would look better / Netflix like tho.

Cheers

**Comment by ivarbrandt** [comment]
TMDbHelper is not supported. Use an addon directly.

**Comment by basicals** [comment]
All right then, thanks for the response. 
I've been pondering wether I should get rid of tmdbhelper, but I'd like to keep the homescreen setup independent of whether a "unofficial" addon ceases to exist or the dev goes AWOL (like Seren did).
Now I wonder is there a reason you decide to not support tmdbhelper, if I may ask?

Back to the landscape widget, and to reply with my opinion, not about to go comparing skins, but AH2 got a pretty sleek way of doing it with an oversized landscape thumb which keeps the viewers focus where it already is, and the series fanart in the background for flavor. This way, the user doesn't need to switch from looking at one item (in the way you have it setup, the series portrait ), to another place (the episode art on the background), to understand what that item is about (the specific episode).

And sorry to extend this, but I just authorized trakt in fen light , setup a squared "next episodes" widget, and now I'm getting an "items failed to play" error whenever i focus the widget for about 6 seconds. Feels like it's attempting to play a video trailer and fails?

Netflix-like trailers are working all right for other tmdbhelper widgets.

![PXL_20240708_171154194](https://github.com/ivarbrandt/skin.nimbus/assets/6373803/b4b15399-95b2-4dde-806f-b85acebde57d)

**Comment by ivarbrandt** [comment]
> Now I wonder is there a reason you decide to not support tmdbhelper, if I may ask?

Because it's a resource hog. If my skins required it, that would make it close to unusable on many lower powered devices.

> AH2 got a pretty sleek way of doing it with an oversized landscape thumb which keeps the viewers focus where it already is, and the series fanart in the background for flavor. This way, the user doesn't need to switch from looking at one item (in the way you have it setup, the series portrait ), to another place (the episode art on the background), to understand what that item is about (the specific episode).

I do it the exact opposite way. Focus is in the fanart, and the posters are for flavor. I get what you're saying though.

> now I'm getting an "items failed to play" error whenever i focus the widget for about 6 seconds.

Square widgets don't have autotrailer functionality. I can add that in for next update.

**Comment by basicals** [comment]
Thanks for your input about TMDBHelper, I'll look into de-tmdbhelperfying my Kodi.

I'm getting playback failed on Poster TV Series widgets too btw:

2024-07-08 23:13:25.076 T:28403    info <general>: VideoPlayer::OpenFile: 
2024-07-08 23:13:25.077 T:27484    info <general>: Creating InputStream
2024-07-08 23:13:25.077 T:27484   error <general>: CVideoPlayer::OpenInputStream - error opening []
2024-07-08 23:13:25.077 T:27484    info <general>: CVideoPlayer::OnExit()
2024-07-08 23:13:25.185 T:28403    info <general>: CVideoPlayer::CloseFile()
2024-07-08 23:13:25.197 T:28403    info <general>: VideoPlayer: waiting for threads to exit
2024-07-08 23:13:25.197 T:28403    info <general>: VideoPlayer: finished waiting

**Comment by basicals** [comment]
Nevermind about that last part. 
Every Fen light widgets were erroring autotrailers because I had the "use minimal media info" setting enabled inside Fen light.

**Comment by Tikipeter** [comment]
>I've been pondering whether or not to add a landscape widget

:) :)

**Comment by ivarbrandt** [comment]
> :) :)

You can't just come in here and sway me like that.

**Comment by Tikipeter** [comment]
:) x 3?

**Comment by ivarbrandt** [comment]
Ahhh you got me. I'll do it. Now that you're here...

Can you help me come up with a solution for stacked widgets? I kinda miss them. I tried to implement them when I first created Nimbus but I didn't see a way it could be done because of the way I designed the scrolling on the home screen with animations using `Animation_Widget_Poster_Slide`.

Because of this, the structure would need to be entirely different as the whole stacked widget would need to be contained in one include like `WidgetListPoster` for example.

**Comment by Tikipeter** [comment]
I'll hopefully be able to look into this more tomorrow, but on a quick think, if you definitely need them contained as a single include your best bet might be going with some kind of grouplist containing both the widgets.

It's been a fair while since playing around with this to get it all working right last time, so my memory is not going to help me.

**Comment by ivarbrandt** [comment]
Whenever you can. No rush at all.

Using a grouplist could work. I'll look into it after I finish the landscape views and widgets.

**Comment by ivarbrandt** [comment]
Sneek peek @Tikipeter 

![Screenshot_20240714-175407](https://github.com/user-attachments/assets/ed688df8-67b6-443e-a686-461a9942aae6)

**Comment by npmstart-pray** [comment]
That looks super sexy!  Can't wait!

**Comment by ivarbrandt** [comment]
> Can't wait!

Me too! This next update is gonna be 🔥

**Comment by Tikipeter** [comment]
I couldn't get stacked working. It would never even appear when I tried grouplisting the 2 widgets. :( :(

**Comment by Tikipeter** [comment]
Lurrvvveee those landscapes. Wow!!!

**Comment by ivarbrandt** [comment]
> I couldn't get stacked working. It would never even appear when I tried grouplisting the 2 widgets. :( :(

All good man. Thanks for taking a crack at it.

> Lurrvvveee those landscapes. Wow!!!

Yessirrr. Coming soon. Hopefully I'll be able to push the update later today.

**Comment by ivarbrandt** [comment]
Update is up and guide has been updated.
