### ISSUE TITLE
No hint at verticality of the overall design

### ISSUE THREAD

**Issue by basicals** [ivarbrandt/skin.nimbus#19]
This might border in a feature request but I'd think it might be an "oversight", nevermind if not the case. 
Currently there's nothing to hint the user that the layout of the skin is vertical. My wyfu instantly asked me "but where's the rest of the stuff?"
This is broadly solved on streaming apps by peek at what's down there, thus inviting the user to scroll down. Some Kodi skins solve it with a small downwards arrow icon, which looks cheaper but gets the job done.

![PXL_20240708_100150886](https://github.com/ivarbrandt/skin.nimbus/assets/6373803/79041fb3-a978-45a2-9527-028794aa4ba9)

![PXL_20240708_095702483](https://github.com/ivarbrandt/skin.nimbus/assets/6373803/0f50c292-f275-4ead-93f6-e24b0f90268d)

**Comment by ivarbrandt** [comment]
You can find out the verticality of the design by minimally exploring a widget. Click up or down and there's the design.
