### ISSUE TITLE
No Movies / TV Shows menu option

### ISSUE THREAD

**Issue by Seroczynski** [ivarbrandt/skin.nimbus#21]
After installation no menu item for Movies and TV Shows was shown. In Skin Settings there is not much I can do. "Remake menus and widgets" doesn't fix it, and when I try to use "Set main menu path" or "Set widgets" I get an empty prompt with only a Cancel button.

**Comment by ivarbrandt** [comment]
It sounds like you didn't install the helper. 

Did you download the skin from my Kodi repo?

**Comment by Seroczynski** [comment]
Yes, I've manually added your repo and installed the skin. The dependencies were downloaded automatically. I have both "Nimbus" and "Nimbus Helper" listed as installed under my Add-ons.

**Comment by ivarbrandt** [comment]
Ok I need more info. What device are you using? Operating system? Does anything in the skin work for you?

You could also try removing it and reinstalling.

**Comment by Seroczynski** [comment]
I've tried removing Nimbus and reinstalling, but I got the same results. The skin settings option shows blank entries at first, and after a rebuild show names (like "Movies" and "TV Shows" etc.). But even though my media library has content, no default movies or shows are being shown in the main menu (not even the menu items themselves).

I can add the Video menu item, select my sources through there and then use that. This way I can access all my media and change the look and feel of my media sources. So I think other features are working, except the widgets to show Movies and TV Shows on the main menu.

Setup
Device: Google Chromecast with Google TV 4K
OS: Android TV 12.0.0 API level 31 (Linux 4.9.269)
Kodi build: 21.0.1 (20240409)

**Comment by ivarbrandt** [comment]
Nimbus doesn't support local library content. Use addons to make your widgets.

**Comment by Seroczynski** [comment]
I don't think I understand you. Why wouldn't my content work for this skin? Do you mean this is only to be used with live subscription services?

**Comment by ivarbrandt** [comment]
> Do you mean this is only to be used with live subscription services?

Correct
