### ISSUE TITLE
[Request] duplicated episode thumbnail as background FanArt in homescreen widgets when using mixed-episode list

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.nimbus#22]
When you set the "Next Episodes" with Lanscape, Poster, etc. from FEN/FENLight or I believe any other addon that has a Mixed-Episode list. It will duplicate the thumbnail artwork as the FanArt background which makes it look bad, specially if the episode thumbnail has a lower quality picture it will get zoomed in. 

This doesn't happen if you go inside the FEN addon and navigate to Next Episodes the artwork will be the official title FanArt as you'll see in the example screenshots below.

**Homescreen Widgets, duplicated artwork**
![image](https://github.com/user-attachments/assets/2c801010-3bee-4b6a-97fd-62494e817da8)

**Inside FenLight add-on, same Next Episode list** No duplicates, tv show's official FanArt is correctly displayed. 👍
![image](https://github.com/user-attachments/assets/ad62786e-b554-45be-9957-ae3548204391)

Hopefully you can make this look the same in the homescreen widgets when the user selects a mixed-episode list to be used.

**Comment by ivarbrandt** [comment]
Artwork settings > episodes/default. Toggle it to fanart.

**Comment by Nuklear92** [comment]
> Artwork settings > episodes/default. Toggle it to fanart.

I'll double check when I get home and see if that fixes the issue, I'll report back. 👍

**Comment by Nuklear92** [comment]
> Artwork settings > episodes/default. Toggle it to fanart.

It worked! Thanks for the quick guide. 👍

I'll close the issue as it's resolved.

**Comment by ivarbrandt** [comment]
This will be automatic in the next version with an option to use landscape art as well.

**Comment by ivarbrandt** [comment]
@Nuklear92 

Is the white focus frame on your setup always that big? Or does it have a soft pulsing glow?

**Comment by Nuklear92** [comment]
> @Nuklear92 
> 
> 
> 
> Is the white focus frame on your setup always that big? Or does it have a soft pulsing glow?

Haha! You know... I haven't quite paid attention to it. I'll double check for you and report back. 👍

**Comment by Nuklear92** [comment]
@ivarbrandt Well, yes that's how they look.

Here's two screenshot I took;

![image](https://github.com/user-attachments/assets/fcfe6821-76e9-4f0e-b40b-72e17001071e)

![image](https://github.com/user-attachments/assets/5bbf6aa3-2af7-4654-9c1c-2d9b24076c04)

**Comment by ivarbrandt** [comment]
Thanks for the screenshots. That's not normal. The focus frame you have is the absolute biggest it can be in the animation cycle.

It's supposed to look like this:

https://github.com/user-attachments/assets/818c0ac8-519d-47da-a5a7-017fea18feff

**Comment by Nuklear92** [comment]
> Thanks for the screenshots. That's not normal. The focus frame you have is the absolute biggest it can be in the animation cycle.
> 
> 
> 
> It's supposed to look like this:
> 
> 
> 
> https://github.com/user-attachments/assets/818c0ac8-519d-47da-a5a7-017fea18feff
> 
> 
> 
> 

Yeah, that's definitely odd. Mine doesn't glow and I was looking for in the skin settings to see if there was any toggles I needed to turn on, but there's none. 🤷‍♂️ are you using background blur in your setup?

**Comment by ivarbrandt** [comment]
> but there's none. 🤷‍♂️ are you using background blur in your setup?

Yes I am but blur won't affect that. I used to have a setting for the glow wayyy back when I first started working on Nimbus but then I made it default. Thing is that skin setting stayed in my settings.xml which is why I never noticed it on any of my installs. It's an ancient bug that has now been fixed.

**Comment by Nuklear92** [comment]
> > but there's none. 🤷‍♂️ are you using background blur in your setup?
> 
> 
> 
> Yes I am but blur won't affect that. I used to have a setting for the glow wayyy back when I first started working on Nimbus but then I made it default. Thing is that skin setting stayed in my settings.xml which is why I never noticed it on any of my installs. It's an ancient bug that has now been fixed.

Oh, so you now fixed this for the next update?

**Comment by ivarbrandt** [comment]
Yep sure did.

I feel bad that people were using it with a giant focus frame.

**Comment by Nuklear92** [comment]
> Yep sure did.
> 
> 
> 
> I feel bad that people were using it with a giant focus frame.

Haha! If you didn't tell me about it, I wouldn't have a clue that it was supposed to glow 😅. 

Hey, now that I had a chance to a couple of comments with you. I was going to ask you if you also had future plans to keep overhauling the video player OSD as you had done with skin media views, etc. I mean, not that it's bad as it is. But, since now you have these beautiful FlixScape, among other fine tunings that has made the skin even more good looking when you have the current video OSD, it doesn't quite match to how the skin looks now and bit more like "Estuary" but dark. 

I'm definitely not asking to to anything at the moment. Just asking in general if you also have any plans for that section of the skin as well in future updates to fine tune and match the experience more to how the skin looks now? 

Also, it would be nice you could add an option for the OSD player to instead of switching to different languages/subtitles when click their respective icons, it opens the audio/subtitle options so you can change it manually instead of having to click the icon many times until you see the desired audio track or subtitle. 🤔

**Comment by ivarbrandt** [comment]
> if you also had future plans to keep overhauling the video player OSD

Nothing planned as of now. But thats how it happens for me. I didn't plan pretty much all of the big updates Nimbus has gotten recently. So just cause I don't have anything planned, doesn't mean I wont randomly overhaul the OSD at some point. Doesn't mean I will as well.

> it doesn't quite match to how the skin looks now and bit more like "Estuary" but dark.

What do you mean by this? What do you think it would look like if it matched?

> instead of switching to different languages/subtitles when click their respective icons, it opens the audio/subtitle options so you can change it manually

You mean a direct jump into the available subtitles/audio tracks dialog?

**Comment by Nuklear92** [comment]
> > Nothing planned as of now. But thats how it happens for me. I didn't plan pretty much all of the big updates Nimbus has gotten recently. So just cause I don't have anything planned, doesn't mean I wont randomly overhaul the OSD at some point. Doesn't mean I will as well.
> 
> 
> 
> Oh, nice! I always thought you had all of this in some kind of "to-do list". 😅
>
>
>
> > What do you mean by this? What do you think it would look like if it matched?
> 
> 
> 
> I really can't figure out as well how it would like, honestly. But putting in example a skin like Arctic Horizon 2, Arctic Fuse, etc. the OSD Player seems to have somehow the same kind of buttons, option boxes language you'll find when navigating homescreen widgets, information within context menu, etc. I'm not really very good explaining these but you can just see at a glance that it somehow carries the same design from the skin has in some way. For example, if you open the player process in Nimbus it's pretty much the same as Estuary. Whereas if you open it in a skin like AH, AF it has it's own design based on the overall skin UI and it displays the player process information in different way. I'll have to grab some screenshots for this to make more sense as I'm sure it's not making any for you hahah! 😄
> 
> 
> 
> > You mean a direct jump into the available subtitles/audio tracks dialog?
>
>
>
> Yes! Or, perhaps do it like AF (Arctic Fuse) where, when you hover over the audio/subtitles icon it will kind of pop up the available audio and subtitles tracks available, if there are multiple available. And the audio tracks displayed at glance will also show if they have different codecs. Example; 

English (Dolby Digital Plus 5.1)
English (Dolby TrueHD ATMOS 7.1)
English w/commentary (Dolby Digital 2.0)
Spanish (Dolby Digital Plus 5.1)

I will try to share some example screenshots or video clip later on for you to understand better how it's presented in a skin like Arctic Fuse. One thing I'm not sure is, if making the audio tracks and subtitles to pop out for the user to select them when you hover over the icons could make the OSD player skin to stutter the video playback as it does in Arctic Fuse, Arctic Horizon 2. Which is why I said about making them as you clarified "direct jumps to the dialog instead". 

Perhaps, for the other option I mentioned. You might have to play around first in a dev build to see if it won't cause any performance drops, etc. 

For the meantime, direct opening of the audio track and subtitles dialog when clicking their icons should do. Instead of having to click many times if a video has multiple audio/subtitle tracks available. 👍

**Comment by ivarbrandt** [comment]
> you can see at a glance that it somehow carries the same design from the overall skin UI in some way.

I get what you mean. The design for all the dialogs in Nimbus aren't changed very much from Estuary. I feel like they don't need to be though. Maybe later I'll come up with a fresh design for all the dialogs.

Also, the OSD has several components that are shared by the skin so I'm not sure what you mean by the design of it not carrying from the rest of the skin. The buttons have the same style from the main menu and some other parts of the skin.

> Or, perhaps do it like AF (Arctic Fuse)
> in a skin like Arctic Fuse
> as it does in Arctic Fuse, Arctic Horizon 2

I see you're coming from Arctic Fuse lol. AF is a good skin. I've played with it a few times and the level of coding is impressive. Hat's off to jurial. That being said, because Fuse is so densely packed with features and functionality, it tends to suffer performance-wise even on a Shield Pro. Lower powered devices are pretty much cooked with that skin. I was making a quick video on Nimbus functionality yesterday and you can't even dream of flying that fast through the skin with a skin like Fuse.

I'm mentioning this because I would like it that when we talk about adding something to Nimbus, we discuss the feature itself, not where it came from. When you say you could do this or that like Fuse, it immediately closes my mind to it because I'm very conscious about each feature/setting I add to my skins and I don't necessarily want to implement a feature directly from a skin that I consider to be heavy. When I implement something, I think of the lowest powered device and I think to myself, "Would adding this feature still provide a smooth experience for said device?" If the answer is no, I skip it. This is why I don't have TMDbHelper in my skins. Any of the functionality I've needed from TMDbHelper, I've coded myself into the Nimbus Helper. 

Now that we got that out of the way, 

> when you hover over the audio/subtitles icon it will kind of pop up the available audio and subtitles tracks available, if there are multiple available. And the audio tracks displayed at glance will also show if they have different codecs.

I don't like the idea of this design. It would be obtrusive to to the viewing experience which is why I prefer cycling through the subtitles/audio tracks. I feel like it's much cleaner this way. This is partly why the OSD in Nimbus is so minimal.

However, I do understand not wanting to cycle through audio tracks/subtitles as sometimes the list can be large so I've implemented an option to choose what you want the audio/subtitle button to do. It'll be added to the OSD section in Skin Settings for next update. I could only find online how to enter the audio settings/subtitle settings dialog. If you can find how to directly enter the available audio tracks/subtitles, I'll implement that instead.

**Comment by Nuklear92** [comment]
Heheh! Yeah, no doubt AF is a big featured packed skin. An I do had noticed performance issues, mainly when you're watching content and you try to open the player's OSD. Most of the time, if not always it will make the video stutter. I wish the current Nvidia Shield Pro 2019 was even more powerful regarding handling of skins, hopefully **if** they ever release a new version which I highly doubt these days they will be doing that. As Nvidia as a company has moved themselves deeply into the A.I stuff and mainly to their core products like Graphics Cards, etc.

And as for the audio/subtitles part, that's fine if you implemented an optional toggle to make the icons from cycling on the tracks to opening option dialog for the user to choose manually. Much preferable, as you only have to open the option once and directly select the best audio track and subtitles if the source has multiple to choose from and sometimes the default chosen when you first start the video aren't the desired. 

Appreciate that added option. And thanks for the information about your approach for your skins, which is definitely why many people love them. It keeps stuff minimal but with some beauty involved while also maintaining a balance in performance. Which many people with low powered devices look for when moving away from the default estuary Kodi skin.

**Comment by ivarbrandt** [comment]
>  I wish the current Nvidia Shield Pro 2019 was even more powerful regarding handling of skins

You and me both. Plus Kodi wasn't originally coded to be used on Android devices. It was designed for PC. It was poorly ported to Android and that's why we see sooo many issues with non-PC based devices.

There's always the option to completely remove widgets, auto start the addon on Kodi launch, and just use it like that. I find myself doing that quite a bit as when I do that, Nimbus just BURNS through the menus like it's nothing because it can allocate everything it has to that instead of having 20+ widgets loaded in the background. Trailer functionality also benefits from this approach as there is no need to reload the widgets after a trailer. The design and artwork options are the exact same for the widgets as they are for addons so you don't lose anything going this route.

> And thanks for the information about your approach for your skins

Thank you for understanding and respecting where I'm coming from. I didn't realize that I needed to get that off my chest so it's pretty cool that you took it well. I appreciate that.

**Comment by ivarbrandt** [comment]
Heads up, I cooked up an optional alternate OSD. It'll be in the next update.

**Comment by ivarbrandt** [comment]
I've cooked up an alternate OSD. It will be available in the next update.

**Comment by Nuklear92** [comment]
> I've cooked up an alternate OSD. It will be available in the next update.

Interesting! Can't wait to see it hehe! 😜 you could've shared a screenshot. Is it still in active development and in subject for any changes or it's finished already? 

And does it maintain the same performance as the current OSD that when you request it, it won't make the video playback stutter like AF and AH skin does? 🤔

**Comment by ivarbrandt** [comment]
> You could've shared a screenshot. Lol you're right.

![Screenshot_20240811-075118](https://github.com/user-attachments/assets/720de98e-b3a8-4174-9eb8-8c07768cd04c)
![Screenshot_20240811-075821](https://github.com/user-attachments/assets/5239a48c-e541-4bd2-9179-05269adc8e00)

> Is it still in active development and in subject for any changes or it's finished already?

It's pretty much finished but I'm open to feedback. 

> And does it maintain the same performance as the current OSD that when you request it, it won't make the video playback stutter

I didn't detect any stuttering. Wasn't really looking for it though so I'll keep an eye out for that behavior.

**Comment by Nuklear92** [comment]
@ivarbrandt Whoa! This really looks cool. I'll definitely have to use for for a while in order to come up with any feedback depending if I find any glitches, etc. but so far it looks like a big upgrade at a first glance!

Does this upgrade applies also to when you open "Player Process" the option that shows you technical audio Media info like channel count, bitrate, System processor info, etc. if you know what I'm talking about?

**Comment by ivarbrandt** [comment]
> if you know what I'm talking about?

I don't. Audio and video codecs along with audio channels will be displayed at the bottom.

**Comment by Nuklear92** [comment]
@ivarbrandt Hey! This is a different topic but. I wanted to share some nice icons that I found that could better represent TV Show status, since I saw that you have changed them however they seem kind of confusing with the leaf, sunset, etc.

Idk how these would look implemented but just wanted to share them as I found them on google. Perhaps what will make them look better is if the calendar shape wasn't black as it could get lost in with the black ground colors. But, this is so you have an ideas 💡 of how to better represent each TV Statues;

![image](https://github.com/user-attachments/assets/98f6bb5e-a292-48ab-a7cd-4cff899669e1)

**This one ☝️ would mean if a TV Show still hasn't announced a new season and it's in between a renewal or getting cancelled**

![image](https://github.com/user-attachments/assets/6dc1ce30-4d62-466a-88e1-e234e5d67d16)

**This one ☝️ would represent when a TV Show gets renewed for a new season**

![image](https://github.com/user-attachments/assets/c9dc6ee2-89ed-4347-9c08-60816392231e)

**This one ☝️ would represent if a TV Show has ended/completed with a final season**

![image](https://github.com/user-attachments/assets/b8fcf230-c9d6-4963-878e-56dd7720c6c3)

**This one ☝️ would represent if a TV Show gets cancelled**

I have no experience in building icons, but I wanted to share these ideas of how you could better represent each TV show status so it's less confusing for users. 👍

**Comment by Nuklear92** [comment]
> > if you know what I'm talking about?
> 
> 
> 
> I don't. Audio and video codecs along with audio channels will be displayed at the bottom.
> 
> 

I see, I'll share a screenshot to show you what I mean in a minute. 😅

**Comment by ivarbrandt** [comment]
> but I wanted to share some nice icons that I found that could better represent TV Show status

No thanks. I like the icons I chose.

> I was talking about which is called "Media Processes" when you look at it in something like the Keymap Editor add-on

I see. I don't use that screen so I won't be changing it.

**Comment by npmstart-pray** [comment]
> @ivarbrandt Hey! my apologies for changing topics briefly, but I wanted to share some nice icons that I found that could better represent TV Show status, since I saw that you have changed them however they seem kind of confusing with the leaf, sunset, etc.
> 
> Idk how these would look implemented but just wanted to share them as I found them on google. Perhaps what will make them look better is if the calendar shape wasn't black as it could get lost in with the black background colors. However, this is so you have an idea of how to better represent each TV Statues;
> 
> ![image](https://github.com/user-attachments/assets/98f6bb5e-a292-48ab-a7cd-4cff899669e1)
> 
> **This one ☝️ would mean if a TV Show still hasn't announced a new season and it's in between a renewal or getting cancelled**
> 
> ![image](https://github.com/user-attachments/assets/6dc1ce30-4d62-466a-88e1-e234e5d67d16)
> 
> **This one ☝️ would represent when a TV Show gets renewed for a new season**
> 
> ![image](https://github.com/user-attachments/assets/c9dc6ee2-89ed-4347-9c08-60816392231e)
> 
> **This one ☝️ would represent if a TV Show has ended/completed with a final season**
> 
> ![image](https://github.com/user-attachments/assets/b8fcf230-c9d6-4963-878e-56dd7720c6c3)
> 
> **This one ☝️ would represent if a TV Show gets cancelled**
> 
> I have no experience in building icons, but I wanted to share these ideas of how you could better represent each TV show status so it's less confusing for users also they look minimalistic and simple yet effective to their meaning. 👍
> 
> **Edited:** in any case you want the website where I found them, which is strictly a icons for sale website I can provide the link, or the link for each icon directly within the website. 

As a user, I'd prefer to see that info in text rather than having to look up what an icon means. Let's not get all emoji, please; just because we can doesn't mean we should.

**Comment by ivarbrandt** [comment]
> As a user, I'd prefer to see that info in text rather than having to look up what an icon means.

Me too. But it didn't fit anymore after the changes I made. 
'Look up' is a stretch. One glance at the changelog and you'll know what they mean.
