### ISSUE TITLE
[Issue] Unsupported media views for anime add-on Otaku

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.nimbus#23]
Hello, again. I'm not sure if this issue fix will have to be via the add-on's developer or you the skin's developer. Either way I'll also tag his username after I explain the issue below.

So, It seems like all those new media views you have added recently including **FlixScape**, **FLIX**, **WallScape**. Look weird and **unsupported within the Otaku add-on** specifically in the Episodes section. **The add-on seems to work fine with every other skin I have installed and their media views, besides Nimbus**. So, I wanted to report this issue so It can be resolved and hopefully the add-on gets fully supported with the skin so myself and any other current and future users of this skin that might happen to use this add-on also enjoys it as it should without encountering themselves with these media view's inconsistencies.

Here are some screenshots and I'll also include a short video clip of all the media views within Episodes and how they compared to an addon like FEN in this example but can also apply to TMDb Helper as well as they all display the newly added media views in Episodes correctly.

Here's the **WallScape** view within **Otaku**
![Kodi_20240720_092306](https://github.com/user-attachments/assets/39e7b5f3-03dc-4120-8118-f952ec593fef)

Here's **WallScape** within **FenLight**, this is the correct way.
![Kodi_20240720_092406](https://github.com/user-attachments/assets/7b34a01a-b5c0-4b84-b361-acfc1cadf562)

Here's **FlixScape** view within **Otaku**.
![Kodi_20240720_092245](https://github.com/user-attachments/assets/8be9a352-763b-4040-8d9c-dc517a01d7b2)

Here's **FlixScape** within **FenLight**, this is the correct way.
![Kodi_20240720_092358](https://github.com/user-attachments/assets/861744b0-6817-426f-b8d1-d8849713ab60)

Here's the short video clip showing the issue and difference between both add-on quickly, this link in particular will expire after 2 days, just in case it doesn't work at the time you check it out.

https://streamable.com/covtfs

So, hopefully this can be fixed/adjusted so the Otaku add-on is fully supported with this skin. Let me know if this has be fixed from the add-on developer side or if you can fix this yourself. Either way I'll tag him below in a separate comment, so he can check the issue too.

**Comment by Nuklear92** [comment]
@Goldenfreddy0703 Hey, sorry to bother. I was just tagging you in hopes that you can also read out this issue with Otaku with the skin **Nimbus**, I already mentioned within the description that I was going to tag you in. Because, i'm unsure if the issue related to the skin developer or otaku's developer in relation for a solution/fix. So, if this is fixable by you let me know and I can close this issue here or if this is related to the skin developer i'll leave it open so it can be resolved from his side.

**Comment by Goldenfreddy0703** [comment]
Hey so I was actually unsure as well, on fentastic, many users had problems with utilizing widgets with Otaku if I recall and there widgets were square and not poster or landscape for some odd reason so this might have something todo with nimbus sense it was made by same developer but I'm not too sure yet, if anybody could test Seren and see if it's happening there, that would be great so we know that it could be mainly an Otaku issue. I have not had any issues from any other skin except with Fentastic in the past.

**Comment by ivarbrandt** [comment]
It definitely looks like its on my end but I can't tell because the artwork is different in most of your screenshots.

In the first screenshot you're using a poster items and comparing it to landscape items. Use WallScape for both then let's see a screenshot.

The second pair of screenshots is what Nimbus displays when it doesn't have the main artwork it needs for that view so that's what it falls back to.

I'll download Otaku and take a look though. Cause that does look bad lol.

**Comment by Nuklear92** [comment]
> It definitely looks like its on my end but I can't tell because the artwork is different in most of your screenshots.
> 
> 
> 
> In the first screenshot you're using poster items and comparing them to landscape items. Use WallScape for both then let's see a screenshot.
> 
> 
> 
> The second pair of screenshots is what Nimbus displays when it doesn't have the main artwork it needs for that view so that's what it falls back to.
> 
> 
> 
> I'll download Otaku and take a look though. Cause that does look bad lol.

Please, and thank you! I've tried even reinstalling the addon hoping it was glitched or something and the media views still look the same **only** when viewing Episodes.

**Comment by Nuklear92** [comment]
> Hey so I was actually unsure as well, on fentastic, many users had problems with utilizing widgets with Otaku if I recall and there widgets were square and not poster or landscape for some odd reason so this might have something todo with nimbus sense it was made by same developer but I'm not too sure yet, if anybody could test Seren and see if it's happening there, that would be great so we know that it could be mainly an Otaku issue. I have not had any issues from any other skin except with Fentastic in the past. 

The developer of the skin is going to download the addon and double check if he can replicate the issue in hopes for a fix. I'll keep you posted or if you can manually check back on this issue to see if it has been resolved or it might need your assistance. 👍

**Comment by ivarbrandt** [comment]
> Please, and thank you! I've tried even reinstalling the addon hoping it was glitched or something and the media views still look the same only when viewing Episodes.

Nah it's def Nimbus. I have it too restrictive on what artwork it allows. I'm in the process of fixing it.

**Comment by Nuklear92** [comment]
> > Please, and thank you! I've tried even reinstalling the addon hoping it was glitched or something and the media views still look the same only when viewing Episodes.
> 
> 
> 
> Nah it's def Nimbus. I have it too restrictive on what artwork it allows. I'm in the process of fixing it.

Oh, great! 😃🙏


@Goldenfreddy0703 so the developer of the skin will be fixing the issue. Thanks again, for checking the issue when I tagged you. ❤️

**Comment by ivarbrandt** [comment]
Alright I fixed all the landscape artwork and gave the posters and menus a clean up. 

If for some reason any item falls back to that layout with the text, it's cause there isn't any art available. I also recommend using anything but Flix for episodes. Even then, it won't look as bad as it did before.

Changes will be up later tonight or tomorrow.

**Comment by Nuklear92** [comment]
> Alright I fixed all the landscape artwork and gave the posters and menus a clean up. 
> 
> 
> 
> If for some reason any item falls back to that layout with the text, it's cause there isn't any art available. I also recommend using anything but Flix for episodes. Even then, it won't look as bad as it did before.
> 
> 
> 
> Changes will be up later tonight or tomorrow.

Awesome! I'll be waiting to check it out and I'll report back. 👍

**Comment by ivarbrandt** [comment]
`0.1.14` is up.

**Comment by Nuklear92** [comment]
> `0.1.14` is up.

Yup! I just installed and checked it out. Now it displays episode artwork as the other add-ons. You're the man! Thanks a lot for the quick fix. 😃❤️

@Goldenfreddy0703 just a heads up, the developer released a new update for the skin fixing the artwork issues, now Otaku works perfectly with Nimbus!

**Comment by ivarbrandt** [comment]
Awesome! You're welcome. Glad I could help.
