### ISSUE TITLE
Double Clearlogo toggle in view options

### ISSUE THREAD

**Issue by meesterexx** [ivarbrandt/skin.nimbus#24]
Loving all the updates recently, looking great!
You may already be aware of this, or maybe I'm not understanding something, but there's 2 Clearlogo toggles in view options:

![Screenshot 2024-07-20 104747](https://github.com/user-attachments/assets/3fad1576-6dc0-4341-b4d5-3553c567d394)

Thanks again for the constant innovation on this skin!

**Comment by ivarbrandt** [comment]
Hey good to hear from you!

Good catch! I didn't notice that. The bottom toggle is for the Clearlogo in list view. I'll get that fixed.

**Comment by ivarbrandt** [comment]
Fixed for `0.1.14`
