### ISSUE TITLE
any chance I can convince you

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#25]
I thought it's worth trying to fight for it, please close the issue if I've gone to far.
<img width="1280" alt="Screenshot (96)" src="https://github.com/user-attachments/assets/ca0ce169-e086-4c80-aebf-1b3ffa93f4a6">
 compared to

![Screenshot (97)](https://github.com/user-attachments/assets/4754295e-039e-433d-8064-db9c56cc4436)

the way the concept skin works is. those mini posters won't be cut off but you'll have 3 by 2 posters on left side.
it starts top left. pressing down selects the item below it. once you have completed the collumn it will start at the top of the second collumn. once you finished that collumn a new grid of 3 by 2 items will load.

You can also press right/left to hop collumns

if you want to quickly go through the posters you can press right to access the scrollbar and you can scroll through 6 items with one click in poster view.

You don't need title image since you have it baked inside the poster and the poster is so big too. some movies don't even have a title image but the poster always has one.

In the view I have you are literally only missing 6 movies, but each movie has full genres, much more plot, you get more immersed in looking at poster to see what the movie is about. it's a better way to browse imho

I believe nothing beats poster view. movie companies spend time and resources on poster. and having it centre draws your eyes their.
if you like the poster, you can very easily do side glance at the plot. we can fit more in plot using this view

you can even reduce the size of the poster some what, add in your diffuse elements from Nimbus but the general concept, what do you think of it? I think so many will fall in love with it. I've seen myself click the trailer button more on this massive poster view than any other view. 
also a good benefit of this view is if someone has animated posters, it would be awesome to have them as big as possible in the centre

Also you have seen some of my creative concept work which you have liked, maybe I might have something here? I'll understand you don't have time to devote to a creating a new view type but if you think it has merit I hope you can consider it for future release. Thanks

**Comment by hcgiub001** [comment]
<img width="1280" alt="Screenshot (96)" src="https://github.com/user-attachments/assets/0ebfb0c9-1e6f-4220-ab53-7a0a03530215">
using design elements from Nimbus makes skin nicer, like blur background blur effect

**Comment by ivarbrandt** [comment]
I don't like that view. However, I added a poster option to the List view for the next update. It will contain a bigger poster.

**Comment by hcgiub001** [comment]
yay looking forward to it! thanks :)

**Comment by ivarbrandt** [comment]
It will look like this:
![Screenshot_20240725-184204](https://github.com/user-attachments/assets/76802079-6bbf-40d8-8f39-010572a51d7f)

**Comment by hcgiub001** [comment]
okay my honest opinion, it looks sweet, I prefer it over the previous listview. now for my constructive criticism 
(this is in no way trying to push for this view)

for context this is how I have it set ( I modified the image size)

![Screenshot (105)](https://github.com/user-attachments/assets/399206c6-c4b8-4823-9cb5-f1de3dac8fd9)

When I go through my list my eyes are on the poster. I don't bother looking at the list or plot. If I like the poster I glance at the genres, then quickly at the ratings and the plot.

I have full plot even though I use much bigger font. I have much bigger poster. and more movies.
it flows nicely. 

with your new listview, the way I see is you have designed so people focus on the title on the left? then have a quick glance at the poster? then back at the plot? they then have to load up extra menu just to read the full plot. The plot also moves down with the title so you are constantly having to mentally adjust where you think the plot should be.

Or maybe I'm not understanding where you want us to look. their is so much wasted space, if you had the same background over my layout, with nicer fonts and better font size, I think it would not only look better but way more functional.

I much prefer your updated poster view. I really hoped I could make you see from my perspective, for those who value poster size, the way I stumbled on my viewpoint is so ideal. I wanted to jump on Nimbus because It's more modern but I'm not sacrificing on functionality. I do think it's a nicer look though and I appreciate you doing this.

**Comment by hcgiub001** [comment]
sorry just to add. your list view is more cluttered , it takes more mental effort to distinguish the titles from the plot, and I don't see any reason for it. it's much easier to do the same thing over again than it is to mix. If I want to look at titles. it's on the left third. If I want the plot it's on the right portion. I don't need to know the title name because the poster is so big that you basically got a title image inside the poster. 

I only look at the title if I want to quickly find a movie. then I have no need for poster view or plot.
It would be nice If I had skinning knowledge lol but you don't understand how much I love your fentastic! Hope that stays alive for a few years haha
