### ISSUE TITLE
Mdblist api key invalid after last update 

### ISSUE THREAD

**Issue by bogdanmatara** [ivarbrandt/skin.nimbus#26]

**Comment by ivarbrandt** [comment]
The new API key validator only accepts valid MDbList API keys. If you already had an API key entered into the settings before this last update, it should automatically transition you to the new validator system when the home screen is loaded. If it doesn't, try reentering your key. If that doesn't work, let me know and I'll look further into it.

**Comment by bogdanmatara** [comment]
Re-added, still invalid. Generated a new key, still invalid.

**Comment by ivarbrandt** [comment]
K go and hit enter again to trigger the validator and send me the log

**Comment by bogdanmatara** [comment]
Good idea, I’ve checked the log. I was on wrong nimbus helper. Updated the helper to the last version and all is good now. Thanks for your time and thanks for the best Kodi skin ever (I am using kodi for more than 10y now :) )

**Comment by ivarbrandt** [comment]
> I was on wrong nimbus helper.

That's the first thing I was going to check in your log lol. Glad you got it working. 

Thank you for the kind words.
