### ISSUE TITLE
Mdblist Invalid API Key

### ISSUE THREAD

**Issue by jorgitoxp** [ivarbrandt/skin.nimbus#27]
Hi there,

not sure if it was after the last update but I no longer see ratings.  When I go to the ratings management section it shows INVALID API KEY.  I’ve recentered it, even created a new app key, but it still shows invalid as soon as it’s entered.  

I even cleared cache in Kodi and re entered the key but no matter what it just keeps showing invalid.  I saw few others posts on Reddit mentioning this same issue.

thanks let me know if anything from me is needed. 
![IMG_4300](https://github.com/user-attachments/assets/aff495f8-bbc2-4fe3-895a-eff9631541cd)

**Comment by ivarbrandt** [comment]
Did you update the helper?

**Comment by jorgitoxp** [comment]
> Did you update the helper to the latest version, `0.0.36`?

I have not.  Normally I don’t even touch the skin, I just let it update automatically.  I’m going to try to see how to find the helper to see if I can update it . I’ll keep you
Posted . Thank you so much for the quick reply and for the amazing skin.

**Comment by jorgitoxp** [comment]
> Did you update the helper to the latest version, `0.0.36`?

I can’t get it to update nimbus helper.  When o click on dependencies it shows I’m running version 0.0.29, and when I click on versions for nimbus skin to download it again, it mentions that the new helper needs to be installed first.  I click yes but it does not install the new version.  When I check dependencies it still shows I’m running .29.  Not sure how to force update the helper to the new version.

**Comment by ivarbrandt** [comment]
Go to Settings > Addons > My addons > Look and feel > Skin > Nimbus > Dependencies > click Nimbus Helper > Versions > click 0.0.36 and it will install

Alternatively, Settings > System > Addons tab > Manage dependencies > scroll to Nimbus Helper > Versions > click 0.0.36 and it will install

Then go to the home screen, if you have an API key already entered in, it will auto validate it for you upon entering the home screen. If not, go enter it in Skin settings and validation should work.

**Comment by jorgitoxp** [comment]
> Go to Settings > Addons > My addons > Look and feel > Skin > Nimbus > Dependencies > click Nimbus Helper > Versions > click 0.0.36 and it will install
> 
> Alternatively, Settings > System > Addons tab > Manage dependencies > scroll to Nimbus Helper > Versions > click 0.0.36 and it will install
> 
> Then go to the home screen, if you have an API key already entered in, it will auto validate it for you upon entering the home screen. If not, go enter it in Skin settings and validation should work.

That did it.  You are the best!  Thank you so much for taking the time to walk me through fixing my issue.  Love your work and your support.

**Comment by ivarbrandt** [comment]
You're welcome. Glad you were able to get it all figured out :)
