### ISSUE TITLE
bug: automatic trailers

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#28]
two bugs identified on my system.

I have automatic trailers on

1/ if a trailer loads for one movie, and I press right or left to change to another movie, the trailer will stop but the trailer 
for the movie I just pressed won't come on. If I press another left or right, it will come on for that selection. then the behaviour repeats.

2/if a trailer is on for a movie and I press down to bring up the posters view of movies, the trailer doesn't stop but carries on, then if I pick another movie, the trailer is still set to the old one and is still playing. their will be no plot showing on this new movie with previous trailer. If I press right or left now, it will close the trailer but again behaviour 1 happens, no trailer will play for that first left/right click

thanks

**Comment by hcgiub001** [comment]
I'm not sure if this is by design but I have selected a key to load trailers.
If I load a trailer on a movie and press down for poster view, the trailer carries on.
I would have assumed it will stop playing. since I can't really see the trailer and if I have hovered over a different movie then the trailer still is playing.
thanks

**Comment by ivarbrandt** [comment]
1. Thanks for reminding me. I've been meaning to fix this.
2. This isn't really a bug as it's designed this way. I didn't think that users would suddenly go into the wall view while watching a trailer.

**Comment by hcgiub001** [comment]
no worries. the automatic trailers are cool.

**Comment by ivarbrandt** [comment]
Yeah I agree with you. 1 and 2 are fixed for next update.
