### ISSUE TITLE
Bug. opening a collection, loading trailer, pressing back

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#29]
I've enabled in Fen
- open movie collections Instead when available 

in the collection page once a trailer loads and I press backspace, I return to back to my previous page which is what I want.
but the trailer is still playing.

expected result - return back to previous page and the trailer stops

this makes more sense, thoughts? thanks

**Comment by ivarbrandt** [comment]
Fixed for next update.
