### ISSUE TITLE
Kodi 21 bèta 2

### ISSUE THREAD

**Issue by djdirty60** [ivarbrandt/skin.nimbus#3]
Good day,

When does nimbus work on Kodi 21 beta 2?

Thanks in advance for your hard work and beautiful skin

**Comment by meesterexx** [comment]
I'm running it on 21b2 here:
![21b2](https://github.com/ivarbrandt/skin.nimbus/assets/13154733/b1d876e7-b2d2-4c55-a681-1a9c29dd4337)

**Comment by djdirty60** [comment]
Here it is no longer to use, or to install

**Comment by meesterexx** [comment]
Are you by chance using a nightly of beta2? Anything past the original beta 2 won't work yet due to changes in the ABI:
https://forum.kodi.tv/showthread.php?tid=375334&pid=3174988#pid3174988

**Comment by ivarbrandt** [comment]
> When does nimbus work on Kodi 21 beta 2?

Probably not for awhile. I'll be taking the same approach as FENtastic when it comes to Omega compatibility.

It'd be pointless to provide you with a zip though since Nimbus is still in development.

**Comment by djdirty60** [comment]
> > When does nimbus work on Kodi 21 beta 2?
> 
> Probably not for awhile. I'll be taking the same approach as FENtastic when it comes to Omega compatibility.
> 
> It'd be pointless to provide you with a zip though since Nimbus is still in development.

Misery 😔
