### ISSUE TITLE
Translation Extras Page

### ISSUE THREAD

**Issue by xavengedx** [ivarbrandt/skin.nimbus#31]
Hello bro, your Nimbus skin is without a doubt the best I've ever tested among them all! And I always see new updates, the option to enable it to open the audio and subtitle configuration is amazing! I'm from Brazil, and I would like to have the option to translate the options on the films/series extras page, is there a way to add this option? I'm using the POV Addon, which works very well and I can put its language in Portuguese. If it had this option to translate the extra page, it would be wonderful.

 Thank you very much in advance for the great work!

**Comment by ivarbrandt** [comment]
This isn't something that is skin related. Contact the POV developer for translation of the extras page.
