### ISSUE TITLE
[Ideas] for missing meta information on titles in the Information tab

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.nimbus#32]
Here are some ideas I thought about that could be useful information which titles are missing in general when you navigate to the context menu "Information tab". I also show useful area where they could be incorporated, IF of course after you read the whole thing you think it's not actually a bad idea.

**Heads up!** for reference I'll be using some screenshots comparison from Arctic Fuse, to better represent the **key** information that's currently missing with Nimbus and perhaps be added with the help of Nimbus Helper which I believe it's your equivalent version more toned down of TMDb Helper. Please, correct me this is not the same. I compare it since I think this is where you get the meta information that Nimbus currently provides.

Okay, here we go. As you will see below, currently when looking into Movies/TV Shows you might notice that you only have a standard release date which is year only and even though it's not bad. Still, it could be more useful if it could be switched to be more accurate in the format of "mm/dd/yyyy". 

<img width="1440" alt="Screenshot 2024-07-31 at 10 08 25 AM" src="https://github.com/user-attachments/assets/005a2748-4e24-4332-883e-6b4adcb41cd5">

Here is how it currently looks, as you see it every title only says the year of release and not the exact date. Look at the arrows for studio logo re-placement reference in both screenshots.

<img width="1440" alt="Screenshot 2024-07-30 at 10 14 31 AM" src="https://github.com/user-attachments/assets/e7f8454a-8ead-498b-8ee7-973f55998679">

For reference, here's how it looks in Arctic Fuse, also the same in Arctic Horizon. Not too difference of an implementation, only more accurate info which what we look for. Also, the other arrows is to show you where the studio logo is placed in that skin and potentially where you could move it in case spacing is an issue to fit the slightly longer release date.

Now, moving to the **context menu Information** tab. Here are some key information that you could potentially add and the space is already available, well just me silly guessing as I have no clue how skinning works and measured space, gaps, etc. to fit information. However, I kinda made some rectangular shapes where I believe some extra info could fit when navigating to that tab which currently has **very limited info** from titles in general and it should be good to have a more in-depth look of useful things at a glance like;

For Movies: **Director**, **Writer**, **Studio**, **Budget/Revenue**, **Accurate Release Date**.

<img width="1440" alt="Screenshot 2024-07-30 at 10 15 26 AM" src="https://github.com/user-attachments/assets/41dc06a6-b5e1-43cf-a057-6c0a7af7d904">

As you see here, I marked with arrows exactly the key useful information that should be available at a first glance when navigating to the context menu **Information** for any title if the user wish to know a little more about the movie in general. I know this information could be easily seen if you're using an add-on like **FEN** or **FENLight** and their **Extras** in Context menu. However, I specifically going more with the **Information**  tab since this is the general tab for any add-on in general specially those that doesn't have an Extras section like, Seren, or maybe any other related streaming add-on out there that would rely to the information that's available within that tab.

<img width="1440" alt="Screenshot 2024-07-30 at 9 59 21 AM" src="https://github.com/user-attachments/assets/350ff567-2912-4089-ade6-1ec8c9ac1ffb">

Here as you can see this is the only information you get from a title, I marked two rectangular shapes where I believe this information might look good at a first glance. 

For TV Shows: **Creator**, **Writer**, **Studio**, **Next Episode**.

<img width="1440" alt="Screenshot 2024-07-30 at 10 31 21 AM" src="https://github.com/user-attachments/assets/c13638b2-6e14-49d5-9af1-8c5db0f9ba44">

Here using Arctic Fuse again for reference, I pointed with arrows the Key information that I believe could be useful to know at a first glance when you navigate to the context menu **Information** for TV Shows.

<img width="1440" alt="Screenshot 2024-07-30 at 10 27 56 AM" src="https://github.com/user-attachments/assets/65d9d224-36d4-49bc-9ecb-8ca90af1b1f5">

And as you can see this is all the information we get currently on Nimbus, again I marked with rectangular shapes two areas where I believe this information could look nice if added. 

In conclusion, I want to make sure and specify this is **not** asking you for any feature requests neither something to be rushed. I wanted to create this issue more for you to see if in the future you plan to add any more information for titles, this is what I think it should be extra useful for users to see. I'm not a fan of overly crowding an information tab like those skin do, which is why I only picked 4 specific extra information for TV Shows and 5 Movies that are key. Other things like, Artworks, Reviews, recommendations, similar, etc. for me that just puts extra resource on a skin.

I hope you made it through here, before closing the issue hehe! I wonder what are your thoughts in these ideas?.

**Edited**: Hey! My mistake with the logo arrangement and the available space within the information tab below the poster. I took these screenshots from my laptop inside Kodi and it made it look like there was larger gap between the poster and bottom area. However, after looking it on my TV the space is smaller. But! For the studio logo, the arrow that points it out towards the right edge of the FanArt that space does look available similar as the screenshot while seeing it on the TV screen. 

As well as for the information tab the rectangular space below the title plot, that space seems to be available as I kind of did it in the screenshot while seeing the information tab on the TV screen.

My apologies, I didn't kind of verified that until recently that I got home and double checked if the spaces were the same as in the screenshots while seeing it on the TV Screen. 😅

**Comment by ivarbrandt** [comment]
> I compare it since I think this is where you get the meta information that Nimbus currently provides.

I get the ratings from the helper. But I do not have TMDb integrated into the helper.

> Still, it could be more useful if it could be switched to be more accurate in the format of "mm/dd/yyyy".

I agree. But if I change it to the full release date, studio logos will have to go.

> Now, moving to the context menu Information tab

I'll think about this. I can't access all the info you mentioned as I don't have TMDb integrated into the helper. Also, if I do add it in, it would be added to a separate tab under Cast.

**Comment by Nuklear92** [comment]
> > I compare it since I think this is where you get the meta information that Nimbus currently provides.
> 
> 
> 
> I get the ratings from the helper. But I do not have TMDb integrated into the helper.
> 
> 
> 
> > Still, it could be more useful if it could be switched to be more accurate in the format of "mm/dd/yyyy".
> 
> 
> 
> I agree. But if I change it to the full release date, studio logos will have to go.
> 
> 
> 
> > Now, moving to the context menu Information tab
> 
> 
> 
> I'll think about this. I can't access all the info you mentioned as I don't have TMDb integrated into the helper. Also, if I do add it in, it would be added to a separate tab under Cast.
> 
> 
> 
> 
** I agree. But if I change it to the full release date, studio logos will have to go.**

Not necessarily, if you look at the very first screenshot I shared there's one position I marked with the green arrows which is pretty much at the right edge of the FanArt which I don't think will look that bad, plus you can even make the icon a tiny bit bigger so it looks cooler. But, that's just a silly idea of mine. Perhaps you won't see it the same way as it might look obstructive to the FanArt itself. 🤷‍♂️

** I'll think about this. I can't access all the info you mentioned as I don't have TMDb integrated into the helper. Also, if I do add it in, it would be added to a separate tab under Cast.**

I understand, I meant it to be when you open the information tab as you'll have those extra info at a first glance, instead of having to scroll to another section. However, either way I think is cool as I believe more information is good from titles in general, specially when you navigate to the information tab within context menu as it's the place you go if you want know more in-depth about a particular movie and tv show before watching, etc. 👍

Anyways, you can take as much time as you need to think about your own unique implementation of this in the future. I just wanted to share some ideas of how I imagined it would be, of course maintaining the most minimalist aspect as possible 😅.

**Comment by ivarbrandt** [comment]
> Perhaps you won't see it the same way as it might look obstructive to the FanArt itself. 🤷‍♂️

Bingo. I want to keep the lower bezel of the fanart clear as the InfoLine stretches all the way to the other side of the screen underneath the fanart. Also, I'd like all information to remain in one place. That way users aren't going cross eyed when looking at the studio logos then back to the main info.

But you know it not a big deal if I remove the studio logos as I've been pondering it for awhile. They aren't maintained so there's a lot of empty ones. If I add them back in it'll be my own custom set of studio logos.

> I understand, I meant it to be when you open the information tab as you'll have those extra info at a first glance, instead of having to scroll to another section

I tried this and it didn't look very good so I opened up a new tab instead. There's not as much room below the poster as your pictures showed (maybe you were on your PC) and adding the info there made it look cluttered.

Here is what it'll look like for next update:

![Screenshot_20240802-202408](https://github.com/user-attachments/assets/74c45e17-fa4d-4947-9e26-7cf2b78b4999)

![Screenshot_20240802-202415](https://github.com/user-attachments/assets/76e1d75c-dcc8-464c-a209-bf24bcbca072)

**Comment by Nuklear92** [comment]
> > Perhaps you won't see it the same way as it might look obstructive to the FanArt itself. 🤷‍♂️
> 
> Bingo. I want to keep the lower bezel of the fanart clear as the InfoLine stretches all the way to the other side of the screen underneath the fanart. Also, I'd like all information to remain in one place. That way users aren't going cross eyed when looking at the studio logos then back to the main info.
> 
> But you know it not a big deal if I remove the studio logos as I've been pondering it for awhile. They aren't maintained so there's a lot of empty ones. If I add them back in it'll be my own custom set of studio logos.
> 
> > I understand, I meant it to be when you open the information tab as you'll have those extra info at a first glance, instead of having to scroll to another section
> 
> I tried this and it didn't look very good so I opened up a new tab instead. There's not as much room below the poster as your pictures showed (maybe you were on your PC) and adding the info there made it look cluttered.
> 
> Here is what it'll look like for next update:
> 
> ![Screenshot_20240802-202408](https://private-user-images.githubusercontent.com/54084201/354787156-74c45e17-fa4d-4947-9e26-7cf2b78b4999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTQ4MDksIm5iZiI6MTcyMjY1NDUwOSwicGF0aCI6Ii81NDA4NDIwMS8zNTQ3ODcxNTYtNzRjNDVlMTctZmE0ZC00OTQ3LTllMjYtN2NmMmI3OGI0OTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAzMDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOTI0NGJkZTNhMWVhNTkyZTI5OGI2NDg2NDI0MWY2MTU1ZTljOGY3ZWMwNjQ5MGQzZjM4ZGJkMTIzYTBmNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hkNcs3soXCHrTq4cFj4c5LTZ84fHk_UFGf8hzE2tqus)
> 
> ![Screenshot_20240802-202415](https://private-user-images.githubusercontent.com/54084201/354787171-76e1d75c-dcc8-464c-a209-bf24bcbca072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTQ4MDksIm5iZiI6MTcyMjY1NDUwOSwicGF0aCI6Ii81NDA4NDIwMS8zNTQ3ODcxNzEtNzZlMWQ3NWMtZGNjOC00NjRjLWEyMDktYmYyNGJjYmNhMDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAzMDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZjI3OWY3MTg1NWQ4ZGY4ODUzYTVkNjFlZDY2M2Q3YzM5ZTMyNGNlOTgyMmU3YTNkZDA2NzM2M2FjMTA0NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q8hDXjUkaiYM_SU_4tM89FhT0BwOaW7jhCfMCJhM81g)

**Here is what it'll look like for next update:**

Hey! this actually looks great. Still keeping the same minimalistic aspect, I like it personally.

**But you know it not a big deal if I remove the studio logos as I've been pondering it for awhile. They aren't maintained so there's a lot of empty ones. If I add them back in it'll be my own custom set of studio logos.**

That would be awesome if you end up bringing your own custom set of studio logos! As I had noticed that too, that theres many titles that are in blank as if there wasn't a studio logo icon available for that particular movie or tv show title.

I was going to ask you as well about the **Trailer** tab within Information. Do you think that tab can become active, for example again if you look at the screenshot below. within the context menu Information from Arctic Fuse and this is the same in Arctic Horizon. when you scroll to the "Trailer" you get showed with all of the available trailers, teasers, clips, etc for that particular title. Of course, again this is from tmdb helper. But, I was going to ask you where do you pull your trailers from using Nimbus Helper? Because usually if you gather your data from tmdb as a source that means you can easily be picking up all the same extra trailers, teasers, clips, etc. As you know many movies and TV Shows sometimes have multiple trailers and sometimes clicking on the Trailer you never know if it will show you the Trailer 1 or 2 or Final Trailer or a Teaser. So, I believed it would've been nice if when you scroll to Trailer it will pop up all the available trailers, etc so the user can select which one they want to see if multiple are available. Or maybe do it like FEN Extras does that when you click Trailer it will pop up a dialog and let you select in a text form.

<img width="1440" alt="Screenshot 2024-08-02 at 11 06 09 PM" src="https://github.com/user-attachments/assets/7b7780c9-a245-4c02-9eb0-78b63f1cc38f">

**Here's how Arctic Fuse/Horizon will show it when you scroll to Trailer in Information within the context menu**

<img width="1440" alt="Screenshot 2024-08-02 at 11 26 42 PM" src="https://github.com/user-attachments/assets/562afd62-ad8a-4a53-88c3-f3823de0b2d9">

**Here is how FEN/FENLight does it if the title has multiple trailers, clips, extended previews, etc within Extras when you hit the Trailer button**

Whichever implementation you think will look cleaner or perhaps you might have your own unique way that would be awesome. But, again that's just in case your source of getting trailers is coming from tmdb, if you're getting your trailers from somewhere else that probably will only show one single trailer then you can leave it as it is.

**Comment by Jcloak** [comment]
Somebody has been doing their own maintenance for the studio logos in this thread. You can download the Textures.xbt file and replace the one in the add-on. It resolved almost all the missing icons for me.

https://forum.kodi.tv/showthread.php?tid=368342

**Comment by ivarbrandt** [comment]
> But, again that's just in case your source of getting trailers is coming from tmdb, if you're getting your trailers from somewhere else that probably will only show one single trailer then you can leave it as it is.

Yes I get my trailers from MDbList and they only provide one from TMDb. I won't make the trailer tab active but I did make the button active. So it'll work just like all other trailer methods.

> Somebody has been doing their own maintenance for the studio logos in this thread.

Nice find! I already removed all the studio logos from the skin though and I do think it looks cleaner. Plus like I said, I don't know where to put them.
![Screenshot_20240803-143408](https://github.com/user-attachments/assets/7da3ac79-8197-461e-b5aa-1e767928f2b6)

Thanks anyways and I'll keep that link in mind if I decide to add them back in.

**Comment by Nuklear92** [comment]
**Yes I get my trailers from MDbList and they only provide one from TMDb. I won't make the trailer tab active but I did make the button active. So it'll work just like all other trailer methods.**

Awesome! That's great if the button is active and it will should multiple trailers, if the Movie or TV Show has. 

About the Studio Logos, I was going to say you can also put the in the information tab in the meantime, somewhere you think it will look nice enough and also make them bigger.

**Comment by Nuklear92** [comment]
@ivarbrandt Hey, I just installed the new update. However, the Trailer button is not Active as you mentioned. And it's now picking up sneak peaks, or even movie clips when you click the trailer instead of showing the actual trailer. I tried with the Movie, Furiosa 2024, Horizon: An American Saga 2024, and Kingdom of the Planet of The Apes 2024.

Furiosa, will show an actual clip of the movie when you hit the trailer button. 

Kingdom of the Planet of the Apes, will show a Hulu digital release teaser that's like 30 seconds and not the actual movie trailer.

Horizon an American Saga, will show a "Get Tickets Now" 1 minute trailer which is mostly an Ad and not the official Trailer.

I thought when you said you made the Trailer button active, was similar to Fen Extras. That when you hit the Trailer button, if the movie or tv show title has multiple videos available, meaning teaser, trailer 1, 2 or Final Trailer as well as other sneak peaks, etc. Then, clicking the Trailer button will open up a quick dialog where you can manually choose what you want to watch, teaser, trailer 1, 2, final trailer, etc. as you can see on the screenshot I shared previously. 😅

**Comment by ivarbrandt** [comment]
> And it's now picking up sneak peaks, or even movie clips when you click the trailer instead of showing the actual trailer.

Make sure you have the the trailer source set to MDbList in Skin settings > Trailer setup.

> I thought when you said you made the Trailer button active, was similar to Fen Extras.

No, I said that I can't do that because MDbList only provides access to one trailer. I said that the trailer button now works like every other trailer method. Meaning it works the same way as when you play a trailer anywhere else in the skin, be it one-click or auto.

**Comment by Nuklear92** [comment]
> > And it's now picking up sneak peaks, or even movie clips when you click the trailer instead of showing the actual trailer.
> 
> 
> 
> Make sure you have the the trailer source set to MDbList in Skin settings > Trailer setup.
> 
> 
> 
> > I thought when you said you made the Trailer button active, was similar to Fen Extras.
> 
> 
> 
> No, I said that I can't do that because MDbList only provides access to one trailer. I said that the trailer button now works like every other trailer method. Meaning it works the same way as when you play a trailer anywhere else in the skin, be it one-click or auto.
> 
> 
> 
> Also, keep an eye on the changelog in the skin. In this case it doesn't have info about what we're discussing but otherwise it contains every change I make to the skin.

Gotcha! I double check that. But, I find odd that for trailers you don't rely on TMDb directly as a source not TMDb helper. As they usually pack more trailers and that way the user can select manually which trailer in specific they want to watch that's the source Fen extras uses and you can see that usually you get more options also TMDb tends to get fast updates when it comes to all things metadata compared to IMDb. 🤔
