### ISSUE TITLE
Diamond Info_MOD skin integration

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#34]
I used to use this back in the days
from this repo
https://github.com/henryjfry/repository.thenewdiamond

you can have skins that allow you to replace information with the extended info like this one.

it's pretty amazing, it uses Themoviedbhelper which I know you rather not touch but you probably don't have to touch that.
would be very beneficial for Nimbus to have this as an option that you can replace normal information screen.

Just thought I'll bring it to your attention since someone in reddit was asking how to get information on umbrella and I told them about this addon and thought it would be cool if it was able to integrate with Nimbus. peace

**Comment by ivarbrandt** [comment]
I don't want this in my skin. If I decide to add in functionality that provides what that addon does, I'll do it in the helper for Nimbus.

**Comment by hcgiub001** [comment]
thanks for replying. I understand just thought to mention it :)
