### ISSUE TITLE
Cast images are not being picked up in list view when browsing in themoviedb addon

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#35]
I'm in TheMovieDb Helper

in list view
![Screenshot (190)](https://github.com/user-attachments/assets/3393be29-9f37-47c7-9a45-d1e8b335a37b)

in flixlist view
![Screenshot (192)](https://github.com/user-attachments/assets/37cecb91-5583-47b0-b404-98a52b194cd1)

this is what default estuary skin shows
![Screenshot (193)](https://github.com/user-attachments/assets/a54f64b5-d376-4acb-8197-cc9494a37779)

anyway possible we can have the images + text on both list/flixlist view?
thanks for your consideration

also you mentioned Nimbus Helper before but I can't find the addon and wanted to check it out

**Comment by hcgiub001** [comment]
this is what arctic horizon 2 shows
![Screenshot (194)](https://github.com/user-attachments/assets/f0e19d25-979f-43ca-a617-0e0d04147152)

I'm guessing it's pulling her information about age and residence from TMDB?
if Nimbus can have those information it would be sweet

**Comment by ivarbrandt** [comment]
TMDbHelper is not supported.

See the changelog in Skin settings > Extras for information on how to update the helper to the latest version.
