### ISSUE TITLE
Home screen is not touch friendly.

### ISSUE THREAD

**Issue by RevontuletCXVII** [ivarbrandt/skin.nimbus#36]
Skin looks and works awesome apart from some issues. Would love to use it as a modern replacement for Estuary/Fentastic, but the home screen is not touch friendly in the slightest. 

Swipes open random side menus, taps don't register in the right places, and if I didn't have only my Add-ons as a widget, I'd have to go into debug mode to just turn off the skin. Every other menu works nicely, but a smoother way to open the sidebar (for changing views and such) would be nice as well.

**Comment by ivarbrandt** [comment]
Nimbus is not made for touchscreens. For the best experience use a keyboard or a remote.
