### ISSUE TITLE
Gismeteo weather - cycling through locations?

### ISSUE THREAD

**Issue by npmstart-pray** [ivarbrandt/skin.nimbus#37]
I'm trying to determine how to cycle through the locations I have set for weather updates, and I've not found it yet. In stock Embuary, it's just a matter of pressing ok in my remote app and the next location populates the screen. Not in Nimbus. Do I have to dig into widgets and make one for each city?

**Comment by ivarbrandt** [comment]
I have not yet figured out how to implement the cycling of locations. I've tried various ways and they all have been buggy.

**Comment by npmstart-pray** [comment]
I'll keep my eyes open here for a follow-up. Thank you.

**Comment by ivarbrandt** [comment]
I got the location cycling working on the home screen. Click the weather main menu item and it'll cycle to the next location.

It needs to open the weather window to be able to do this so you'll see the home window fade out then back in again when you cycle locations. This will only happen one time on each Kodi startup and only when the button is clicked. After that you'll be able to freely cycle through locations without any windows opening/closing.

This will be available in the next update.

**Comment by npmstart-pray** [comment]
Wow, that was quicker than I expected. 
Standing by for the upcoming update!  Thanks much!!

**Comment by npmstart-pray** [comment]
Updated and working as expected. 
Again, many thanks!
