### ISSUE TITLE
Hide seekbar when paused

### ISSUE THREAD

**Issue by Jcloak** [ivarbrandt/skin.nimbus#38]
There are scenarios where it is useful to see the entire screen when pausing a video. It would be nice to have a setting to auto-hide the seekbar when video is paused similar to the auto-hide OSD setting.

**Comment by ivarbrandt** [comment]
I don't want this in Nimbus.

**Comment by VelimirSaban** [comment]
I know I probably won't change your opinion on this, but for the record I would like to see this option as well. The main reason is that sometimes I don't want to know how much time is left until the end of the movie, and I have to press pause :)

**Comment by VelimirSaban** [comment]
Let's say I'm watching a movie for which I don't know how long it is. Maybe I didn't look at the duration or I didn't want to know, and I get completely lost in the tense story, but when it's the most interesting, I have to go to the toilet and take a break. At that moment, when I press pause, the interface will show me how much time I have left and this will often spoil my viewing experience. :) I want the feeling to be like in the cinema, where I don't know how long the movie will last and what else could happen. I know it's a bit of an unusual explanation, but I often look for that option when choosing skins. I managed to prove the relevance of this option with some developers in the past, for example, OSMC skin has this option, Mod Estuary MOD V2 also offered something similar at the user's request, etc. 
Some skins offer an option to automatically hide the seek bar when the video is paused, but for me it's not enough, I really don't want to see the seek bar, nor the duration, nor when it will end, just a freeze image. Another reason would be when I want to see or search for something in the movie, so I want to freeze the image without any interface elements. Of course, this happens rarely, but it is useful.
I completely understand that you don't want to take user suggestions for some new skin elements, I respect that. The skin is really beautiful, simple, light and I'm grateful for everything you do. Thanks!

**Comment by ivarbrandt** [comment]
That is such a great explanation. I love it. Thank you for sharing.

Alright I added it in for next update which will be soon. It won't auto-hide. It'll just pause your content with zero on screen elements. You can literally pause and unpause during the whole movie and never see the OSD if you want.

> I completely understand that you don't want to take user suggestions for some new skin elements, I respect that.

I appreciate you being aware of this.

**Comment by Jcloak** [comment]
Thanks for the work on this one. Is it possible to adjust this so it only stays hidden during pause, but is still visible when seeking?

**Comment by VelimirSaban** [comment]
I would also like to have seek bar displayed when seeking because, for example, we can see if a desired jump of 10, 30, 60... seconds happened correctly after remote input. I skip intro of some shows so visible seek bar is nice to have for easier navigation to a desired time of the show. Thanks!

**Comment by ivarbrandt** [comment]
Fixed for next update.
