### ISSUE TITLE
Auto trailer still playing once I enter Fen Extra menu in background

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#39]
First of all I really love the new additions! I've noticed you add a vertical line to give more emphasis on what is highlighted nice
and of course the symbol to show a movie is part of a collection. kind of better than how I envisioned it. I also love how you change the colour to match the background, damn sweet! nice work

so regarding the behaviour , if auto trailer is enabled and Fenlight has extras eneabled, if I press select to enter extras menu, the trailer is still playing.
also if a movie is part of a collection and I press select to enter the collection set, the trailer is still playing. now that the focus has changed maybe stopping the trailer would be more intuitive?
but yeah really like Nimbus now thanks

**Comment by ivarbrandt** [comment]
While I agree that it's not ideal behavior, I don't feel like fixing it.

It doesn't impede functionality in any way. 

Just end the trailer by pressing left or right then go into extras.

**Comment by hcgiub001** [comment]
yeah It's not so bad, plus you might want to watch the trailer more when you enter the collections page and have the option to look at the collection to
