### ISSUE TITLE
Adding a little something to help out a friend with fonts. :)

### ISSUE THREAD

**Issue by Tikipeter** [ivarbrandt/skin.nimbus#4]
Hi there mate.

I'm playing around using this skin on my test kit, and loving it. Really great work with everything so far.

I'm hoping you can accommodate a small request I have..

Could you add `<style>symbol</style>` to the 3 `ICON FONTS` you have in `Font.xml`?

eg..

```
		<!-- ICON FONTS -->
		<font>
			<name>PlayerIcon</name>
			<filename>remixicon.ttf</filename>
			<size>38</size>
			<style>symbol</style>
		</font>
		<font>
			<name>PlayerIconSmall</name>
			<filename>remixicon.ttf</filename>
			<size>32</size>
			<style>symbol</style>
		</font>
		<font>
			<name>SmallIcon</name>
			<filename>remixicon.ttf</filename>
			<size>22</size>
			<style>symbol</style>
		</font>
```

It will tell Fen/Fen Light not to pick those particular fonts when it is trying to match the skin's font sizes to what it needs. At the moment, I need a font of size 38, and Fen/Fen Light are picking the `PlayerIcon` font. Which is not good. :)

Thanks if you can do this for me. :) :)

**Comment by ivarbrandt** [comment]
Hey man! How's it going?!

I see you've found my secret project 😉 

> I'm playing around using this skin on my test kit, and loving it. Really great work with everything so far.

Awesome! Netflix-like skins aren't for everyone but I really like the way it's turned out so far. Cool to hear you're enjoying it as well.

> I'm hoping you can accommodate a small request I have..

I got you my guy. I'll add that in for the next update.

**Comment by Tikipeter** [comment]
>Netflix-like skins aren't for everyone

Yeah I'm generally one of those people. But I'm trying to get used to that layout as I really love the skin. :)

>I got you my guy. I'll add that in for the next update.

You're too good to me. Thanks mate. Appreciate it.

**Comment by ivarbrandt** [comment]
> But I'm trying to get used to that layout as I really love the skin. :)

That's awesome! So cool to hear :)

> You're too good to me. Thanks mate. Appreciate it.

You're very welcome. The changes are in `0.0.76`

I've been meaning to contact you about something else regarding Nimbus. I just didn't want to draw attention to the skin because it was nowhere near usable in the beginning.

I've noticed when using the one-click trailers or the auto-trailers that at the end of playback the widgets all reload. This happens in Fen and Fen Light. Is there a way for Fen/Fen Light to know the difference between trailer playback and normal playback initiated from within Fen/Fen Light?

If you could implement this it'd be awesome. If not, no worries :) I just thought I'd ask.

**Comment by Tikipeter** [comment]
I'm really sorry mate, I can't help you with that. There is no help for it unfortunately.

That is Kodi itself refreshing the widgets at start and end of playback.

There is no way to stop it from happening.

**Comment by ivarbrandt** [comment]
No worries man, It's good to know. I thought it was Fen and Fen Light doing that lol. Thank you for telling me.

**Comment by Tikipeter** [comment]
The font changes worked a treat.

Thanks again. 🥇

**Comment by ivarbrandt** [comment]
Glad to hear it!

Anytime man 👍🏽
