### ISSUE TITLE
Widgets navigation

### ISSUE THREAD

**Issue by xavengedx** [ivarbrandt/skin.nimbus#40]
I can't find a visual cue showing the user that there is another row/widget above or below. Is there a way to show that there is another menu below the current widget?

**Comment by Guguloi** [comment]
Just look after signs.  😄 
![IMG_20240808_204647](https://github.com/user-attachments/assets/cb28ee8f-0d67-469f-87d9-7534114211a0)

**Comment by xavengedx** [comment]
Yes, I already found the option that leaves it like that, but with the widgets appearing underneath I think it's cool KKK but it's an irrelevant thing actually, Nimbus skin is the most fantastic of all! Nimbus + Fen light + RD best configuration ever!

**Comment by xavengedx** [comment]
The only thing missing was Fen light having the option to configure it in Portuguese, because I'm from Brazil, the best Addon to use with Nimbus is Fen light, the movie collections function, even though it was recently launched, only works with Fen light

**Comment by ivarbrandt** [comment]
This would require a full redesign of the home screen and I'm not doing that.
