### ISSUE TITLE
Have to toggle blur on then back off for color scheme highlighting to work

### ISSUE THREAD

**Issue by meesterexx** [ivarbrandt/skin.nimbus#41]
This is kind of a weird one. If I use a color scheme (like Rufous Red), each time I relaunch Kodi, I have to toggle blur on then off 1 time for the color scheme to show. Otherwise all the highlights are white. Color highlighting persists through a skin reload, but if I close Kodi and relaunch, it loses the highlighting. It does this on both the android tv box and desktop (Linux) so doesn't seem OS specific. Not a big deal but wanted to make you aware in case you hadn't seen it. To me, it seems like on launch it's not checking the color scheme setting if blur is off and uses the default white highlight. Once you toggle blur on/off manually it is reading the color scheme setting.

On Kodi launch before toggling blur on then off:
![Nimbus no color](https://github.com/user-attachments/assets/a3746315-efe5-4c26-8de0-301e1606d2ce)

After toggling blur on then off:
![nimbus color](https://github.com/user-attachments/assets/af72646d-6d3f-4fee-8bbd-41d960075804)

Before toggling blur:
![no color 2](https://github.com/user-attachments/assets/5dbe648c-350f-4bc0-8b98-2544aa43e5db)

After toggling blur:
![color 2](https://github.com/user-attachments/assets/db3f3515-a044-428c-b8a5-5f4a6e4772bb)

**Comment by ivarbrandt** [comment]
Fixed for next update.

**Comment by meesterexx** [comment]
Hey, thanks for the quick fix! Still loving this skin and appreciate all the work and improvements you put into it :smile:
