### ISSUE TITLE
[BUG] to big space in list view when using scrubs

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#42]
https://streamable.com/mjt0ph

only happens in scrubs, not sure why
peace

**Comment by ivarbrandt** [comment]
Looks like It's using addons as the content type for the list view. Can you check that for me?

When you click left into the View options it will say at the top what type of content it is.

**Comment by hcgiub001** [comment]
do you mean this?
![Screenshot (288)](https://github.com/user-attachments/assets/759ba330-8376-4613-8e71-5c5383c3ae01)

**Comment by ivarbrandt** [comment]
Yes. Fixed for next update.

**Comment by hcgiub001** [comment]
yay!
