### ISSUE TITLE
[Feature Request] turn off collection icon if we entered a collection screen

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#44]
To me a collection icon represents that a movie is a set and not just an element.
when we are inside a set, then the individual movies are elements (and not sets), which the icon over elements isn't working in that thinking.
Are you able to turn them off when inside a set? imho it looks cleaner plus we have no use of the icon inside a collection since we know they will be part of a collection, which is redundant

**Comment by ivarbrandt** [comment]
I like this idea. I'll add it in for next update.
