### ISSUE TITLE
[BUG] If scrollbar has focus on one menu and you return to previous menu, the scrollbar has focus

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#45]
expected result: when I return to previous menu (backspace) I expect the focus not to be on scrollbar, even if I had focus on scrollbar on a different menu

https://streamable.com/0x2r00

**Comment by ivarbrandt** [comment]
Not a bug. This is how scrolling is in almost every skin including default Estuary.

**Comment by hcgiub001** [comment]
thanks
