### ISSUE TITLE
[Feature Requests] some ideas

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#46]
1/ if we set press down to enter trailer, then press down to close trailer

2/I like ability to chose what action  happens when we press down, are you able to use long press to configure other actions?
so pressing down I can set to trailer and long press down I can set to open wall, you could have long press up to set information etc

3/When you enter POV trailer you a timeline at the bottom
![Screenshot (295)](https://github.com/user-attachments/assets/99f966e5-8bfe-49e9-8fb4-5ed9f15e20f6)

when watching trailer it's a nice indication to know when the trailer will finish so you can quickly get to watching a movie.

if this can be done and I press down for trailer, it would be really good if the focus is on timeline so then I can press right and left to go forward or back in the trailer, then maybe I can press up so the trailer ends and the focus is on the movie item

(what would be even cool would be if you can have the colour or the timeline to be the match background blur colour)

Just throwing out some ideas

**Comment by ivarbrandt** [comment]
> 1/ if we set press down to enter trailer, then press down to close trailer

I don't like this. Plus it would interfere with normal OSD operation.

> are you able to use long press to configure other actions?

Not that I know of. The only way I know to configure long presses is by modifying the `keymap.xml`. But again, I don't like this idea.

> when watching trailer it's a nice indication to know when the trailer will finish so you can quickly get to watching a movie

Eh, one click on the OSD and you'll see how time is left exactly and visually. So no on this one.

> it would be really good if the focus is on timeline so then I can press right and left to go forward or back in the trailer

You can do this already by just pressing left or right while the trailer is playing and it will seek.

>then maybe I can press up so the trailer ends and the focus is on the movie item

Again, this would interfere with normal OSD operation.

> what would be even cool would be if you can have the colour or the timeline to be the match background blur colour

Funny you mention this, the next update will have the ability to extend the auto changing background color to other parts of the skin. Not the OSD though.

**Comment by hcgiub001** [comment]
> You can do this already by just pressing left or right while the trailer is playing and it will seek.

if using this settings
![Screenshot (309)](https://github.com/user-attachments/assets/bbee3000-2127-496a-bcb1-97952c185023)

pressing right or left just changes the movie you are in.

> "1/ if we set press down to enter trailer, then press down to close trailer

I don't like this. Plus it would interfere with normal OSD operation."

if a trailer is playing and we press down, it just reloads the trailer 
https://streamable.com/nrsr7b
having it closed when we press down has benefits, you might want to see 
like this
![Screenshot 2024-08-13 153421](https://github.com/user-attachments/assets/6ac9988a-a6fb-409b-ba13-201a08650934)
you can't see that again if you wanted to watch the movie

> Not that I know of. The only way I know to configure long presses is by modifying the keymap.xml. But again, I don't like this idea.

some people don't have many buttons, even more people are not aware of long press functionality.

there is one way

in your gen.xml file

```xml
<?xml version="1.0" ?>
<keymap>
  <global>
    <keyboard>
    </keyboard>
  </global>
  <Videos>
    <keyboard>
      <down mod>RipCD</down>
    </keyboard>
  </Videos>
</keymap>
```

I placed the key in videos window. This has less chance of it messing up with long hold down arrow in other windows and
we only using it in video window, it doesn't matter anyway since no one really uses long down key

now I mapped it to RipCD, which I believe is redundant and no one uses.
(got that from https://kodi.wiki/view/List_of_built-in_functions)

but you can set Nimbus to perform an action when it see's the RipCD command to say open the wall

this has benefits because you don't have to keep altering with keyboard.xml file
and you can chose to disregard the action on any screen you don't want.

the delay to normal down isn't bad either.

this way we can have trailer for down button but not miss out on wall function by assigning it long down.

anyway I just throw out ideas, it's okay if you say no (I normally get more ideas later lol)
I'll close it if you still don't like them

**Comment by hcgiub001** [comment]
> Funny you mention this, the next update will have the ability to extend the auto changing background color to other parts of 
> the skin. Not the OSD though.

I only got that after seeing you could alter the collection icon, otherwise I wouldn't have known that was possible lol

**Comment by hcgiub001** [comment]
disregard the long down command request, I forgot you can't hold down the key for normal behaviour, like I want to quickly scroll down a list and hold down, now I lose that ability. my bad. just let me know the rest are bad request and I'll close

**Comment by ivarbrandt** [comment]
Please don't delete your comments. It confuses me when I check my phone and I see multiple notifications and then when I click on them to see the rest of what you said, the comment is gone.

As for the trailers being able to be stopped when pressing down, I like this. I'll add it in.

**Comment by hcgiub001** [comment]
sorry, I wrote about the long press down, quite lengthy but realised that you lose the ability to hold the down button to quickly go through a list.
also I mentioned that right now the behaviour of pressing down was to reload the trailer.
and lastly I mentioned that when the trailer loads pressing right or left actually just changes movie.
and we have no way of changing the timeline on the trailer.

I'm not sure if I'm bothering you too much with my request and I've done this before and didn't want to waste your time, so I thought it's best to delete since you already said no.
