### ISSUE TITLE
Adding fonts

### ISSUE THREAD

**Issue by mukuluku** [ivarbrandt/skin.nimbus#47]
Hello, thanks for the great job!

I have noticed that you have several other fonts files already in the fonts folder. 
Would it be possible to make them optional selectable from the skin?
I usually use inter-black for example and have to edit the files after each update. 
I think it would be a good addition to the skin in general.

Thanks!

**Comment by ivarbrandt** [comment]
Nah I like them as they are now. They are there in case I decide to implement them later elsewhere in the skin.
