### ISSUE TITLE
My last order

### ISSUE THREAD

**Issue by xavengedx** [ivarbrandt/skin.nimbus#53]
When I configure the POV for my language in PT, I have this problem with the genre of the film, I don't mind that the genre appears in English, if you can fix that! Thanks for the work @ivarbrandt 

![screenshot00013](https://github.com/user-attachments/assets/86fda76e-2d7d-4dfd-98ad-e86ac7e25b60)
![screenshot00012](https://github.com/user-attachments/assets/a83477a2-f741-4ba1-b40d-1a8f26a6600a)

**Comment by ivarbrandt** [comment]
This isn't possible.

When you changed the language to Portuguese, you also changed the way the genre makes its way to the genre classification system. Because there isn't a match, it will display nothing.
