### ISSUE TITLE
[BUG] Dramacool

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#55]
![Screenshot (331)](https://github.com/user-attachments/assets/a553f76a-c258-430d-b49a-55fc19ebdb4e)
the poster is over the text
![Screenshot (333)](https://github.com/user-attachments/assets/943c3d1c-b66a-4f95-9c33-cae20edb4317)

If I'm in wall view, it will go into flixlist view after I change the movie selection, it can't auto save the view and on the side panel you have
![Screenshot (335)](https://github.com/user-attachments/assets/12ae41f7-82b4-4498-a25d-99e5df4eda69)
same happens when I'm in  wallscape, it will go to flixlist view after like 5 seconds without me doing anything
![Screenshot (336)](https://github.com/user-attachments/assets/c7286dbc-03d8-49b2-bc9a-fe6250a8e12c)

List view is missing the text for each listing 
![Screenshot (337)](https://github.com/user-attachments/assets/753fbe8a-1af0-4a57-9aaa-365f961ac2bb)

Lastly I'm not sure how you know what to use for trailers, but I was wondering if you had logic that removed from the title
[SUB] Yolo (2024) EP 1

so you remove the "[SUB]" and "EP 1" when doing a YouTube search? 
I created a list with movies from dramacool in trakt
https://trakt.tv/users/trkthc001/lists/asiancsh-recently-added-movie-1?sort=rank,asc

so I could quickly check in Fenlight which movie had a trailer and I know
https://trakt.tv/movies/yolo-2024
has a trailer but in dramacool no movies seem to have trailers

**Comment by ivarbrandt** [comment]
Fixed for next update.

> has a trailer but in dramacool no movies seem to have trailers

Dramacool doesn't provide an IMDb ID so Nimbus can't look up the trailer. You could try the default source for playing trailers.

**Comment by hcgiub001** [comment]
default source didn't work but it's no biggie, thanks
