### ISSUE TITLE
[BUG] Lost in Rio movie is showing collections item inside the collections screen

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#56]
![Screenshot (341)](https://github.com/user-attachments/assets/c18dc265-a664-4628-83a6-8d251f4d27fa)

![Screenshot (342)](https://github.com/user-attachments/assets/97e2561e-b2de-4b81-8cc6-a6e73b19815d)

each movie inside the collection has the collection icon

**Comment by hcgiub001** [comment]
while I'm talking about the collection Icon, I'm really enjoying knowing if the movie is 1st in the collection, is it possible to know the placement of other movies in the set? or even have something like 1/3 to show like it's 1st out of 3 in the collection?
if not it's no biggy

**Comment by ivarbrandt** [comment]
Fixed for next update.

> is it possible to know the placement of other movies in the set?

Not possible
