### ISSUE TITLE
[BUG] Watchmen chapter 1

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#57]
![Screenshot (344)](https://github.com/user-attachments/assets/899ffd0e-9460-4864-a139-fbb2a5af1107)

the IMDB and TMDB ratings are not matching
![Screenshot 2024-08-15 055111](https://github.com/user-attachments/assets/7a28da90-54bf-4872-9cf3-cddba58125c4)
![Screenshot 2024-08-15 055120](https://github.com/user-attachments/assets/e4bb9a07-5e62-4057-85ef-6a1aa178eb87)

and that tmdb rating is missing part of the 0

**Comment by ivarbrandt** [comment]
Nothing I can do about that as those are the ratings pulled from the API. It could be that they are old ratings as Nimbus only allows updating the ratings if it has been 7 days since it was last updated.

I fixed the TMDb rating cutting off as well.
