### ISSUE TITLE
[BUG] Crew

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#58]
![Screenshot (345)](https://github.com/user-attachments/assets/79a79067-8297-4dd9-883d-56060c367c02)
you have that spacing

![Screenshot (346)](https://github.com/user-attachments/assets/e8c3b3f6-0ac6-4eb7-b379-d6283092495c)
![Screenshot (347)](https://github.com/user-attachments/assets/df57e513-e7bf-4994-9a01-c7b7b683c2e9)

and not sure if you can do anything about this but it's taking a while to load the posters 
https://streamable.com/2o6vul

much longer than other addons

**Comment by ivarbrandt** [comment]
Fixed for next update.

> and not sure if you can do anything about this but it's taking a while to load the posters

Nope. That's addon related.
