### ISSUE TITLE
Video OSD playback controls will break if Font is changed to Arial

### ISSUE THREAD

**Issue by kim1406** [ivarbrandt/skin.nimbus#6]
I'm a fan of Fentastic skin and I've just tried Nimbus and found it amazing. I have to change the default font to Arial based, since I need Arabic language to work. Everything is working great, but, I noticed that, the Video OSD playback controls bar is messed up when I use the Arial font instead of the skin default font. See image below. I hope this will be fixed soon. 
Thanks. 

![OSD Contorls](https://github.com/ivarbrandt/skin.nimbus/assets/5627410/42a187ff-767a-471c-b5d5-e0cd0d048ba1)

**Comment by ivarbrandt** [comment]
I gotchu. I'll fix it for the next update.

**Comment by kim1406** [comment]
Great to hear that. Thanks for your effort.

**Comment by ivarbrandt** [comment]
Fixed.

**Comment by kim1406** [comment]
Thank your very much. It's fixed now. I may have a small problem if you can fix also. If I use Arabic metadata language in both FEN and POV, genre tag will not be shown. On Fentastic skin, it is shown fine in Arabic letters, so, the problem could be the Arial based font in Nimbus is not the same as the one in Fentastic. Below pictures from both skins.

Here is the problem:

![Problem-New skin](https://github.com/ivarbrandt/skin.nimbus/assets/5627410/059a2ee7-69a5-41c2-bc5b-e0c97389413f)

No problem when English metadata is used:

![English-New Skin](https://github.com/ivarbrandt/skin.nimbus/assets/5627410/5a7eba0b-0d6a-4234-9d06-be3ef2c383a6)

Here how it is shown on Fentastic which is fine:

![Fentastic OK](https://github.com/ivarbrandt/skin.nimbus/assets/5627410/8e66c55a-5883-40f4-bcc1-7f38757a66f3)

**Comment by ivarbrandt** [comment]
I create the genres in a special label in Nimbus. Without the direct translations of all the genres possible in Arabic, I can't fix this. Use the English metadata to avoid issues.

**Comment by kim1406** [comment]
If needed, I can help translate the whole skin. Just give me the required files. I did translate Aeon MQ long time ago.
