### ISSUE TITLE
Collection icon issue

### ISSUE THREAD

**Issue by djdirty60** [ivarbrandt/skin.nimbus#63]
Good day,

When I am in my collection, the movie collection icon is not visible, but via the widget.

![image](https://github.com/user-attachments/assets/bf1b7b03-a1d8-4545-b5c2-d40df93695d1)

You can take a look at that.

Thanks in advance

**Comment by ivarbrandt** [comment]
The movie collection icon shows for movies that belong to a movie set. Your custom collection doesn't count.

**Comment by djdirty60** [comment]
> The movie collection icon shows for movies that belong to a movie set. Your custom collection doesn't count.

But the movies that are in my custom collection are also in movie collections. Previously, the icon could be seen in the custom collection.

**Comment by djdirty60** [comment]
Widget
![image](https://github.com/user-attachments/assets/1f962ed2-6a67-49a0-a21b-71adf50ede21)

my collection
![image](https://github.com/user-attachments/assets/d3f0d4c5-980a-4560-8839-2dc48b929494)

**Comment by ivarbrandt** [comment]
Shiiit. I see your point. I'll see if I can come up with a fix.

**Comment by djdirty60** [comment]
> Shiiit. I see your point. I'll see if I can come up with a fix.

Doesn't matter, can happen. I only noticed and thought it was a shame it was gone. Hoping you can find a solution.

Thanks in advance for your top skin. And your hard work for

**Comment by ivarbrandt** [comment]
Good eye. I had no idea.

I came up with a fix. It'll be in the next update.

**Comment by ivarbrandt** [comment]
Update is up.
