### ISSUE TITLE
[BUG] a movie showing as 1st in connection when it's not

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#64]
![Screenshot (370)](https://github.com/user-attachments/assets/1024be90-7b24-483e-a602-1cec6deceda6)

and when I enter the collection

![Screenshot (371)](https://github.com/user-attachments/assets/e054063c-9140-44a7-bb71-40325e87a7ef)

I wanted to see what it shows for the other movie for the collection icon

![Screenshot (373)](https://github.com/user-attachments/assets/2de4925e-e671-43b3-9ba8-33ceeebb82c3)

**Comment by hcgiub001** [comment]
some strange behaviour going on I noticed
https://streamable.com/kq55cg

I searched for the movie "one-armed boxer"
these 3 results came up

one-armed boxer
One-Armed Silat Boxer
Master of the flying Guillotine

not sure why the last movie came up because it doesn't have that name

the middle movie One-Armed Silat Boxer is not part of a collection
If I move from 1st movie to second, it borrows it's collection icon (though not part of a movie)
If I move from third movie to second one, again it will borrow it's collection icon 

as you can see from the video I uploaded.

**Comment by ivarbrandt** [comment]
I've noticed this too for about 4 or 5 different collections now. The data coming from the API doesn't seem to be that reliable.

If I find this happens a lot I'll have to remove the feature altogether.

**Comment by hcgiub001** [comment]
I searched for 
"One-Armed Silat Boxer"

on it's own and this came up
![Screenshot (375)](https://github.com/user-attachments/assets/6e69ccbf-fb48-4426-bca3-2d4d53d6f06f)

I wanted to see if I return to the selection with all 3 and inherit the other icon (without the one) what will happen.

it switched to the other one, so it definitely saved it for some reason

![Screenshot (376)](https://github.com/user-attachments/assets/2e849fb3-430e-449c-9a75-3fd41cf03578)

> If I find this happens a lot I'll have to remove the feature altogether.

do you mean the collections icon or showing if it's first in the collections set?

how is one movie able to change the collection icon of another?

I did some more testing with this movie

"One-Armed Silat Boxer"
I created a list with this movie and another movie not belonging to a collection

I cleared all cache, checked the collection icon of One-Armed Silat Boxer by searching for that movie,
it returned none
so now did a search for One-Armed  Boxer, to bring up those 3 movies
the previous behaviour remained the same (it inherits the collection icon from the last movie)

then I went back into my list and still saw that it inherited the collection icon, went to the movie without collection item and back to One-Armed Silat Boxer, now it inherited it's (absent) collection icon

it seems this movie is behaving oddly? 

also another weird thing I noticed, I cleared cache and searched for that movie
One-Armed Silat Boxer
and the layout seems to be bugged for that movie now
![Screenshot (378)](https://github.com/user-attachments/assets/ff2a4bfb-96e9-4c04-9bdd-f6a625caf73f)

this is the only movie I've noticed this from

**Comment by hcgiub001** [comment]
> I've noticed this too for about 4 or 5 different collections now. The data coming from the API doesn't seem to be that reliable.
> 
> If I find this happens a lot I'll have to remove the feature altogether.

did you watch my video here
https://streamable.com/kq55cg
?

**Comment by ivarbrandt** [comment]
You ran into a very rare bug lol. I'm pretty sure it's fixed now though.

https://github.com/user-attachments/assets/1dccf627-195e-4987-b9c1-3a538f0e9dc4

**Comment by hcgiub001** [comment]
I wish I did computer science lol
my background is mathematics
thanks for fixing this
:)

**Comment by hcgiub001** [comment]
I'll let you close when you update this in Nimbus.

**Comment by ivarbrandt** [comment]
> I wish I did computer science lol

It's never too late.

**Comment by Tikipeter** [comment]
I feel hcgiub001 is on their way, at least to coding a Kodi addon or skin or both.

I started by fiddling with skins, you started by fiddling with skins, and I see the same path going on here.

Anyway, it looks like the keywords method might end up not being entirely reliable. I was afraid that might be the case.

**Comment by ivarbrandt** [comment]
Agreed, they just gotta take the leap.

I'm in the middle when it comes to the keywords method. It gets most of them right but others wrong. I wouldn't mind too much if it was an obscure collection but it gives me pause to see something as popular as the Dark Knight categorized incorrectly.

Worse case scenario I'll remove whether or not the movie is the first in the collection and just use the basic collection implementation where it tells you if a movie belongs to a collection or not.
