### ISSUE TITLE
custom window to bring back favourites dialogue

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#66]
I'm sure you've used favourites dialogue, I did when we had confluence as default.
it's replaced by favourites window now.

it has so much functionality, you could put in shortcuts to other parts of your build or put in a search for addons. best thing was you don't have to leave your current window and after the action when you press back you get back to your previous window.

so I was thinking how about creating a custom window and inside it you grab what's in the favourites.xml

it could work really well in Nimbus. here is what I was thinking

when in flix view and we click up, we have the side panel. we press right  and we get the favourites panel (custom window)

at the top of the favourites panel you could have refresh and run a script to grab everything from favourites.xml and see what's added
now If I press right again the favourites window will go and the side bar will come back
each time you shuffle the sidebar to favourites you could have it so it's automatic.

so I can press up, right, pick a favourites item, which will close the panel , now if I press up again. I get the favourites panel first. (pressing right will shuffle to side panel)

I checked on each option in side bar and pressing right doesn't do anything once inside sidebar, same applies to any favourites item

now most people might not keep changing the skin settings so this could be super super useful functionality to instead have a favourites dialogue. and the side bar is only one extra click away.

I even asked Bing Copilot if it's possible and it said yes lol
is it possible to do this? custom window which has the favourites items?
no skin going forward will have favourites as a dialogue accessible anywhere in kodi!

**Comment by ivarbrandt** [comment]
This is a cool idea. I'll think about it.

**Comment by ivarbrandt** [comment]
I've decided no for now. It's a bit more work that I'm willing to put in at this time.
