### ISSUE TITLE
Update crashes on loading 7 widgets on 1.1.20 compared to 0.0.95

### ISSUE THREAD

**Issue by OnMyChown** [ivarbrandt/skin.nimbus#67]
Was really excited to try the update. I'll likely have to downgrade.
Retried making the widgets but still crashes.

Device is a Fire Cube TV 2nd GEN
![image](https://github.com/user-attachments/assets/776ad1c8-9623-4af6-9b2c-3e7ac4c6fc28)

**Comment by ivarbrandt** [comment]
That's over 20 versions ago. We could try to fix it but I recommend completely uninstalling the skin and helper. Then reinstall it and you should be good to go.

**Comment by OnMyChown** [comment]
Tried reinstalling skin (clean settings) and helper with no luck. Crashes consistently at around 8 widgets

**Comment by npmstart-pray** [comment]
Amazon Fire devices may have processors that are up to modern speed standards, but where they skimp out is in the RAM dept. the hint is in the 32bit OS. 
Your 7 widgets likely cause the machine to crash because the OS's requirements are probably ~300MB (or more!) of the 2 GB of RAM. 
Idk how much a fire device goes for, but you can probably get a RasPi4 with 8GB that runs a 64b OS for about the same price as that Bezos brick, and it'll last longer too.

**Comment by npmstart-pray** [comment]
Perhaps not, but it will end up obsoleting the device sooner than later either way, either with lack of RAM or apps being written as 64b to take advantage of greater RAM. 

If you don't mind me asking, how does the device get internet?

**Comment by OnMyChown** [comment]
The fire cube supports ethernet and wifi 6E. I have it on wifi

**Comment by npmstart-pray** [comment]
Tried hardwiring it to the router instead?

**Comment by ivarbrandt** [comment]
> Crashes consistently at around 8 widgets

Does it crash with 3 widgets?

**Comment by OnMyChown** [comment]
> > Crashes consistently at around 8 widgets
> 
> Does it crash with 3 widgets?

Not if it's just one category. If it were to 3 on 3 categories so 9 total I'm pretty sure it would crash.

I did revert to a backup with 0.0.96 and it works fine. If you'd like me to test further I can or you can close the issue. Lmk

**Comment by ivarbrandt** [comment]
Try deleting the settings.xml for the skin.  

File Manager > Profile Directory > addon_data > skin.nimbus > long press settings.xml > Delete

Restart Kodi right after. Then go and remake the widgets after you restart Kodi.

**Comment by OnMyChown** [comment]
Still crashes after deleting the file. Though my widgets were still there after deleting the file. I did however delete the skin entirely with the data afterwards since it was from the test repo and install the new one from the regular repo with the same issue after configuring the widgets.


I don't remember setting the main menu path for the widgets. I just set it up the same as my first widget. Could that cause an issue?

**Comment by ivarbrandt** [comment]
> I don't remember setting the main menu path for the widgets. I just set it up the same as my first widget. Could that cause an issue?

I'm not sure. I've never done that before. It shouldn't be possible to see any widgets without having a path set for the main menu.

**Comment by OnMyChown** [comment]
> > I don't remember setting the main menu path for the widgets. I just set it up the same as my first widget. Could that cause an issue?
> 
> I'm not sure. I've never done that before. It shouldn't be possible to see any widgets without having a path set for the main menu.

I was just curious if it had to be configured any sort of way.


Also might be irrelevant but FENtastic also works without issues with the same widgets

**Comment by ivarbrandt** [comment]
Nope. You set the main menu item and then set its widgets. That's it. Jumping from 0.0.95 to the current version is most likely the reason something is messed up.

Have you tried deleting the Addon13.db file? This is the last resort I go to fix something as it disables every single addon in your Kodi. If you have a lot of them it could be a pain to re-enable them.

This has fixed 99 percent of the problems I've had with skin/addons in the past. It is the semi-nuclear option short of doing a fresh install of Kodi.

**Comment by OnMyChown** [comment]
I noticed on my version of the skin the widgets tend to load one by one as I scroll down to them. Did that behavior change in future versions?

**Comment by ivarbrandt** [comment]
The widget sections or the widgets themselves within a section?

**Comment by OnMyChown** [comment]
The widgets themselves within each section. I'm assuming the behavior eventually changed to load entire sections?

**Comment by ivarbrandt** [comment]
It's never loaded just one widget at a time within sections. It's always displayed one widget at a time within sections.
