### ISSUE TITLE
Trailer setup not working

### ISSUE THREAD

**Issue by Maczilla** [ivarbrandt/skin.nimbus#68]
When i setup trailers to Auto, it works but keep restarting the movie trailer every 5 seconds. I change the setup from Auto to One-Click and remap the button i wanna use, this also doesn’t work.

**Comment by hcgiub001** [comment]
uploading a log and checking you are using the latest version of Nimbus + Nimbus helper would be quicker to get any issues resolved
https://www.comparitech.com/kodi/view-kodi-log-files-erorrs/

latest version of Nimbus is 0.1.20
Nimbus Helper 0.0.40

make it easier for Dev

**Comment by Maczilla** [comment]
Just installed it 3 days ago and thought any new updates would pop up like my other repo's. But after manually reinstalling the repo again it updated and everything works great now and solved the issue.
