### ISSUE TITLE
poster size

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#69]
I tweaked View_54_Flix.xml and got the posters bigger

https://www.reddit.com/r/Addons4Kodi/comments/1eunjk6/made_the_posters_in_nimbus_bigger_thoughts/

someone tried it and it didn't fit like mine, I realised it's because I don't have  a standard laptop screen.

now I understand why their was so much space underneath the posters, which I thought was wasted space

I changed a few elements, but the last poster won't come up on my setup, this was just a test case.

so far everyone commenting preferred the larger poster, what is your thoughts?

since everyone has different displays can you not have a multiplier that people can type into settings to get it perfect for their display?

like for the person whose interested but couldn't get it to work. I just multiplied all the sizes by 0.9
but the "watched" label and the icon next to it I had to do it by eye.
or just have two sizes, so users can pick

and since people have different size tv's this makes sense? I had lots of wasted space I didn't realise wasn't intended by Nimbus

If you think it's a good idea you can try, if not just close it thanks

**Comment by ivarbrandt** [comment]
Thats looks pretty cool!

It's not something I want in Nimbus as the poster sizes are too big for my taste but looks cool nonetheless.
