### ISSUE TITLE
[BUG] collection icon cut off in TMDBhelper

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#70]
updated to latest

this is in TMDBhelper
![Screenshot (395)](https://github.com/user-attachments/assets/4ab125f8-d443-446a-b355-e348c64ebd1c)

this is in Fenlight
![Screenshot (397)](https://github.com/user-attachments/assets/f5bfbe3c-8ff2-4051-82d1-966d5c28b7d6)

thanks

**Comment by ivarbrandt** [comment]
It's because you have the prefix "Rated" in TMDbHelper. You can remove this in the settings.

**Comment by hcgiub001** [comment]
I checked the settings and is this what you are referring to? 
I blanked out MPAA rating prefix that had the word rating inside
![Screenshot (411)](https://github.com/user-attachments/assets/f2f22c5a-44a9-49d9-b86a-1097fadba14c)

can't see a way to clear cache, so anyway tried on movies I don't think I clicked on before
the rating remains
![Screenshot (409)](https://github.com/user-attachments/assets/f08787fa-0c72-49ae-b868-649f71d257ac)
![Screenshot (410)](https://github.com/user-attachments/assets/542c3aee-7da0-45f4-bee1-654816638bc0)

another user had some other issue using TMDBhelper and took a screenshot of his screen

https://www.reddit.com/r/Addons4Kodi/comments/1eunjk6/comment/liq099j/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by ivarbrandt** [comment]
I don't use TMDbHelper and I don't support it in Nimbus.
