### ISSUE TITLE
[BUG] number keys not registering in fullscreenvideo

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#72]
I use number keys to skip type in the amount I want to skip ahead in a video. they are not registering on my setup

also when skipping ahead , that small line isn't as noticeable 
![Screenshot (413)](https://github.com/user-attachments/assets/80ddb0ce-1ea1-4752-a6c5-40fcd10147dc)

even having a blue line would stand out more?

EDIT:
if you go back in seekyou can't see the position
![Screenshot (415)](https://github.com/user-attachments/assets/383a5049-ca2a-4818-9238-a3062c1025fd)

**Comment by ivarbrandt** [comment]
Use a different color theme. As for the transparent background. It looks that way because your device has different dimensions.

This is what it's supposed to look like:

![Screenshot_20240818-125730](https://github.com/user-attachments/assets/6f533e18-4b01-4a1d-8874-572c2d7de356)

**Comment by hcgiub001** [comment]
yeah that's better thanks

**Comment by ivarbrandt** [comment]
The modular OSD has a thicker progress bar and the little line that you see when seeking appears outside of the progress bar. You could try that. Just disable what you don't need in it.

**Comment by hcgiub001** [comment]
I forgot , where you able to use the number keys to seek?

**Comment by ivarbrandt** [comment]
I don't use number keys to seek. I just click left/right.

**Comment by hcgiub001** [comment]
I understand. the colour theme worked for the other part so I'll close thanks

**Comment by hcgiub001** [comment]
> I don't use number keys to seek. I just click left/right.

have you never wanted to skip say 1 minute exact? Just curious, I watch anime and over the years I've learnt the intro is ~1 minute 25 seconds long, so all I do is press 125 right
allot of people don't know you can skip forward from your actual location. and think the number pad is only useful if you want to go to exactly a certain position and not a relative position.
one of the best thing about kodi is this ability to easily go anywhere I want.
