### ISSUE TITLE
Jellyfin addon paths no longer showing in config of menu items

### ISSUE THREAD

**Issue by boldenkintaro** [ivarbrandt/skin.nimbus#73]
Using latest version 0.1.21.

I am using the Jellyfin addon (not native mode) and want to configure my home screen accordingly. I want the "Movies" menu item to jump right into the addon's movie path. Not into my library.

But when configuring the skin's menu items, Jellyfins library paths to movies, shows etc. are no longer showing. They do show, when I enter the addon manually. They are only missing when configuring the skin's menu items.

Other skins work fine however...So I suppose it's not my Jellyfin config that's mistaken...

**Comment by ivarbrandt** [comment]
> are no longer showing

They used to show?

> They are only missing when configuring the skin's menu items.

Do mean the configured label for the main menu item in Skin settings?

Could you provide some screenshots? They would be quite helpful.

**Comment by boldenkintaro** [comment]
> They used to show?

Yes. I started playing around with Nimbus yesterday morning (Germany). Must be right before the new release was published. The previous release let me choose addon paths and displayed me all the different Jellyfin path options.

> Could you provide some screenshots? They would be quite helpful.

Sure! Now I learned how to make screenshots on my Nvidia Shield :-)

I reset Kodi and started from scratch to reproduce the problem.
I don't have a local library. All movies & shows are synced via Jellyfin's addon. As you can see, the default skin shows the movie & show library with the content provided by Jellyfin.

![Kodi_20240819_141718](https://github.com/user-attachments/assets/763c0c39-17db-416b-806a-6b140de3b76c)

Strangely Nimbus doesn't show my movie / show library at all, even though it is enabled by default:

![Kodi_20240819_141739](https://github.com/user-attachments/assets/c5bc0cfa-80fc-430e-86e9-1e586f415546)

![Kodi_20240819_141854](https://github.com/user-attachments/assets/c57e69c1-f1a9-486e-b740-750bb6949d1c)

And when I try to change the menu item's path, the following dialog opens:

![Kodi_20240819_000710](https://github.com/user-attachments/assets/81664bd0-9a8e-4cf0-87ad-ad6c4bcb8484)

When I choose to browse Jellyfin's path, the following reduced tree is shown:

![Kodi_20240819_000721](https://github.com/user-attachments/assets/1fc486ad-4dd8-4117-a473-e2f5a5d4701b)

But there should be many more paths to choose from. For example the Jellyfin's movie library, show library and so on.
Just for comparison - here is the dialog to choose paths in the Arctic Fuse Skin:

![Kodi_20240819_143208](https://github.com/user-attachments/assets/1eb48c64-f10e-49f4-aa4d-1bd60f46983c)

And these are all paths in the Jellyfin addon:

![Kodi_20240819_143200](https://github.com/user-attachments/assets/9d6c62d6-52e1-48bd-a249-e9c8479b8088)

Most of them are missing in Nimbus' dialog.

**Comment by ivarbrandt** [comment]
Thanks for the screenshots. Nothing changed in the most recent update to affect this.

Nimbus does not support library content. You might not have a local library but it looks like JellyFin uses a local library path for your movies and tvshows. That is why you're seeing a reduced tree.

**Comment by boldenkintaro** [comment]
Hm, thanks anyway :-)
Nimbus is astoninglishy beautiful by the way. I really like your design!

**Comment by ivarbrandt** [comment]
I appreciate it :)
