### ISSUE TITLE
glow around the scroll bar

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#74]
glow really makes this skin special and I was thinking how about have the glow on the scrollbar so the glow is almost in every menu in the addons, like the scroll bar here

![Screenshot (418)](https://github.com/user-attachments/assets/866efe01-60f0-490a-9a31-0bf78bdc146d)

if I press down, it would be better if the glow didn't start from the beginning but carried on at the same time from above, better for continuity   

EDIT:
the bar is so thin, you could just have the glow image and don't need a bar in front?
it is very small

**Comment by ivarbrandt** [comment]
I doubt I'll do anything to change this but I'll bite. 

What do you mean?

**Comment by hcgiub001** [comment]
I separated the glow image from the poster, and made it thinner to repsent the little line we have in the list view
https://streamable.com/

my idea was to replace the bar that shows which item is selected with a glow image that pulsates. when in list view for moving around it's not as dynamic and colour rich as flix view where people love it

but it seems the bar is to small. for this to work?

say I move down, you have a slim line

  |

slimmer than what you already have

but as soon as I move down and the line appears you fill from top to bottom with a thick linke
so the front element is a line
the back element is a rectangle that increases in height and starts from the top of the line
each time I press down we see this animation
if I go up, the rectangle starts from the bottom of the line and fills up

I think doing something eye catchy with the little line or something on that page would be cool.
you probably don't need a line element. just a rectangle like you have now but make it expand down if we move down, and expand up if we move up.
little touch that makes it interesting to be in each screen and each view?

**Comment by ivarbrandt** [comment]
You didn't post your actual video link

**Comment by hcgiub001** [comment]
my bad
https://streamable.com/ykygud

the video link itself isn't really showing much. I wanted to turn the glow behind a poster into the shape or the little bar.
but it's to small for the glow. but what do you think of the other animation idea.

**Comment by hcgiub001** [comment]
the glow doesn't work because I need to increase the radius or something

**Comment by hcgiub001** [comment]
https://github.com/user-attachments/assets/22eae6a6-b8b9-4377-81d9-d281117a96ed


https://github.com/user-attachments/assets/787576f4-b8fa-456b-aca1-4bdebbb8cfb6

this is the bar animation I was thinking of, if I move up the bar starts from bottom.

or if you can think of an animation you like. just something to make it more interesting.
thoughts on bar?

**Comment by ivarbrandt** [comment]
>  I wanted to turn the glow behind a poster into the shape or the little bar. but it's to small for the glow.

Ah I see. I've tried that before with a glowing selector at the bottom of posters. I didn't like it very much. The glowing frame around the posters looks much cleaner.

> this is the bar animation I was thinking of, if I move up the bar starts from bottom.

Interesting but I don't like it. I might make the current selector glow and pulse but that's as far as I'd go with that.

**Comment by hcgiub001** [comment]
the glow would fit well with the glow in other screens. just see how it turns out and if you like it. no biggie if you don't

**Comment by hcgiub001** [comment]
Hey Ivar
you mentioned " It changes the color scheme up in a natural way so you're never looking at the same skin so to speak"
I agree and love seeing all the cool transitions and colours.

which is why I thought won't it be cool if we could change the single image of that sunset.
so how about each day we have a new HD image bought to us by none other than bing!

You have two api's you can work with (probably much more)
https://peapix.com/api
https://github.com/TimothyYe/bing-wallpaper

Bing images are so amazing (and inspirational)!

have a look the images we get each day
https://peapix.com/bing

Wednesday
![Screenshot (447)](https://github.com/user-attachments/assets/48f4d039-a2ce-4811-a2ef-e15e3c03b34c)

Tuesday
![Screenshot (449)](https://github.com/user-attachments/assets/d1da3e83-ae38-4710-9e56-946030d40912)

Monday
![Screenshot (450)](https://github.com/user-attachments/assets/e29ced5d-6ff6-40de-98b7-19a38ac149b4)

the background doesn't have the logic to change according to the image and nor does the select bar

so with the glow and this dynamic new image everyday, would be cool?
https://[peapix.com/bing/feed?country=jp](https://peapix.com/bing/feed?country=jp)
