### ISSUE TITLE
[BUG] Widget pulse glow on poster and landscape

### ISSUE THREAD

**Issue by blackbaroon** [ivarbrandt/skin.nimbus#78]
First of all sorry for my bad english.
Aniway from version 0.1.19 the pulse glow highlight around the home widget on poster and landscape format not working when a video is playing on background (only work for square size).
Same problem entering on movie or tv show main menu (always on background video mode ).
No problem in normal mode (no background video execution). 
Version 0.1.18 no issue detected.
Congratulations for your hard work.Skin is very fast.

**Comment by hcgiub001** [comment]
(I'm not Nimbus Dev)
what current version do you have? the most up to date version is v0.1.21

**Comment by blackbaroon** [comment]
Same version 0.1.21

**Comment by ivarbrandt** [comment]
Fixed for next update.

**Comment by blackbaroon** [comment]
Thank you!!
