### ISSUE TITLE
Cast - Clicking on an Actor says 'No results found'

### ISSUE THREAD

**Issue by onlytanmoy** [ivarbrandt/skin.nimbus#80]
Hello @ivarbrandt hope you doing well, please refer the screen record https://streamable.com/itvt0h
I am expecting to see all the work (Movies & Shows) the actor is involved with, is there a way to fix this?
I am using the latest version of the skin.

**Comment by ivarbrandt** [comment]
Click right instead.

**Comment by onlytanmoy** [comment]
> Click right instead.

Thanks, that worked 🙂
From there when I browse a movie that actor is part of, it only shows Close and Plot buttons, is it possible to add another button, which upon clicking will display context menu from which I can play the movie, add to my Trakt list etc.?

**Comment by ivarbrandt** [comment]
Nah I don't want to.
