### ISSUE TITLE
[BUG] having a comma in search term , duplicates the search term plus poster missalignment

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#81]
hey ivarbrandt, hope your well

It's not a big bug 
![Screenshot (469)](https://github.com/user-attachments/assets/eced074d-5460-48bc-a87f-8e946edf8e16)

clicking without comma
![Screenshot (473)](https://github.com/user-attachments/assets/d17c3ceb-0e2a-4344-9091-378afd465d16)

clicking with comma
![Screenshot (474)](https://github.com/user-attachments/assets/7648004d-347a-4179-ab41-d2193337b58c)

thanks

**Comment by ivarbrandt** [comment]
I tried reproducing this with various addons and I couldn't.

This is likely addon related.

**Comment by hcgiub001** [comment]
I had this with Fenlight, I cleared all cache and tried searching again for that show and it was normal, yeah not sure what happened.
Only thing I can think of is I had auto translate on, wonder if I grabbed a title after it translated it and it had some weird character. Thanks for looking into this
