### ISSUE TITLE
Mini Menu Changes

### ISSUE THREAD

**Issue by rich333000** [ivarbrandt/skin.nimbus#83]
Home Mini Menu
1. Add option to hide Shutdown Menu & Settings, could add Settings to the Shutdown Menu window for easy access with 'S' key or remote button.
2. Add a Recent Search/New Search option, so we could have both New Search & Recent Search in the Home Mini Menu instead of picking one option for the Search function.

Search Mini Menu
1. Remove or add option to hide the selected Add-on toggle, it adds to confusion when most users only want to search one add-on and can easily be pressed by accident.

**Comment by rich333000** [comment]
Hey, I managed to implement theses changes on my own, but hard coded them instead of creating options to enable/disable in settings.

Can I ask, what area/lines should i be looking at to change the size of the menus? I want the mini menu to be 2 options in height, and the main groups menu to be 8, Then maybe adjust the the bottom mini menu with clock lower if needed. If you could just point me in the right direction and i'll have a go myself.

**Comment by ivarbrandt** [comment]
Look at the ListItem include and how it's used in the List include. That's how I build out the main/mini menu style.

**Comment by rich333000** [comment]
thanks! i've been able to set it up perfectly
