### ISSUE TITLE
[Feature Enhancement] change the colour of not yet aired text to match colour scheme

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#85]
Hey Ivar, hope you good
Just a thought but would it be cool to instead of using the colour red for not yet aired title to the dynamic colour you are using for other elements to match the poster (the little scrollbar)

like here
![Screenshot (482)](https://github.com/user-attachments/assets/75551b85-ab5d-464c-b3c2-365661c407e1)
![Screenshot (479)](https://github.com/user-attachments/assets/3f14f115-12ed-4cca-b23e-f3b97ae32633)

the red for some doesn't seem so nice, but as long as it's not white, you get the idea that it's not aired yet.

EDIT:
so it will look something like this
<img width="1280" alt="new screenshot" src="https://github.com/user-attachments/assets/fb4c63a4-726f-4d85-abf6-38e139c2a2e6">

the color scheme is preserved

**Comment by ivarbrandt** [comment]
That color comes from the addon. I can't do anything about that.

**Comment by hcgiub001** [comment]
I'll ask Tikipeter if a skinner is allowed to overwrite the colour to his own choice

**Comment by ivarbrandt** [comment]
Alright. Btw, try clearing your blur cache and see if that fixes the background not blurring correctly for you.

**Comment by hcgiub001** [comment]
I cleared all the caches and restarted kodi. seems same.
https://streamable.com/t3djcu

It's probably me, I change skins around constantly and add new addons. I'm going to do a fresh install of windows soon anyway so It's fine. thanks

**Comment by hcgiub001** [comment]
I know you hate complication and probably close the issue but I was thinking of something else. 
![Screenshot (484)](https://github.com/user-attachments/assets/c74c0f3a-f4cf-4578-864f-23fb1b21ef8c)

are you using an image overlay for the shadow?

I like the pulsating effect of the glow behind posters, what do you think of the idea of that shadow overlay changing position constantly. so right now the shadow is top right, you can have the centre of the shadow focused slowly around the screen so the whole background seems to be moving. 
having it go in random walks (the darkest part of the shadow) would be engaging for the brain.

just ignore this if you have no interest. I'll wait on Tikipeter's response if he has the motivation to do it (been throwing out lots of issues at him to)

**Comment by hcgiub001** [comment]
thanks. some things you find out after you tried it that it's not what you thought lol.

**Comment by ivarbrandt** [comment]
Exactly. Sometimes you won't know until after you implement it and run with it for awhile.

**Comment by hcgiub001** [comment]
Unfortunately Tikipeter said, it would need to support all skins unfortunately. Not really possible. worth a try thanks
