### ISSUE TITLE
dim out unaired episodes

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#87]
from 
![Screenshot (499)](https://github.com/user-attachments/assets/546489c2-f35e-4beb-9217-9c6b5491f39d)

to something like
<img width="1280" alt="new" src="https://github.com/user-attachments/assets/cc9de160-bb05-4d34-b925-3b4682c3c2a4">

I personally don't like it, maybe it's too much and It messes up the great poster for it. just thought to throw it out and see if you think it could be nice

edit: it's growing on me lol
edit 2: if you liked this you could also undim if a user hovers over an unaired episode.

**Comment by ivarbrandt** [comment]
Nah

**Comment by npmstart-pray** [comment]
What about dimming out viewed episodes?

**Comment by hcgiub001** [comment]
why dim out view episodes, you'll not see the nice thumbnails for them

**Comment by npmstart-pray** [comment]
To show me that I’ve already seen them.   I find the little checkmarks to be difficult to see at times. Sent from my latest communicator device somewhere in space. On Sep 2, 2024, at 11:52, hcgiub001 ***@***.***> wrote:﻿
why dim out view episodes, you'll not see the nice thumbnails for them

**Comment by hcgiub001** [comment]
> To show me that I’ve already seen them.   I find the little checkmarks to be difficult to see at times. Sent from my latest communicator device somewhere in space. On Sep 2, 2024, at 11:52, hcgiub001 ***@***.***> wrote:﻿ why dim out view episodes, you'll not see the nice thumbnails for them —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

if you bring up side bar (press up or left) you will see this
![Screenshot (521)](https://github.com/user-attachments/assets/f75cd6e7-6e28-457b-893b-868def04bded)
 if you click on all videos you can toggle to unwatched, watched. so you want unwatched
![Screenshot (522)](https://github.com/user-attachments/assets/51bb61ac-5838-4a9b-8e5c-43c84b499b36)

all the watched videos will dissapear until you click on toggle again
