### ISSUE TITLE
Flix List title/ratings overlap.

### ISSUE THREAD

**Issue by cp3817** [ivarbrandt/skin.nimbus#88]
I seem to be having an issue where the titles of some TV Show episodes overlap with their respective ratings on the Flix List layout. I've attached a video where you can hopefully see this. I can't be certain if it's a genuine issue or it only happens for me. Thanks anyway for the skin!

https://github.com/user-attachments/assets/f592a513-ea0d-48d0-b5f8-b92a3fd7bc73

**Comment by ivarbrandt** [comment]
Fixed for next update. Might be awhile before it's up though.

**Comment by ivarbrandt** [comment]
Fix is up.
