### ISSUE TITLE
pressing i in fullscreenvideo does nothing

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#89]
Hey Ivar, hope your well

action: pressing i on keyboard in full screenvideo

expected behaviour , brings up this screen
![Screenshot (520)](https://github.com/user-attachments/assets/920e2afd-6610-4d18-ba06-40b295f9fc7c)

what happens: nothing

another thing if I press the i icon , it will have the new menu (as shown in above screenshot) then when I close that menu and press pause again, the new menu comes on (with the information) first. Not sure if that is by design, it just differed from before.

thanks

**Comment by ivarbrandt** [comment]
Show me a video of this behavior.

**Comment by hcgiub001** [comment]
https://streamable.com/lxz426

you can see what keypresses I do. when I press i, nothing happens.
pressing the i on the OSD in kodi (in Nimbus) will change the OSD but the new OSD stays when you press back and press enter again.
I would have expected the older OSD to remain?
the OSD doesn't matter but pressing i, in other skins brings up OSD

**Comment by ivarbrandt** [comment]
You're confusing the modular OSD style for an info screen. There isn't an info screen, just two OSD styles. So it's working just like it should.

**Comment by hcgiub001** [comment]
> You're confusing the modular OSD style for an info screen. There isn't an info screen, just two OSD styles. So it's working just like it should.
> 
> Btw, I have a new view in the next update that I think you'll like.

so excited!!!!! can't wait!!! :D

**Comment by ivarbrandt** [comment]
Update is up.
