### ISSUE TITLE
Test Repo

### ISSUE THREAD

**Issue by ryankeast** [ivarbrandt/skin.nimbus#9]
So sorry to post as it's not really an "Issue". But I would love to install and have a play (I appreciate it's maybe not going to be available for major release).  I assume this is in a "test" repository. . I can not seem to find the link at all. Current user of Fentastic so interested to check this out. Thanks for all your work.

**Comment by ryankeast** [comment]
Worked it out. Sorry to waste your time.

**Comment by ivarbrandt** [comment]
All good. You can get the test repo here: https://github.com/ivarbrandt/repository.ivarbrandt.test/blob/main/repository.ivarbrandt.test-1.0.0.zip
