### ISSUE TITLE
Nimbus doesn't like some specific poster artwork?

### ISSUE THREAD

**Issue by basicals** [ivarbrandt/skin.nimbus#90]
Running latest version 0.1.22 on Shield TV, with tmbd and fanart.tv artwork enabled from the official tmdb.org addon.

Basically some posters won't be displayed on nimbus widgets, but are correctly displayed on kodi's estuary skin:

Not shown in widget:
![PXL_20240904_090750019](https://github.com/user-attachments/assets/40297782-0f4d-4cf4-9732-57f9b414d1f5)

Shown in info screen:
![PXL_20240904_090741522](https://github.com/user-attachments/assets/5f17e504-8d4a-4f6e-a997-e7ab39e3f388)

Estuary:
![PXL_20240904_085913494](https://github.com/user-attachments/assets/839dd294-8b98-4f14-937a-a2e6ccab1ce6)

[Link to artwork](https://www.themoviedb.org/movie/104645-dream-theater-dark-side/images/posters)

This is happening to some 5 different movies, from a set of about 50. The rest display correctly. The widget corresponds to a .json kodi smartlist, via the skin variables addon.

**Comment by ivarbrandt** [comment]
I've made some changes for next update that makes the artwork less restrictive. Hopefully it fixes your issue.

**Comment by ivarbrandt** [comment]
Fix is up.
