### ISSUE TITLE
Love PosterFlow

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#91]
Love the new viewtype! it's better than what I had! I set the down arrow to open information. it's instant. Great work. 
I have a request, when inside Information screen and we are not on cast where pressing right means we look at cast, can we have pressing right otherwise in information triggers trailer? I miss one button trailer.
I like looking at poster as long as I feel I have understood it, some posters have more information than others and I miss having easy access to trailer. it's fine if you can't.

Also one thing I noticed. in information screen we don't have the collection icon, having that somewhere would be sweet.

really love the view by the way! great job. Thankyou

**Comment by hcgiub001** [comment]
I'm wondering if instead of a separate screen for information , why not have the information screen you already have that shows the poster, plus we get to explore other elements in the information (the one where you can set on side bar on down action)

This has less dissonance because the mini poster keeps it tied together. or even allow to set which information screen would you rather have, I think more value in your nice information screen?

**Comment by ivarbrandt** [comment]
I thought you'd like it.

The collection icon is available in the auto info display. You can have that enabled then make the down action trailer.

If you want to keep the on down action as information, then the trailer is available in there too with one click.

**Comment by hcgiub001** [comment]
thanks, yeah it's pretty awesome! it takes a while to get used to, been using flix for so long but the way I learnt how good it really is when I go to content I've not come across before.
Just a thought, you have 2 information screens. The auto one you have now and your skin information screen (When you press down)
can we choose which information we want for auto?
if we can have the skin information screen we basically replace the fanart with poster (more consistency) and we get access to all the information stuff. thoughts?

so on the side you could have "auto information screen"
and have option 1 or 2.
then in information screen we could have the right key also close information screen but we don't change the movie.
anyway, it's fine if not. great work and thanks!

**Comment by hcgiub001** [comment]
I really am enjoying it more and more! I probably main this now and would be brainstorming ideas to test you lol.

I have one idea, hear me out.
The auto information doesn't fit in with the design and animations. The fanart behind the text, I'm not a fan of. So I was thinking. Slide out an information card behind the centre poster (so right edge of poster you'll slide out an information card to fill the right third of the screen)
then when users press right the information card slides back behind the poster and we can move left or right to another poster.

example when it's slid out all the way
(something like this but only once)
https://streamable.com/fpzoyl

just throwing out ideas.

**Comment by ivarbrandt** [comment]
> The auto information doesn't fit in with the design and animations.

I disagree. It fits perfectly because the transition from full screen images (posters) to another fullscreen image (fanart), doesn't clash the way a transition to a blurred background image would.

The card sliding out is how I originally was going to do it. But having the info on the right side of the screen looked off. I would need to make the focused item the 2nd or 3rd to fit in the information and that's not the look I'm going for with this view.

What I can do is make the delay for auto info configurable. That way you have longer to view the poster.

**Comment by hcgiub001** [comment]
a delay would be great, I think I'll just extend by a second personally, thanks for great work

**Comment by ivarbrandt** [comment]
A configurable delat has been added for next update. Might be awhile before it's up.

**Comment by hcgiub001** [comment]
awesome! thankyou

**Comment by ivarbrandt** [comment]
Update is up.
