### ISSUE TITLE
tmdb helper rating

### ISSUE THREAD

**Issue by xavengedx** [ivarbrandt/skin.nimbus#92]
Hello Ivar, thanks for the update, I really like using POV + Nimbus, but the addon that brings the best experience for my language is TMDB HELPER, but the tv-show ratings don't appear when I use it, can you fix that ?

![screenshot00000](https://github.com/user-attachments/assets/9a51855a-e3fc-4c35-a38f-bf709fb3f204)

**Comment by ivarbrandt** [comment]
Nimbus does not support TMDbHelper.
