### ISSUE TITLE
Can't skip videos using progress bar

### ISSUE THREAD

**Issue by EloneMusk** [ivarbrandt/skin.nimbus#94]
Unlike the default video player there is no functionality to skip video using progress bar by using android tv remote and selecting the progress bar.

**Comment by ivarbrandt** [comment]
Yes, that's true.

**Comment by EloneMusk** [comment]
Are you going to implement this into nimbus?

For now I have switched back to Fentastic. This is really important feature for me. Takes too much time to skip videos otherwise.

**Comment by ivarbrandt** [comment]
> Are you going to implement this into nimbus?

Probably not. You can seek in increments by clicking left and right during video playback. If there are chapters available, up and down skips to the previous/next chapter.

**Comment by hcgiub001** [comment]
You can change the behaviour of your remote in different screens you are in.
when you are in playback you are in fullscreenvideo
Install Keymap editor from kodi repo
and you can set any buttons on your remote that do anything you want.
![Screenshot (534)](https://github.com/user-attachments/assets/4da59bd6-5f7c-4957-ac90-d979d322e297)
![Screenshot (535)](https://github.com/user-attachments/assets/020db5ee-38f3-4ba0-b2ce-4e2f75d073c0)

![Screenshot (536)](https://github.com/user-attachments/assets/88637fe0-000a-405c-8d99-fead78cf28d9)
![Screenshot (537)](https://github.com/user-attachments/assets/a4500a0b-c94a-428b-85fc-0b40a245d7fc)

I think you want next and previous?

if you don't have any extra buttons then you can install a fork of keymap editor that has the ability to have actions for long press on a button
https://github.com/bleak-lodge/script.keymapedit

so now you you have have it set that when you long press on volume up , it goes to next video and long press volume down goes previous.

if you decide to use long press on a button, it adds a slight delay, but you will still be able to use volume keys.

you can even set change buttons when you are on the progress bar menu so I believe that is the Video OSD Settings

**Comment by ivarbrandt** [comment]
I just checked just to make sure, and pressing left or right during video playback in Nimbus does the exact same thing as highlighting the progress bar nub in FENtastic and then pressing left or right. It's actually faster and easier in Nimbus because you don't have to highlight the progress bar, just press left or right and it will begin seeking.
