### ISSUE TITLE
Missing info with List view using Umbrella

### ISSUE THREAD

**Issue by VelimirSaban** [ivarbrandt/skin.nimbus#97]
Hi,

When viewing episodes, using Umbrella and List view, no info about the marked episode is visible. When I use FenLight, the info is visible. Maybe it's something to do with the addon settings, but I couldn't find it.

Umbrella:

![Umbrella](https://github.com/user-attachments/assets/77341d89-31d4-414a-8c99-359e8d691dd0)

FenLight:

![FenLight](https://github.com/user-attachments/assets/8ae0b5e4-7bdd-454e-9ae2-5cd7a455a473)

**Comment by ivarbrandt** [comment]
Fixed for next update.

Thanks for bringing this to my attention. Fixing this revealed a whole slew of bugs related to the way that Nimbus interacts with Umbrella.
