### ISSUE TITLE
Nimus update error

### ISSUE THREAD

**Issue by hcgiub001** [ivarbrandt/skin.nimbus#98]
[kodi.log](https://github.com/user-attachments/files/17004918/kodi.log)

not sure if it's because I messed something up, I had same issue with your 1.23 backup. when I install it goes all black then I close kodi and nothing changed when I restart

**Comment by hcgiub001** [comment]
Someone on reddit posted

"Hey, I reverted back to 0.1.23 but when it installed 0.1.24 it also updated Nimbus Helper to 0.0.43 and now I'm getting a Nimbus Helper error on my Shield every time I load up. Am I supposed to downgrade the helper to 0.0.42? And if so, how do I do that? lol. Thanks if you can help."

https://www.reddit.com/r/Addons4Kodi/comments/1ffwbtp/comment/ln7a41a/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

good question, maybe having a copy of skin.helper the latest version that was out when the latest old style Nimbus was out would be good? I think I got a copy so will give it to him for now

**Comment by hcgiub001** [comment]
I changed to Estuary then to Nimbus and it worked

**Comment by ivarbrandt** [comment]
Nimbus has been reverted back to the Netflix layout.

**Comment by hcgiub001** [comment]
you worked hard on widget layout. I'm sure the stuff you learned will come in handy in future, Netflix Nimbus
