### ISSUE TITLE
Can't use decimal point for Auto info delay.

### ISSUE THREAD

**Issue by TheSymm** [ivarbrandt/skin.nimbus#99]
I would love to be able to set it to something like 0.5 seconds, as I find 0 is too quick and 1 is too slow. Maybe a swap to milliseconds would be the move,
Regardless it's an awesome update and you have come up with a very ingenious way to display the info.

Awesome work.

**Comment by ivarbrandt** [comment]
Nimbus has been reverted back to the Netflix layout.
